/**
 * Système de niveaux culinaires (1-10)
 * Détermine les techniques, précision et logique disponibles
 */

export type ChefLevel = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

export interface LevelCapabilities {
  level: ChefLevel;
  name: string;
  description: string;
  techniques: string[]; // Techniques disponibles
  precision: "loose" | "moderate" | "strict" | "exact";
  minRecipeQuality: number; // Score minimum pour accepter une recette (0-100)
  advancedFeatures: string[];
  temperature: "approximate" | "range" | "exact";
  timing: "rough" | "careful" | "precise" | "exact";
  platingStandard: "rustic" | "simple" | "refined" | "haute-cuisine";
}

const LEVEL_DEFINITIONS: Record<ChefLevel, LevelCapabilities> = {
  1: {
    level: 1,
    name: "Novice",
    description: "Recettes simples, 3-4 étapes basiques",
    techniques: ["boil", "mix", "bake"],
    precision: "loose",
    minRecipeQuality: 30,
    advancedFeatures: [],
    temperature: "approximate",
    timing: "rough",
    platingStandard: "rustic",
  },
  2: {
    level: 2,
    name: "Apprentice",
    description: "Recettes classiques, techniques élémentaires",
    techniques: ["boil", "mix", "bake", "fry", "simmer"],
    precision: "loose",
    minRecipeQuality: 40,
    advancedFeatures: ["flavor-balance"],
    temperature: "approximate",
    timing: "rough",
    platingStandard: "rustic",
  },
  3: {
    level: 3,
    name: "Intermediate",
    description: "Maîtrise des techniques de base",
    techniques: ["boil", "mix", "bake", "fry", "simmer", "sear", "poach", "braise"],
    precision: "moderate",
    minRecipeQuality: 50,
    advancedFeatures: ["flavor-balance", "texture-control"],
    temperature: "range",
    timing: "careful",
    platingStandard: "simple",
  },
  4: {
    level: 4,
    name: "Advanced",
    description: "Compétence solide, recettes complexes",
    techniques: [
      "boil",
      "mix",
      "bake",
      "fry",
      "simmer",
      "sear",
      "poach",
      "braise",
      "glaze",
      "reduce",
      "emulsify",
    ],
    precision: "moderate",
    minRecipeQuality: 60,
    advancedFeatures: ["flavor-balance", "texture-control", "sauce-making"],
    temperature: "range",
    timing: "careful",
    platingStandard: "simple",
  },
  5: {
    level: 5,
    name: "Expert",
    description: "Maîtrise du timing, gestion des portions",
    techniques: [
      "boil",
      "mix",
      "bake",
      "fry",
      "simmer",
      "sear",
      "poach",
      "braise",
      "glaze",
      "reduce",
      "emulsify",
      "deglaze",
      "temper",
      "sous-vide",
    ],
    precision: "strict",
    minRecipeQuality: 70,
    advancedFeatures: [
      "flavor-balance",
      "texture-control",
      "sauce-making",
      "scaling",
      "ingredient-substitution",
    ],
    temperature: "exact",
    timing: "precise",
    platingStandard: "refined",
  },
  6: {
    level: 6,
    name: "Professional Chef",
    description: "Cuisine pro, mises en place perfectionnées",
    techniques: [
      "boil",
      "mix",
      "bake",
      "fry",
      "simmer",
      "sear",
      "poach",
      "braise",
      "glaze",
      "reduce",
      "emulsify",
      "deglaze",
      "temper",
      "sous-vide",
      "smoke",
      "clarify",
      "julienne",
    ],
    precision: "strict",
    minRecipeQuality: 75,
    advancedFeatures: [
      "flavor-balance",
      "texture-control",
      "sauce-making",
      "scaling",
      "ingredient-substitution",
      "mise-en-place",
      "flavor-layering",
    ],
    temperature: "exact",
    timing: "precise",
    platingStandard: "refined",
  },
  7: {
    level: 7,
    name: "Master Chef",
    description: "Créativité contrôlée, innovations justifiées",
    techniques: [
      "boil",
      "mix",
      "bake",
      "fry",
      "simmer",
      "sear",
      "poach",
      "braise",
      "glaze",
      "reduce",
      "emulsify",
      "deglaze",
      "temper",
      "sous-vide",
      "smoke",
      "clarify",
      "julienne",
      "carpaccio",
      "terrine",
      "sphere",
    ],
    precision: "exact",
    minRecipeQuality: 80,
    advancedFeatures: [
      "flavor-balance",
      "texture-control",
      "sauce-making",
      "scaling",
      "ingredient-substitution",
      "mise-en-place",
      "flavor-layering",
      "molecular-techniques",
      "heritage-knowledge",
    ],
    temperature: "exact",
    timing: "exact",
    platingStandard: "haute-cuisine",
  },
  8: {
    level: 8,
    name: "Executive Chef",
    description: "Chef exécutif, direction culinaire",
    techniques: [
      "boil",
      "mix",
      "bake",
      "fry",
      "simmer",
      "sear",
      "poach",
      "braise",
      "glaze",
      "reduce",
      "emulsify",
      "deglaze",
      "temper",
      "sous-vide",
      "smoke",
      "clarify",
      "julienne",
      "carpaccio",
      "terrine",
      "sphere",
      "consomme",
      "ballottine",
      "pate",
    ],
    precision: "exact",
    minRecipeQuality: 85,
    advancedFeatures: [
      "flavor-balance",
      "texture-control",
      "sauce-making",
      "scaling",
      "ingredient-substitution",
      "mise-en-place",
      "flavor-layering",
      "molecular-techniques",
      "heritage-knowledge",
      "menu-engineering",
      "food-psychology",
    ],
    temperature: "exact",
    timing: "exact",
    platingStandard: "haute-cuisine",
  },
  9: {
    level: 9,
    name: "Michelin Star Chef",
    description: "Excellence culinaire, innovation de haut niveau",
    techniques: [
      "boil",
      "mix",
      "bake",
      "fry",
      "simmer",
      "sear",
      "poach",
      "braise",
      "glaze",
      "reduce",
      "emulsify",
      "deglaze",
      "temper",
      "sous-vide",
      "smoke",
      "clarify",
      "julienne",
      "carpaccio",
      "terrine",
      "sphere",
      "consomme",
      "ballottine",
      "pate",
      "foamage",
      "gel-making",
      "fermentation",
      "meat-aging",
    ],
    precision: "exact",
    minRecipeQuality: 90,
    advancedFeatures: [
      "flavor-balance",
      "texture-control",
      "sauce-making",
      "scaling",
      "ingredient-substitution",
      "mise-en-place",
      "flavor-layering",
      "molecular-techniques",
      "heritage-knowledge",
      "menu-engineering",
      "food-psychology",
      "seasonal-curation",
      "technique-innovation",
    ],
    temperature: "exact",
    timing: "exact",
    platingStandard: "haute-cuisine",
  },
  10: {
    level: 10,
    name: "Légendaire Chef Étoilé",
    description: "Maîtrise totale, créativité absolue, perfection culinaire",
    techniques: [
      "boil",
      "mix",
      "bake",
      "fry",
      "simmer",
      "sear",
      "poach",
      "braise",
      "glaze",
      "reduce",
      "emulsify",
      "deglaze",
      "temper",
      "sous-vide",
      "smoke",
      "clarify",
      "julienne",
      "carpaccio",
      "terrine",
      "sphere",
      "consomme",
      "ballottine",
      "pate",
      "foamage",
      "gel-making",
      "fermentation",
      "meat-aging",
      "sous-pression",
      "cryogenic",
      "demi-glace-mastery",
      "flavor-archaeology",
    ],
    precision: "exact",
    minRecipeQuality: 95,
    advancedFeatures: [
      "flavor-balance",
      "texture-control",
      "sauce-making",
      "scaling",
      "ingredient-substitution",
      "mise-en-place",
      "flavor-layering",
      "molecular-techniques",
      "heritage-knowledge",
      "menu-engineering",
      "food-psychology",
      "seasonal-curation",
      "technique-innovation",
      "ingredient-mastery",
      "cultural-fusion",
      "impossible-innovation",
    ],
    temperature: "exact",
    timing: "exact",
    platingStandard: "haute-cuisine",
  },
};

export function getLevelCapabilities(level: ChefLevel = 10): LevelCapabilities {
  return LEVEL_DEFINITIONS[level] || LEVEL_DEFINITIONS[10];
}

export function isAvailableTechnique(level: ChefLevel, technique: string): boolean {
  const caps = getLevelCapabilities(level);
  return caps.techniques.includes(technique);
}

export function hasAdvancedFeature(level: ChefLevel, feature: string): boolean {
  const caps = getLevelCapabilities(level);
  return caps.advancedFeatures.includes(feature);
}

export function canAcceptRecipe(level: ChefLevel, recipeQuality: number): boolean {
  const caps = getLevelCapabilities(level);
  return recipeQuality >= caps.minRecipeQuality;
}

// Export default level 10 (Chef Étoilé)
export const DEFAULT_CHEF_LEVEL: ChefLevel = 10;
