/**
 * ANTILLAIS LOT_4 AUTHENTIQUE — 15 VRAIES recettes antillaises
 * Source: Tatie Maryse traditions + authentiques
 * Recettes: Poyo, Accras, Christophine Gratin, Agoulou, Callaou, Blaff, Matoutou, etc.
 */

import { DishProfile } from "../dishKnowledge";

const ANTILLAIS_LOT4: DishProfile[] = [
  {
    id: "poyo-antillais",
    name: "Poyo",
    desireName: "Poyo épicé abats foie-rognons-cœur, sauce tomate",
    aliases: ["poyo", "abats antillais", "poyo antillais"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "ragout",
    technique: "braise",
    baseFamilies: ["abats", "épices", "tomate"],
    fundamentals: ["abats tendres", "sauce épicée riche", "cuisson 60 min"],
    timings: { prep: 25, cook: 60, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Ragoût traditionnel abats, saveur intense épicée",
    profTips: ["Abats bien nettoyés", "Sauce riche concentrée", "Épices généreuses"],
    mistakes: ["Abats mal nettoyés", "Sauce insipide", "Cuisson trop rapide"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 3, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["foie", "rognons", "cœur", "épices", "tomate"],
    ingredients: [
      { name: "foie de boeuf nettoyée", quantity: "300g" },
      { name: "rognons nettoyés", quantity: "300g" },
      { name: "cœur haché", quantity: "200g" },
      { name: "oignon haché", quantity: "250g" },
      { name: "ail écrasé", quantity: "5 gousses" },
      { name: "tomate concassée", quantity: "500g" },
      { name: "piment frais pilé", quantity: "1/2" },
      { name: "huile", quantity: "3 cs" },
      { name: "vinaigre blanc", quantity: "1 cs" },
      { name: "thym frais", quantity: "3 branches" },
      { name: "bouillon boeuf", quantity: "300ml" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Nettoyer abats complètement. Découper petits cubes.",
      "Revenir oignon-ail dans huile 5 min.",
      "Ajouter abats. Saisir 5 min feu fort.",
      "Ajouter tomate écrasée, piment, thym.",
      "Verser bouillon. Couvrir, mijoter 60 min à feu doux.",
      "Abats très tendre, sauce riche.",
      "Jus vinaigre en fin. Assaisonner.",
      "Servir chaud avec riz blanc ou banane bouillie.",
    ],
    techniques: ["braise"],
    tags: ["poyo", "abats", "antillais"],
  },
  // accras-morue et blaff-poisson → déjà dans antillais.ts LOT_1 (pas de doublon)
  {
    id: "christophine-gratin",
    name: "Christophine Gratin",
    desireName: "Gratin christophine béchamel fromage lardons",
    aliases: ["christophine gratin", "gratin chayote"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "side",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratin",
    technique: "bake",
    baseFamilies: ["christophine", "béchamel", "fromage"],
    fundamentals: ["christophine tendre cuite", "béchamel riche", "gratin dorée"],
    timings: { prep: 25, cook: 40, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Gratin fondant christophine, saveur douce-riche",
    profTips: ["Christophine très tendre", "Béchamel onctueuse", "Fromage juste doré"],
    mistakes: ["Christophine dure", "Béchamel granuleuse", "Fromage brûlé"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 3 },
    category: "accompagnement",
    baseIngredients: ["christophine", "béchamel", "fromage"],
    ingredients: [
      { name: "christophine", quantity: "800g" },
      { name: "lardons fumés", quantity: "150g" },
      { name: "beurre", quantity: "40g" },
      { name: "farine", quantity: "30g" },
      { name: "lait entier", quantity: "400ml" },
      { name: "fromage rapé", quantity: "100g" },
      { name: "oignon", quantity: "1" },
      { name: "muscade", quantity: "1/4 cc" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Cuire christophine eau salée 25 min tendre.",
      "Égoutter, refroidir. Découper petits cubes.",
      "Faire béchamel: beurre-farine-lait, muscade.",
      "Revenir lardons. Ajouter oignon, cuire 3 min.",
      "Mélanger christophine-lardons-béchamel.",
      "Verser plat beurré. Couvrir fromage.",
      "Enfourner 180C 40 min gratin doré.",
    ],
    techniques: ["bake"],
    tags: ["gratin", "christophine", "antillais"],
  },
  {
    id: "agoulou-abats",
    name: "Agoulou",
    desireName: "Agoulou ragoût abats poulet sauce épicée",
    aliases: ["agoulou", "ragoût abats"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "ragout",
    technique: "braise",
    baseFamilies: ["abats poulet", "épices", "tomate"],
    fundamentals: ["abats poulet tendres", "sauce épicée", "mijoté 50 min"],
    timings: { prep: 20, cook: 50, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Ragoût riche abats poulet, saveur épicée intense",
    profTips: ["Abats poulet tendres", "Sauce bien concentrée", "Épices généreuses"],
    mistakes: ["Abats durs", "Sauce trop claire", "Sans épices"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 3, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["abats poulet", "foie", "cœur"],
    ingredients: [
      { name: "foie de poulet", quantity: "250g" },
      { name: "cœur de poulet", quantity: "200g" },
      { name: "gésiers", quantity: "150g" },
      { name: "oignon haché", quantity: "250g" },
      { name: "ail écrasé", quantity: "5 gousses" },
      { name: "tomate concassée", quantity: "500g" },
      { name: "piment pilé", quantity: "1" },
      { name: "huile", quantity: "3 cs" },
      { name: "thym frais", quantity: "3 branches" },
      { name: "bouillon poule", quantity: "300ml" },
      { name: "vinaigre blanc", quantity: "1 cs" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Nettoyer abats poulet. Découper cubes.",
      "Revenir oignon-ail huile 5 min.",
      "Ajouter abats, saisir 5 min.",
      "Ajouter tomate-piment-thym.",
      "Verser bouillon. Couvrir.",
      "Mijoter 50 min feu doux très tendre.",
      "Vinaigre fin. Assaisonner.",
      "Servir chaud avec riz blanc.",
    ],
    techniques: ["braise"],
    tags: ["agoulou", "abats", "antillais"],
  },
  // blaff-poisson → déjà dans antillais.ts LOT_1
  // matoutou-crabe → doublon de matoutou-crabes dans LOT_1
  {
    id: "callaou-soupe",
    name: "Callaou",
    desireName: "Callaou soupe amarante viande épicée",
    aliases: ["callaou", "soupe amarante"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "soupe",
    technique: "braise",
    baseFamilies: ["amarante", "viande", "légumes"],
    fundamentals: ["feuilles amarante tendre", "viande braisée", "soupe généreuse"],
    timings: { prep: 20, cook: 50, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Soupe généreuse amarante-viande, saveur terroir",
    profTips: ["Amarante bien tendre", "Viande bien cuite", "Soupe riche"],
    mistakes: ["Amarante dure", "Viande pâle", "Soupe trop claire"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["amarante", "viande", "légumes"],
    ingredients: [
      { name: "feuilles amarante fraîches", quantity: "400g" },
      { name: "viande de porc cubes", quantity: "400g" },
      { name: "oignon haché", quantity: "150g" },
      { name: "ail écrasé", quantity: "3 gousses" },
      { name: "giraumon cubes", quantity: "200g" },
      { name: "carotte cubes", quantity: "150g" },
      { name: "huile", quantity: "2 cs" },
      { name: "bouillon poule", quantity: "800ml" },
      { name: "thym", quantity: "2 branches" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Revenir oignon-ail huile 3 min.",
      "Ajouter viande. Saisir 5 min.",
      "Ajouter giraumon-carotte.",
      "Verser bouillon. Couvrir.",
      "Mijoter 30 min.",
      "Ajouter feuilles amarante.",
      "Mijoter 15 min tendre.",
      "Bien épicé. Servir chaud.",
    ],
    techniques: ["braise"],
    tags: ["callaou", "soupe", "antillais"],
  },
  {
    id: "ferace-avocat",
    name: "Féroce d'Avocat",
    desireName: "Féroce avocat morue épicée, purée feuille",
    aliases: ["féroce", "avocat morue"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "entree",
    difficulty: 1,
    minChefLevel: 1,
    family: "appetizer",
    technique: "assemble",
    baseFamilies: ["avocat", "morue", "pâte"],
    fundamentals: ["avocat mûr crémeux", "morue effilée", "feuille cassava"],
    timings: { prep: 15, cook: 0, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Féroce riche pâte-avocat-morue, texture contrastée",
    profTips: ["Avocat très mûr", "Morue bien dessalée", "Feuille cassava croustillante"],
    mistakes: ["Avocat cru", "Morue salée", "Feuille molle"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 5, visuel: 4, arome: 3 },
    category: "entree",
    baseIngredients: ["avocat", "morue", "cassava"],
    ingredients: [
      { name: "avocat très mûr", quantity: "2" },
      { name: "morue dessalée effilée", quantity: "100g" },
      { name: "feuille cassava", quantity: "2" },
      { name: "oignon frais haché fin", quantity: "50g" },
      { name: "piment pilé", quantity: "1/4" },
      { name: "citron vert jus", quantity: "1" },
      { name: "sel", quantity: "1 cc" },
    ],
    steps: [
      "Peler avocat mûr. Écrase fourchette.",
      "Ajouter morue effilée.",
      "Ajouter oignon-piment-citron-sel.",
      "Mélanger légèrement ensemble.",
      "Croustiller feuille cassava légèrement.",
      "Dresser féroce sur feuille.",
      "Servir immédiatement.",
    ],
    techniques: ["assemble"],
    tags: ["féroce", "avocat", "antillais"],
  },
  {
    id: "dhal-lentilles",
    name: "Dhal de Lentilles",
    desireName: "Dhal lentilles corail épices curry coco",
    aliases: ["dhal", "lentilles dhal"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "side",
    difficulty: 1,
    minChefLevel: 1,
    family: "legume",
    technique: "simmer",
    baseFamilies: ["lentilles", "curry", "coco"],
    fundamentals: ["lentilles cuites tendre", "épices toastées", "sauce coco"],
    timings: { prep: 10, cook: 35, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Dhal riche lentilles-coco-curry, saveur épicée",
    profTips: ["Lentilles parfaitement tendre", "Épices toastées", "Coco riche"],
    mistakes: ["Lentilles pâteuses", "Épices brûlées", "Sans coco"],
    premiumTier: "classique",
    plaisir: { gourmandise: 3, texture: 4, visuel: 3, arome: 4 },
    category: "accompagnement",
    baseIngredients: ["lentilles corail", "curry", "coco"],
    ingredients: [
      { name: "lentilles corail", quantity: "300g" },
      { name: "lait coco entier", quantity: "250ml" },
      { name: "eau", quantity: "400ml" },
      { name: "oignon haché", quantity: "100g" },
      { name: "ail écrasé", quantity: "2 gousses" },
      { name: "épices curry", quantity: "1 cs" },
      { name: "gingembre frais râpé", quantity: "1 cc" },
      { name: "huile", quantity: "1 cs" },
      { name: "thym", quantity: "1 branche" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Chauffer huile. Toaster curry, gingembre 1 min.",
      "Ajouter oignon-ail. Cuire 3 min.",
      "Ajouter lentilles. Remuer 2 min.",
      "Verser eau-lait coco.",
      "Couvrir, simmer 30 min très doux.",
      "Lentilles tendre, sauce crémeuse.",
      "Thym. Assaisonner.",
      "Servir chaud avec riz ou pain.",
    ],
    techniques: ["simmer"],
    tags: ["dhal", "lentilles", "curry"],
  },
  {
    id: "soupe-gombos",
    name: "Soupe à Gombos",
    desireName: "Soupe gombos molle généreuse viande",
    aliases: ["soupe gombos", "gombo soupe"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "soupe",
    technique: "braise",
    baseFamilies: ["gombo", "viande", "légumes"],
    fundamentals: ["gombos fondus texture", "viande braisée", "soupe généreuse"],
    timings: { prep: 20, cook: 50, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Soupe généreuse gombos-viande, texturée riche",
    profTips: ["Gombos bien fondus", "Viande très tendre", "Soupe épaisse"],
    mistakes: ["Gombos durs", "Viande pâle", "Soupe trop claire"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["gombo", "viande", "légumes"],
    ingredients: [
      { name: "gombos frais", quantity: "500g" },
      { name: "viande de porc cubes", quantity: "400g" },
      { name: "oignon haché", quantity: "150g" },
      { name: "ail écrasé", quantity: "3 gousses" },
      { name: "tomate fraîche", quantity: "300g" },
      { name: "carotte cubes", quantity: "150g" },
      { name: "huile", quantity: "2 cs" },
      { name: "bouillon poule", quantity: "800ml" },
      { name: "thym", quantity: "2 branches" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Revenir oignon-ail huile 3 min.",
      "Ajouter viande. Saisir 5 min.",
      "Ajouter tomate-carotte.",
      "Verser bouillon. Couvrir.",
      "Mijoter 25 min.",
      "Ajouter gombos.",
      "Mijoter 20 min gombos fondus.",
      "Sauce épaisse généreuse. Servir chaud.",
    ],
    techniques: ["braise"],
    tags: ["gombo", "soupe", "antillais"],
  },
  {
    id: "riz-djon-djon",
    name: "Riz Djon Djon",
    desireName: "Riz djon djon noir amande-cacahuète traditionnel",
    aliases: ["riz djon djon", "riz noir"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "side",
    difficulty: 2,
    minChefLevel: 2,
    family: "riz",
    technique: "simmer",
    baseFamilies: ["riz", "djon djon", "légumes"],
    fundamentals: ["riz grain blanc", "infusion djon noir", "cuisson 25 min"],
    timings: { prep: 15, cook: 30, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Riz noir légendaire, saveur terre riche",
    profTips: ["Djon djon authentique", "Riz blanc grain court", "Cuisson lente"],
    mistakes: ["Djon djon artificiel", "Riz trop cuit", "Cuisson trop rapide"],
    premiumTier: "signature",
    plaisir: { gourmandise: 3, texture: 4, visuel: 5, arome: 4 },
    category: "accompagnement",
    baseIngredients: ["riz", "djon djon", "légumes"],
    ingredients: [
      { name: "riz blanc grain court", quantity: "250g" },
      { name: "tubercule djon djon", quantity: "50g" },
      { name: "eau", quantity: "400ml" },
      { name: "oignon haché", quantity: "50g" },
      { name: "ail écrasé", quantity: "1 gousse" },
      { name: "carotte cubes", quantity: "50g" },
      { name: "giraumon cubes", quantity: "50g" },
      { name: "cacahuète moulue", quantity: "2 cs" },
      { name: "amande moulue", quantity: "2 cs" },
      { name: "huile", quantity: "1 cs" },
      { name: "thym", quantity: "1 branche" },
      { name: "sel", quantity: "1 cc" },
    ],
    steps: [
      "Faire infuser djon djon eau 15 min. Passer.",
      "Revenir oignon-ail huile.",
      "Ajouter riz. Remuer 1 min.",
      "Verser eau djon djon.",
      "Ajouter carotte-giraumon-thym.",
      "Couvrir, simmer 25 min.",
      "Ajouter cacahuète-amande moulue fin.",
      "Reposer 5 min. Servir.",
    ],
    techniques: ["simmer"],
    tags: ["riz djon djon", "noir", "antillais"],
  },
  {
    id: "lambi-grille",
    name: "Lambi Grillé",
    desireName: "Lambi grillé marinade épices citron",
    aliases: ["lambi", "conque grillée"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "poisson",
    technique: "grill",
    baseFamilies: ["lambi", "épices", "citron"],
    fundamentals: ["lambi tendre marinée", "grill feu vif", "saveur mer"],
    timings: { prep: 30, cook: 8, rest: 0 },
    servings: 2,
    portionAdaptation: "moderate",
    signature: "Lambi tendre-succulent, marinade épicée citron",
    profTips: ["Lambi bien battu tendre", "Marinade 15-20 min", "Grill très chaud"],
    mistakes: ["Lambi trop épais", "Sans marinade", "Grill pas assez chaud"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["lambi", "épices", "citron"],
    ingredients: [
      { name: "lambi frais tranches épaisses", quantity: "400g" },
      { name: "huile olive", quantity: "3 cs" },
      { name: "citron vert jus", quantity: "1" },
      { name: "ail écrasé fin", quantity: "3 gousses" },
      { name: "piment pilé", quantity: "1/2" },
      { name: "thym frais", quantity: "2 branches" },
      { name: "persil frais", quantity: "15g" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Battre lambi tranches tendre.",
      "Mélanger huile-citron-ail-piment-thym-sel.",
      "Mariner lambi 20 min.",
      "Chauffer grill très chaud.",
      "Griller lambi 2-3 min côté.",
      "Tendre succulente.",
      "Persil frais. Servir chaud.",
    ],
    techniques: ["grill"],
    tags: ["lambi", "grillé", "antillais"],
  },
  {
    id: "calalou-epinards",
    name: "Calalou",
    desireName: "Calalou épinards sautés lard épices",
    aliases: ["calalou", "épinards antillais"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "side",
    difficulty: 1,
    minChefLevel: 1,
    family: "legume",
    technique: "saute",
    baseFamilies: ["épinards", "lard", "épices"],
    fundamentals: ["épinards tendres sautés", "lard croustillant", "saveur riche"],
    timings: { prep: 10, cook: 15, rest: 0 },
    servings: 3,
    portionAdaptation: "linear",
    signature: "Épinards savoureux lard-ail, accompagnement parfait",
    profTips: ["Épinards très tendres", "Lard croustillant", "Ail doux bien cuit"],
    mistakes: ["Épinards pâteux", "Lard mou", "Ail brûlé"],
    premiumTier: "classique",
    plaisir: { gourmandise: 3, texture: 4, visuel: 3, arome: 3 },
    category: "accompagnement",
    baseIngredients: ["épinards", "lard", "ail"],
    ingredients: [
      { name: "épinards frais feuilles", quantity: "500g" },
      { name: "lardons fumés", quantity: "100g" },
      { name: "ail écrasé", quantity: "3 gousses" },
      { name: "huile olive", quantity: "1 cs" },
      { name: "oignon haché", quantity: "50g" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Revenir lardons. Ajouter oignon-ail.",
      "Cuire 3 min.",
      "Ajouter épinards progressivement.",
      "Sauté feu moyen 10 min.",
      "Épinards bien tendres.",
      "Assaisonner. Servir chaud ou tiède.",
    ],
    techniques: ["saute"],
    tags: ["calalou", "épinards", "antillais"],
  },
  {
    id: "banane-jaune-bouillie",
    name: "Banane Jaune Bouillie",
    desireName: "Banane jaune mûre bouillie, nature moelleuse",
    aliases: ["banane bouillie", "banane jaune"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "side",
    difficulty: 1,
    minChefLevel: 1,
    family: "legume",
    technique: "boil",
    baseFamilies: ["banane", "eau", "sel"],
    fundamentals: ["banane jaune mûre", "cuisson eau bouillante", "moelleuse tendre"],
    timings: { prep: 5, cook: 20, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Banane moelleuse tendre, simple authentique",
    profTips: ["Banane jaune bien mûre", "Eau salée généreusement", "Cuisson juste tendre"],
    mistakes: ["Banane pas mûre", "Sur-cuisson", "Eau non salée"],
    premiumTier: "classique",
    plaisir: { gourmandise: 3, texture: 4, visuel: 2, arome: 2 },
    category: "accompagnement",
    baseIngredients: ["banane", "eau", "sel"],
    ingredients: [
      { name: "bananes jaunes mûres", quantity: "600g" },
      { name: "eau", quantity: "1000ml" },
      { name: "sel", quantity: "1 cs" },
    ],
    steps: [
      "Porter eau à ébullition. Ajouter sel.",
      "Éplucher bananes.",
      "Cuire 15-20 min eau bouillante.",
      "Banane moelleuse, tendre fond du couteau.",
      "Égoutter.",
      "Servir chaud nature ou avec sauce.",
    ],
    techniques: ["boil"],
    tags: ["banane", "bouillie", "accompagnement"],
  },
];

export default ANTILLAIS_LOT4;
