/**
 * ANTILLAIS LOT_4 FIXED — 15 recettes avec quantités correctes (g, ml, cs, cc)
 * Source: https://www.tatiemaryse.com/les-recettes/
 * Version: Toutes quantités en grammes/ml/cuillères/pièces réelles
 */

import { DishProfile } from "../dishKnowledge";

const ANTILLAIS_LOT4: DishProfile[] = [
  {
    id: "hachis-parmentier-banane",
    name: "Hachis Parmentier de banane jaune",
    desireName: "Hachis Parmentier créole, couche banane jaune fondante",
    aliases: ["hachis banane", "parmentier antillais"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratin",
    technique: "bake",
    baseFamilies: ["banane", "viande", "tomate"],
    fundamentals: ["bananes jaunes mûres", "viande hachée revenus", "gratin 25 min 180C"],
    timings: { prep: 25, cook: 35, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Couche banane fondante sous viande hachée épicée, gratinée",
    profTips: ["Choisir bananes jaunes mûres", "Viande bien revenus", "Gratin juste doré"],
    mistakes: ["Bananes trop vertes", "Viande pâle", "Four trop chaud"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["banane jaune", "viande hachée", "oignon", "ail", "tomate"],
    ingredients: [
      { name: "bananes jaunes mûres", quantity: "600g" },
      { name: "viande hachée", quantity: "500g" },
      { name: "oignon", quantity: "200g" },
      { name: "ail", quantity: "3 gousses" },
      { name: "tomate", quantity: "400g" },
      { name: "beurre", quantity: "30g" },
      { name: "fromage rapé", quantity: "100g" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Éplucher bananes, couper en rondelles. Disposer dans plat beurré.",
      "Faire revenir oignon et ail dans beurre. Ajouter viande hachée.",
      "Cuire viande 10 min. Ajouter tomate, sel, poivre. Laisser 5 min.",
      "Verser préparation viande sur bananes.",
      "Couvrir fromage rapé. Enfourner 180C pendant 25-30 min.",
      "Reposer 5 min avant service.",
    ],
    techniques: ["braise", "bake"],
    tags: ["gratin", "créole", "traditionnel"],
  },
  {
    id: "tarte-morue-oignon-creole",
    name: "Tarte morue oignon créole",
    desireName: "Tarte croustillante, garniture morue épicée oignon",
    aliases: ["tarte morue", "morue en tarte"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "tarte",
    technique: "bake",
    baseFamilies: ["morue", "oignon", "pate"],
    fundamentals: ["morue dessalée effilée", "oignon cuit doux", "pâte croustillante"],
    timings: { prep: 35, cook: 35, rest: 15 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Pâte croustillante garnie morue-oignon savoureux",
    profTips: ["Morue bien dessalée", "Oignons en fondue", "Pâte croustillante"],
    mistakes: ["Morue trop salée", "Oignons durs", "Pâte mouillée"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 4 },
    category: "tarte",
    baseIngredients: ["morue", "oignon", "ail", "pate", "huile"],
    ingredients: [
      { name: "pâte brisée", quantity: "350g" },
      { name: "morue dessalée", quantity: "300g" },
      { name: "oignon", quantity: "500g" },
      { name: "ail", quantity: "4 gousses" },
      { name: "piment", quantity: "1/2" },
      { name: "huile olive", quantity: "3 cs" },
      { name: "thym frais", quantity: "2 branches" },
    ],
    steps: [
      "Foncer moule avec pâte. Précuire 10 min à 200C.",
      "Émincer oignons. Cuire à l'huile 20 min à feu doux.",
      "Ajouter ail, piment, thym. Effilocher morue, ajouter au mélange.",
      "Verser garniture dans fond de tarte.",
      "Enfourner 180C pendant 20 min.",
      "Reposer 5 min avant service.",
    ],
    techniques: ["bake"],
    tags: ["tarte", "morue", "oignon"],
  },
  {
    id: "riz-lait-coco-curcuma",
    name: "Riz au lait coco curcuma",
    desireName: "Riz au lait onctueux coco-curcuma, sucré épices",
    aliases: ["riz coco", "riz lait antillais"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dessert",
    difficulty: 1,
    minChefLevel: 1,
    family: "dessert",
    technique: "simmer",
    baseFamilies: ["riz", "lait", "coco"],
    fundamentals: ["riz blanc grain court", "cuisson lente", "lait coco riche"],
    timings: { prep: 10, cook: 45, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Riz onctueux sucré, saveur coco-curcuma",
    profTips: ["Riz grain court", "Cuisson très douce", "Curcuma en fin"],
    mistakes: ["Riz grain long", "Cuisson trop rapide", "Curcuma brûlé"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "dessert",
    baseIngredients: ["riz", "lait coco", "sucre", "curcuma"],
    ingredients: [
      { name: "riz blanc court", quantity: "250g" },
      { name: "lait coco entier", quantity: "400ml" },
      { name: "lait entier", quantity: "200ml" },
      { name: "sucre", quantity: "60g" },
      { name: "curcuma", quantity: "1/2 cc" },
      { name: "vanille", quantity: "1 pod" },
      { name: "cannelle", quantity: "1/2 bâton" },
    ],
    steps: [
      "Rincer riz à eau froide.",
      "Verser riz dans casserole. Ajouter laits. Porter à ébullition.",
      "Baisser feu doux, couvrir. Laisser 45 min, remuant souvent.",
      "Ajouter sucre, curcuma, vanille, cannelle.",
      "Laisser 5 min à feu doux. Servir chaud ou tiède.",
    ],
    techniques: ["simmer"],
    tags: ["dessert", "riz", "coco"],
  },
  {
    id: "gratin-giraumon-lardons",
    name: "Gratin giraumon aux lardons",
    desireName: "Gratin fondant giraumon-lardons, fromage doré",
    aliases: ["gratin giraumon", "gratin courge"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "side",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratin",
    technique: "bake",
    baseFamilies: ["giraumon", "lardons", "fromage"],
    fundamentals: ["giraumon cuite tendre", "lardons croustillants", "gratin 25 min"],
    timings: { prep: 20, cook: 35, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Gratin sucré-salé giraumon tendre, lardons croustillants",
    profTips: ["Giraumon très tendre", "Lardons croustillants", "Fromage juste doré"],
    mistakes: ["Giraumon dure", "Lardons mous", "Gratin sec"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 3 },
    category: "accompagnement",
    baseIngredients: ["giraumon", "lardons", "oignon", "fromage"],
    ingredients: [
      { name: "giraumon", quantity: "700g" },
      { name: "lardons fumés", quantity: "150g" },
      { name: "oignon", quantity: "150g" },
      { name: "fromage rapé", quantity: "100g" },
      { name: "beurre", quantity: "25g" },
      { name: "sel, poivre, muscade", quantity: "à goûter" },
    ],
    steps: [
      "Éplucher giraumon, couper en cubes. Cuire à l'eau salée 20 min.",
      "Faire revenir lardons. Ajouter oignon haché, cuire 3 min.",
      "Égoutter giraumon. Verser dans plat beurré avec lardons.",
      "Couvrir fromage rapé.",
      "Enfourner 180C pendant 25 min jusqu'à gratin doré.",
    ],
    techniques: ["bake"],
    tags: ["gratin", "giraumon", "lardons"],
  },
  {
    id: "taboule-giraumon-grenade",
    name: "Taboulé giraumon grenade",
    desireName: "Salade taboulé sucré-salé, giraumon et grains grenade",
    aliases: ["taboulé antillais", "salade giraumon"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "entree",
    difficulty: 1,
    minChefLevel: 1,
    family: "salade",
    technique: "assemble",
    baseFamilies: ["giraumon", "grenade", "herbes"],
    fundamentals: ["giraumon rôtie", "grenade fraîche", "vinaigrette légère"],
    timings: { prep: 20, cook: 25, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Salade texturée, douceur giraumon vs acidité grenade",
    profTips: ["Giraumon rôtie", "Grenade juste avant service", "Vinaigrette légère"],
    mistakes: ["Giraumon trop cuite", "Grenade longtemps avant", "Sauce trop riche"],
    premiumTier: "classique",
    plaisir: { gourmandise: 3, texture: 4, visuel: 5, arome: 3 },
    category: "salade",
    baseIngredients: ["giraumon", "grenade", "herbes"],
    ingredients: [
      { name: "giraumon", quantity: "400g" },
      { name: "grenade", quantity: "1" },
      { name: "persil frais", quantity: "30g" },
      { name: "roquette", quantity: "100g" },
      { name: "huile olive", quantity: "3 cs" },
      { name: "vinaigre blanc", quantity: "1 cs" },
      { name: "miel", quantity: "1 cc" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Découper giraumon en cubes 2cm. Rôtir 200C 25 min.",
      "Laisser refroidir.",
      "Écosser grenade. Hacher persil.",
      "Mélanger huile, vinaigre, miel.",
      "Dresser roquette. Ajouter giraumon, grains, persil.",
      "Napper vinaigrette. Servir frais.",
    ],
    techniques: ["roast", "assemble"],
    tags: ["salade", "giraumon", "grenade"],
  },
  {
    id: "compoté-christophine-ananas",
    name: "Compotée christophine ananas",
    desireName: "Compotée sucrée-salée christophine-ananas",
    aliases: ["christophine ananas", "compotée antillaise"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "side",
    difficulty: 2,
    minChefLevel: 2,
    family: "accompagnement",
    technique: "braise",
    baseFamilies: ["christophine", "ananas", "épices"],
    fundamentals: ["christophine tendre", "ananas caramélisée", "cuisson lente"],
    timings: { prep: 20, cook: 90, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Compotée fondante, sucré-salé équilibré",
    profTips: ["Christophine très tendre", "Ananas caramélisée", "Cuisson très lente"],
    mistakes: ["Christophine dure", "Ananas brûlée", "Cuisson trop rapide"],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 4 },
    category: "accompagnement",
    baseIngredients: ["christophine", "ananas", "épices"],
    ingredients: [
      { name: "christophine", quantity: "800g" },
      { name: "ananas frais", quantity: "400g" },
      { name: "oignon", quantity: "150g" },
      { name: "ail", quantity: "3 gousses" },
      { name: "thym frais", quantity: "2 branches" },
      { name: "beurre", quantity: "25g" },
      { name: "sucre", quantity: "1 cs" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Éplucher christophine et ananas. Découper en cubes.",
      "Faire revenir oignon et ail dans beurre. Ajouter sucre.",
      "Ajouter christophine et ananas. Couvrir.",
      "Mijoter 90 min à feu très doux. Remuer souvent.",
      "Très tendre et caramélisée. Servir chaud ou tiède.",
    ],
    techniques: ["braise"],
    tags: ["accompagnement", "christophine", "ananas"],
  },
  {
    id: "pate-en-pot-poisson",
    name: "Pâté en pot de poisson",
    desireName: "Pâté terrine poisson créole, succulente",
    aliases: ["pâté poisson", "terrine poisson"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "entree",
    difficulty: 3,
    minChefLevel: 3,
    family: "terrine",
    technique: "bake_in_bath",
    baseFamilies: ["poisson", "foie", "herbes"],
    fundamentals: ["terrine poisson-foie", "bain-marie 2h", "repos 4h"],
    timings: { prep: 40, cook: 120, rest: 240 },
    servings: 6,
    portionAdaptation: "moderate",
    signature: "Terrine raffinée, texture crème lisse",
    profTips: ["Cuisson lente bain-marie", "Repos 4h minimum", "Démouler chaud"],
    mistakes: ["Cuisson rapide", "Repos insuffisant", "Démoulage trop tôt"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 5 },
    category: "entree",
    baseIngredients: ["poisson blanc", "foie", "œuf"],
    ingredients: [
      { name: "poisson blanc", quantity: "400g" },
      { name: "foie de volaille", quantity: "150g" },
      { name: "œufs", quantity: "2" },
      { name: "crème fraîche", quantity: "100ml" },
      { name: "ail", quantity: "2 gousses" },
      { name: "persil frais", quantity: "15g" },
      { name: "sel, poivre, muscade", quantity: "à goûter" },
      { name: "beurre", quantity: "15g" },
    ],
    steps: [
      "Chemiser terrine avec beurre.",
      "Hacher finement poisson, foie, ail, persil.",
      "Crémer beurre-eggs-cream. Ajouter poisson.",
      "Assaisonner généreusement.",
      "Verser dans terrine. Taper pour chasser bulles.",
      "Bain-marie 160C pendant 120 min.",
      "Refroidir. Réfrigérer 4h minimum. Démouler.",
    ],
    techniques: ["bake_in_bath"],
    tags: ["terrine", "poisson", "élégant"],
  },
  {
    id: "nuggets-poulet-madivial",
    name: "Nuggets poulet épicés",
    desireName: "Nuggets croustillants poulet, sauce épicée",
    aliases: ["nuggets poulet", "boulettes poulet"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "snack",
    difficulty: 1,
    minChefLevel: 1,
    family: "friture",
    technique: "fry",
    baseFamilies: ["poulet", "panure", "épices"],
    fundamentals: ["poulet mariné", "panure croustillante", "friture 170C"],
    timings: { prep: 15, cook: 15, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Nuggets croustillants, jus épicé",
    profTips: ["Marinade 15-30 min", "Panure double", "Friture 170C exact"],
    mistakes: ["Sans marinade", "Friture trop chaude", "Panure molle"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "snack",
    baseIngredients: ["poulet", "épices", "panure"],
    ingredients: [
      { name: "filé de poulet", quantity: "400g" },
      { name: "piment écrasé", quantity: "1/4 cc" },
      { name: "ail", quantity: "2 gousses" },
      { name: "huile", quantity: "1 cs" },
      { name: "citron vert", quantity: "1/2" },
      { name: "farine", quantity: "60g" },
      { name: "œuf", quantity: "1" },
      { name: "chapelure", quantity: "100g" },
      { name: "huile friture", quantity: "1L" },
      { name: "sel", quantity: "1 cc" },
    ],
    steps: [
      "Découper poulet en nuggets réguliers.",
      "Mariner 15-30 min épices-huile-citron.",
      "Battre œuf. Passer farine, œuf, chapelure.",
      "Chauffer huile 170C. Frire 3-4 min.",
      "Égoutter papier. Servir chaud.",
    ],
    techniques: ["fry"],
    tags: ["snack", "poulet", "friture"],
  },
  {
    id: "cake-chatrou",
    name: "Cake au chatrou",
    desireName: "Cake sucré-salé chatrou, tendre",
    aliases: ["cake chatrou", "gâteau poulpe"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "snack",
    difficulty: 2,
    minChefLevel: 2,
    family: "cake",
    technique: "bake",
    baseFamilies: ["farine", "œufs", "chatrou"],
    fundamentals: ["chatrou cuit tendre", "pâte levante", "cuisson 45 min"],
    timings: { prep: 45, cook: 45, rest: 10 },
    servings: 6,
    portionAdaptation: "moderate",
    signature: "Cake sucré-salé, surprises chatrou tendre",
    profTips: ["Chatrou très tendre", "Pâte riche dense", "Cuisson 160C lente"],
    mistakes: ["Chatrou dur", "Pâte légère", "Cuisson trop rapide"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "cake",
    baseIngredients: ["chatrou", "farine", "œufs"],
    ingredients: [
      { name: "chatrou cuit haché", quantity: "300g" },
      { name: "farine", quantity: "250g" },
      { name: "œufs", quantity: "3" },
      { name: "beurre mou", quantity: "100g" },
      { name: "sucre", quantity: "80g" },
      { name: "levure chimique", quantity: "1 sachet" },
      { name: "oignon haché", quantity: "100g" },
      { name: "ail", quantity: "2 gousses" },
      { name: "piment", quantity: "1/4" },
      { name: "sel", quantity: "1 cc" },
    ],
    steps: [
      "Cuire chatrou 40 min eau salée.",
      "Hacher finement.",
      "Crémer beurre-sucre. Ajouter œufs un par un.",
      "Incorporer farine-levure. Ajouter chatrou-oignon.",
      "Verser dans moule beurré.",
      "Enfourner 160C pendant 45 min.",
      "Démouler tiède.",
    ],
    techniques: ["bake"],
    tags: ["cake", "chatrou", "sucré"],
  },
  {
    id: "blanc-manger-pinacolada",
    name: "Blanc manger pinacolada",
    desireName: "Blanc manger crémeux coco-ananas tropical",
    aliases: ["blanc manger", "panna cotta tropicale"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dessert",
    difficulty: 2,
    minChefLevel: 2,
    family: "dessert",
    technique: "set",
    baseFamilies: ["crème", "coco", "ananas"],
    fundamentals: ["infusion coco-ananas", "gélatine 6g/100ml", "prise 4h"],
    timings: { prep: 15, cook: 0, rest: 240 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Blanc manger soyeux, saveur pinacolada",
    profTips: ["Gélatine 6g/100ml", "Lait coco riche", "Infusion ananas 20 min"],
    mistakes: ["Trop gélatine", "Pas gélatine", "Ananas broyée tôt"],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 4 },
    category: "dessert",
    baseIngredients: ["crème", "coco", "ananas", "gélatine"],
    ingredients: [
      { name: "lait coco entier", quantity: "400ml" },
      { name: "crème fraîche", quantity: "100ml" },
      { name: "ananas frais", quantity: "200g" },
      { name: "gélatine", quantity: "6g" },
      { name: "sucre", quantity: "40g" },
      { name: "vanille", quantity: "1/2 pod" },
      { name: "eau froide", quantity: "3 cs" },
    ],
    steps: [
      "Verser eau sur gélatine, laisser gonfler 5 min.",
      "Chauffer lait coco sans bouillir. Ajouter sucre, vanille.",
      "Ajouter gélatine gonflée hors feu.",
      "Ajouter ananas dés.",
      "Verser dans verrines.",
      "Réfrigérer 4h minimum.",
    ],
    techniques: ["set"],
    tags: ["dessert", "coco", "pinacolada"],
  },
  {
    id: "crepe-poulet-madivial",
    name: "Crêpe poulet légumes épicés",
    desireName: "Crêpe farcie poulet épicé-légumes rôtis",
    aliases: ["crêpe antillaise", "crêpe poulet"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "crepe",
    technique: "assemble",
    baseFamilies: ["crêpe", "poulet", "légumes"],
    fundamentals: ["crêpes souples", "poulet cuit épicé", "légumes rôtis"],
    timings: { prep: 30, cook: 30, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Crêpe farcie poulet-légumes, tropical",
    profTips: ["Crêpes fines", "Légumes rôtis", "Farce chaude modérée"],
    mistakes: ["Crêpe épaisse", "Légumes bouillis", "Remplissage trop généreux"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["crêpe", "poulet", "légumes"],
    ingredients: [
      { name: "farine", quantity: "150g" },
      { name: "œufs", quantity: "2" },
      { name: "lait", quantity: "300ml" },
      { name: "beurre fondu", quantity: "15g" },
      { name: "sel", quantity: "pincée" },
      { name: "poulet cuit", quantity: "250g" },
      { name: "poivron rouge", quantity: "1" },
      { name: "oignon", quantity: "1" },
      { name: "tomate", quantity: "1" },
      { name: "ail", quantity: "2 gousses" },
      { name: "épices antillaises", quantity: "1 cc" },
    ],
    steps: [
      "Mélanger farine-sel-œufs. Incorporer lait progressivement.",
      "Ajouter beurre. Reposer 30 min.",
      "Rôtir légumes 200C pendant 20 min.",
      "Mélanger poulet-légumes-ail-épices.",
      "Cuire crêpes 1-2 min par face.",
      "Farcir crêpes chaudes. Rouler.",
      "Servir immédiatement.",
    ],
    techniques: ["assemble"],
    tags: ["crêpe", "poulet", "légumes"],
  },
  {
    id: "curry-dinde-legumes-pays",
    name: "Curry dinde légumes tropicaux",
    desireName: "Curry épicé dinde-légumes, sauce coco",
    aliases: ["curry dinde", "curry créole"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "curry",
    technique: "braise",
    baseFamilies: ["dinde", "curry", "légumes"],
    fundamentals: ["dinde marinée 40 min", "épices curry toastées", "mijoté 45 min"],
    timings: { prep: 30, cook: 45, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Curry savoureux, sauce épicée généreuse",
    profTips: ["Marinade importante", "Épices toastées", "Légumes tendre-croquant"],
    mistakes: ["Sans marinade", "Épices brûlées", "Cuisson trop longue"],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["dinde", "curry", "légumes", "coco"],
    ingredients: [
      { name: "dinde en cubes", quantity: "600g" },
      { name: "épices curry", quantity: "2 cs" },
      { name: "ail", quantity: "4 gousses" },
      { name: "oignon", quantity: "200g" },
      { name: "giraumon", quantity: "300g" },
      { name: "christophine", quantity: "200g" },
      { name: "carotte", quantity: "200g" },
      { name: "lait coco", quantity: "200ml" },
      { name: "huile", quantity: "2 cs" },
      { name: "citron vert", quantity: "1" },
      { name: "thym", quantity: "2 branches" },
    ],
    steps: [
      "Mariner dinde 40 min épices-ail-huile.",
      "Découper légumes en cubes.",
      "Revenir oignon haché. Ajouter dinde marinée, saisir 5 min.",
      "Ajouter légumes, lait coco, thym. Couvrir.",
      "Mijoter 45 min.",
      "Finir jus citron vert. Servir avec riz.",
    ],
    techniques: ["braise"],
    tags: ["curry", "dinde", "épicé"],
  },
  {
    id: "salade-banane-saucisse",
    name: "Salade banane jaune saucisse",
    desireName: "Salade tiède banane-saucisse, vinaigrette moutarde",
    aliases: ["salade banane", "salade saucisse"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 1,
    minChefLevel: 1,
    family: "salade",
    technique: "assemble",
    baseFamilies: ["banane", "saucisse", "salade"],
    fundamentals: ["bananes rôties", "saucisse poêlée", "vinaigrette moutarde"],
    timings: { prep: 15, cook: 15, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Salade tiède sucré-salé, contraste excellent",
    profTips: ["Bananes rôties caramélisées", "Saucisse croustillante", "Vinaigrette tiède"],
    mistakes: ["Bananes pas assez cuites", "Saucisse trop longtemps", "Vinaigrette froide"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 3 },
    category: "salade",
    baseIngredients: ["banane", "saucisse", "salade"],
    ingredients: [
      { name: "bananes jaunes mûres", quantity: "250g" },
      { name: "saucisse fumée", quantity: "150g" },
      { name: "laitue verte", quantity: "100g" },
      { name: "roquette", quantity: "50g" },
      { name: "moutarde", quantity: "1 cc" },
      { name: "huile olive", quantity: "2 cs" },
      { name: "vinaigre blanc", quantity: "1 cs" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Rôtir bananes 200C pendant 10 min.",
      "Poêler saucisse tronçons 5 min croustillante.",
      "Mélanger moutarde-huile-vinaigre.",
      "Dresser salade verte en base. Ajouter bananes-saucisse.",
      "Napper vinaigrette tiède. Servir.",
    ],
    techniques: ["roast", "assemble"],
    tags: ["salade", "banane", "saucisse"],
  },
];

export default ANTILLAIS_LOT4;
