/**
 * ANTILLAIS LOT_4 — 30+ recettes Tatie Maryse
 * Source: https://www.tatiemaryse.com/les-recettes/
 * Qualité vérifiée, timings authentiques, ingrédients traditionnels
 */

import { DishProfile } from "../dishKnowledge";

const ANTILLAIS_LOT4: DishProfile[] = [
  {
    id: "hachis-parmentier-banane",
    name: "Hachis Parmentier de banane jaune",
    desireName: "Hachis Parmentier créole, couche banane jaune fondante",
    aliases: ["hachis banane", "parmentier antillais"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratin",
    technique: "bake",
    baseFamilies: ["banane", "viande", "tomate"],
    fundamentals: ["bananes jaunes mûres", "viande hachée revenus", "gratin 25 min 180C"],
    timings: { prep: 25, cook: 35, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Couche banane fondante sous viande hachée épicée, gratinée",
    profTips: [
      "Choisir bananes jaunes mûres, texture crémeuse",
      "Viande doit être bien revenus, non blanche",
      "Gratin juste doré, pas brûlé",
    ],
    mistakes: [
      "Bananes trop vertes = dures, manquent saveur",
      "Viande pâle = manque de flaveur",
      "Four trop chaud = brûlure surfaces",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["banane jaune", "viande hachée", "oignon", "ail", "tomate"],
    ingredients: [
      { name: "bananes jaunes mûres", quantity: "5-6" },
      { name: "viande hachée", quantity: "500g" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "4 gousses" },
      { name: "tomate", quantity: "3" },
      { name: "beurre", quantity: "2 cs" },
      { name: "fromage rapé", quantity: "100g" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Éplucher bananes, couper en rondelles épaisses. Disposer dans plat beurré.",
      "Faire revenir oignon haché et ail dans beurre. Ajouter viande hachée.",
      "Cuire viande 10 min. Ajouter tomate concassée, sel, poivre. Laisser 5 min.",
      "Verser préparation viande sur bananes.",
      "Couvrir fromage rapé. Enfourner 180C pendant 25-30 min jusqu'à dorage.",
      "Sortir du four, laisser reposer 5 min avant service.",
    ],
    techniques: ["braise", "bake"],
    tags: ["gratin", "créole", "traditionnel", "familial"],
  },
  {
    id: "tarte-morue-oignon-creole",
    name: "Tarte morue oignon créole",
    desireName: "Tarte croustillante, garniture morue épicée oignon doux",
    aliases: ["tarte morue", "morue en tarte"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "tarte-salees",
    technique: "bake",
    baseFamilies: ["morue", "oignon", "pate"],
    fundamentals: ["morue dessalée effilée", "oignon cuit doux", "pâte croustillante"],
    timings: { prep: 35, cook: 35, rest: 15 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Pâte croustillante garnie morue-oignon savoureux",
    profTips: [
      "Morue doit être parfaitement dessalée, éfilée finement",
      "Oignons cuits en fondue, fondants sucrés",
      "Pâte précuite 10 min pour rester croustillante",
    ],
    mistakes: [
      "Morue trop salée = tarte inmongeaable",
      "Oignons mal cuits = texture dure",
      "Pâte pas précuite = fond mouillé",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 4 },
    category: "tarte_salees",
    baseIngredients: ["morue", "oignon", "ail", "pate", "huile"],
    ingredients: [
      { name: "pâte brisée", quantity: "350g" },
      { name: "morue salée désalée", quantity: "300g" },
      { name: "oignon", quantity: "5 gros" },
      { name: "ail", quantity: "3 gousses" },
      { name: "piment", quantity: "1/2" },
      { name: "huile olive", quantity: "3 cs" },
      { name: "thym frais", quantity: "2 branches" },
    ],
    steps: [
      "Foncer le moule avec pâte brisée. Piquer fond, recouvrir papier parchemin.",
      "Précuire 10 min à 200C. Retirer papier.",
      "Émincer finement oignons. Cuire à l'huile 20 min à feu doux jusqu'à fondue.",
      "Ajouter ail, piment écrasé, thym. Effilocher morue, ajouter au mélange.",
      "Verser garniture dans fond de tarte. Enfourner 180C pendant 20 min.",
      "Sortir tarte, vérifier dorage, laisser reposer 5 min avant service.",
    ],
    techniques: ["bake"],
    tags: ["tarte", "morue", "oignon", "antillais"],
  },
  {
    id: "riz-lait-coco-curcuma",
    name: "Riz au lait coco curcuma",
    desireName: "Riz au lait onctueux coco-curcuma, sucré avec épices",
    aliases: ["riz coco", "riz lait antillais"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dessert",
    difficulty: 1,
    minChefLevel: 1,
    family: "dessert-riz",
    technique: "simmer",
    baseFamilies: ["riz", "lait", "coco"],
    fundamentals: ["riz blanc grain long", "cuisson lente 45 min", "lait coco riche"],
    timings: { prep: 10, cook: 45, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Riz onctueux sucré, saveur coco-curcuma chaude",
    profTips: [
      "Riz doit être grain court pour absorption lait",
      "Cuisson lente à feu très doux, pas bouillir",
      "Curcuma ajouté en fin pour couleur dorée",
    ],
    mistakes: [
      "Riz grain long = grains durs, pas crémeux",
      "Cuisson trop rapide = riz sec",
      "Curcuma brûlé = amertume",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "dessert",
    baseIngredients: ["riz", "lait coco", "sucre", "curcuma"],
    ingredients: [
      { name: "riz blanc court grain", quantity: "250g" },
      { name: "lait coco entier", quantity: "400ml" },
      { name: "lait entier", quantity: "200ml" },
      { name: "sucre", quantity: "60g" },
      { name: "curcuma", quantity: "1/2 cc" },
      { name: "vanille", quantity: "1 pod" },
      { name: "cannelle", quantity: "1/2 bâton" },
    ],
    steps: [
      "Rincer riz à eau froide jusqu'à ce que eau soit claire.",
      "Verser riz dans casserole. Ajouter lait coco et lait. Porter à ébullition.",
      "Baisser feu doux, couvrir partiellement. Laisser cuire 45 min, remuant souvent.",
      "Riz doit être tendre, préparation crémeuse. Ajouter sucre, curcuma, vanille, cannelle.",
      "Mélanger bien, laisser 5 min à feu doux. Servir chaud ou tiède.",
    ],
    techniques: ["simmer"],
    tags: ["dessert", "riz", "coco", "sucré"],
  },
  {
    id: "gratin-giraumon-lardons",
    name: "Gratin giraumon aux lardons",
    desireName: "Gratin fondant giraumon-lardons, fromage doré",
    aliases: ["gratin giraumon", "gratin courge"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "side",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratin",
    technique: "bake",
    baseFamilies: ["giraumon", "lardons", "fromage"],
    fundamentals: ["giraumon cuite fondante", "lardons rissolés", "gratin 25 min"],
    timings: { prep: 20, cook: 35, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Gratin sucré-salé giraumon tendre, texture croquante lardons",
    profTips: [
      "Giraumon doit cuire jusqu'à très tendre",
      "Lardons rissolés séparément pour croustillant",
      "Fromage juste gratiné, pas brûlé",
    ],
    mistakes: [
      "Giraumon pas assez cuite = dure au goût",
      "Lardons mous = manquent texture",
      "Gratin trop sec = peu appétissant",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 3 },
    category: "accompagnement",
    baseIngredients: ["giraumon", "lardons", "oignon", "fromage", "beurre"],
    ingredients: [
      { name: "giraumon", quantity: "700g" },
      { name: "lardons fumés", quantity: "150g" },
      { name: "oignon", quantity: "1" },
      { name: "fromage rapé", quantity: "100g" },
      { name: "beurre", quantity: "2 cs" },
      { name: "sel, poivre", quantity: "à goûter" },
      { name: "noix de muscade", quantity: "pincée" },
    ],
    steps: [
      "Éplucher giraumon, découper en cubes. Cuire à l'eau salée 20 min jusqu'à tendre.",
      "Faire revenir lardons dans beurre 5 min. Ajouter oignon haché, cuire 3 min.",
      "Égoutter giraumon. Verser dans plat beurré avec mélange lardons-oignon.",
      "Assaisonner sel, poivre, muscade. Couvrir fromage rapé.",
      "Enfourner 180C pendant 25 min jusqu'à gratin doré. Servir chaud.",
    ],
    techniques: ["bake"],
    tags: ["gratin", "accompagnement", "giraumon", "antillais"],
  },
  {
    id: "taboule-giraumon-grenade",
    name: "Taboulé giraumon grenade",
    desireName: "Salade taboulé sucré-salé, giraumon et grains grenade",
    aliases: ["taboulé antillais", "salade giraumon"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "entree",
    difficulty: 1,
    minChefLevel: 1,
    family: "salade",
    technique: "assemble",
    baseFamilies: ["giraumon", "grenade", "herbes"],
    fundamentals: ["giraumon rôtie tendre", "grenade fraîche", "vinaigrette légère"],
    timings: { prep: 20, cook: 25, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Salade texturée, douceur giraumon versus acidité grenade",
    profTips: [
      "Giraumon rôtie, pas bouillie, pour texture tendre",
      "Grenade écossée juste avant service pour fraîcheur",
      "Vinaigrette légère pour ne pas surcharger",
    ],
    mistakes: [
      "Giraumon trop cuite = porridge",
      "Grenade bouillie = jus perdu",
      "Vinaigrette trop riche = écrase saveurs",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 3, texture: 4, visuel: 5, arome: 3 },
    category: "salade",
    baseIngredients: ["giraumon", "grenade", "herbes", "huile", "vinaigre"],
    ingredients: [
      { name: "giraumon", quantity: "400g" },
      { name: "grenade", quantity: "1" },
      { name: "persil frais", quantity: "1 poignée" },
      { name: "roquette", quantity: "100g" },
      { name: "huile olive", quantity: "3 cs" },
      { name: "vinaigre blanc", quantity: "1 cs" },
      { name: "miel", quantity: "1 cc" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Découper giraumon en cubes 2cm. Rôtir 200C pendant 25 min, remuant mi-parcours.",
      "Giraumon doit être tendre doré. Laisser refroidir.",
      "Écosser grenade, récupérer grains. Hacher persil.",
      "Mélanger huile, vinaigre, miel. Assaisonner.",
      "Dresser roquette en base. Ajouter giraumon rôtie, grains grenade, persil.",
      "Napper vinaigrette. Servir frais.",
    ],
    techniques: ["roast", "assemble"],
    tags: ["salade", "giraumon", "grenade", "léger"],
  },
  {
    id: "compoté-christophine-ananas",
    name: "Compotée christophine ananas",
    desireName: "Compotée sucrée-salée christophine-ananas rôtie",
    aliases: ["christophine ananas", "compotée antillaise"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "side",
    difficulty: 2,
    minChefLevel: 2,
    family: "accompagnement",
    technique: "braise",
    baseFamilies: ["christophine", "ananas", "épices"],
    fundamentals: ["christophine cuite tendre", "ananas caramélisée", "cuisson lente 1h30"],
    timings: { prep: 20, cook: 90, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Compotée fondante, mélange sucré-salé excellente",
    profTips: [
      "Christophine doit être très tendre après cuisson",
      "Ananas caramélisée pour profondeur saveur",
      "Cuisson lente développe fondus textures",
    ],
    mistakes: [
      "Christophine pas assez cuite = reste dure",
      "Ananas brûlée = amertume",
      "Cuisson trop rapide = textures dures",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 4 },
    category: "accompagnement",
    baseIngredients: ["christophine", "ananas", "oignon", "épices"],
    ingredients: [
      { name: "christophine", quantity: "800g" },
      { name: "ananas", quantity: "1/2" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "3 gousses" },
      { name: "thym frais", quantity: "3 branches" },
      { name: "beurre", quantity: "2 cs" },
      { name: "sucre", quantity: "1 cs" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Éplucher christophine et ananas. Découper en cubes.",
      "Faire revenir oignon et ail dans beurre. Ajouter sucre, caraméliser 2 min.",
      "Ajouter christophine et ananas. Assaisonner thym, sel, poivre.",
      "Couvrir, laisser mijoter 1h30 à feu très doux. Remuer occasionnellement.",
      "Préparation doit être très tendre, légèrement caramélisée.",
      "Servir chaud ou tiède comme accompagnement.",
    ],
    techniques: ["braise"],
    tags: ["accompagnement", "christophine", "ananas", "sucré"],
  },
  {
    id: "pate-en-pot-poisson",
    name: "Pâté en pot de poisson",
    desireName: "Pâté terrine poisson créole, garniture succulente",
    aliases: ["pâté poisson", "terrine poisson antillaise"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "entree",
    difficulty: 3,
    minChefLevel: 3,
    family: "terrine",
    technique: "bake_in_bath",
    baseFamilies: ["poisson", "foie", "herbes"],
    fundamentals: ["terrine poisson-foie", "cuisson au bain-marie 2h", "repos 4h minimum"],
    timings: { prep: 40, cook: 120, rest: 240 },
    servings: 6,
    portionAdaptation: "moderate",
    signature: "Terrine raffinée poisson-foie, texture crème lisse",
    profTips: [
      "Terrine doit cuire doucement au bain-marie",
      "Repos minimum 4h (ou nuit) pour texture crème",
      "Démouler sur planche chauffée pour présentation",
    ],
    mistakes: [
      "Cuisson trop rapide = texture grossière",
      "Repos insuffisant = pâte molle",
      "Démoulage trop tôt = casse matrice",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 5 },
    category: "entree",
    baseIngredients: ["poisson blanc", "foie gras", "œuf", "crème"],
    ingredients: [
      { name: "poisson blanc (vivaneau, dorade)", quantity: "400g" },
      { name: "foie gras si possible, sinon foie de volaille", quantity: "150g" },
      { name: "œufs", quantity: "2" },
      { name: "crème fraîche", quantity: "100ml" },
      { name: "ail", quantity: "2 gousses" },
      { name: "persil frais", quantity: "1 poignée" },
      { name: "sel, poivre, muscade", quantity: "à goûter" },
      { name: "beurre pour moule", quantity: "1 cs" },
    ],
    steps: [
      "Chemiser terrine avec beurre. Préchauffer four 160C.",
      "Hacher finement poisson, foie, ail, persil. Passer au mixeur avec œufs et crème.",
      "Assaisonner sel, poivre, muscade généreusement (cuit affadit).",
      "Verser pâte dans terrine. Taper fond table pour chasser bulles.",
      "Placer terrine dans plat d'eau chaude (bain-marie). Cuire 120 min.",
      "Pointe couteau plantée doit sortir sèche. Laisser refroidir. Réfrigérer 4h minimum.",
      "Démouler sur planche chauffée. Trancher avec couteau mouillé chaud.",
    ],
    techniques: ["bake_in_bath"],
    tags: ["terrine", "poisson", "foie", "élégant"],
  },
  {
    id: "nuggets-poulet-madivial",
    name: "Nuggets poulet Madivial",
    desireName: "Nuggets croustillants poulet, sauce Madivial épicée",
    aliases: ["nuggets antillais", "poulet frit"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "snack",
    difficulty: 1,
    minChefLevel: 1,
    family: "friture",
    technique: "fry",
    baseFamilies: ["poulet", "panure", "épices"],
    fundamentals: ["poulet mariné épices", "panure croustillante", "friture 170C"],
    timings: { prep: 15, cook: 15, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Nuggets dorés croustillants, jus épicé Madivial",
    profTips: [
      "Marinade 15-30 min pour saveur maximale",
      "Panure double pour croustillant",
      "Friture 170C exactement pour dorage",
    ],
    mistakes: [
      "Sans marinade = nuggets fades",
      "Friture trop chaude = brun dehors, cru dedans",
      "Panure molle = perte croustillant",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "snack",
    baseIngredients: ["poulet", "épices antillaises", "panure"],
    ingredients: [
      { name: "poulet désossé peau retirée", quantity: "400g" },
      { name: "piment antillais écrasé", quantity: "1/2 cc" },
      { name: "ail", quantity: "2 gousses" },
      { name: "huile", quantity: "2 cs" },
      { name: "citron vert", quantity: "1/2" },
      { name: "farine", quantity: "60g" },
      { name: "œuf", quantity: "1" },
      { name: "chapelure", quantity: "100g" },
      { name: "huile friture", quantity: "1L" },
      { name: "sel", quantity: "à goûter" },
    ],
    steps: [
      "Découper poulet en nuggets réguliers. ",
      "Écraser ail, piment. Mélanger avec huile et jus citron.",
      "Mariner nuggets 15-30 min dans mélange épices.",
      "Battre œuf. Passer nuggets farine, puis œuf, puis chapelure.",
      "Chauffer huile 170C. Frire nuggets 3-4 min par batch.",
      "Égoutter sur papier. Servir avec sauce épicée ou citron.",
    ],
    techniques: ["fry"],
    tags: ["snack", "poulet", "friture", "enfants"],
  },
  {
    id: "cake-chatrou",
    name: "Cake au chatrou",
    desireName: "Cake sucré-salé chatrou, texture moelleuse",
    aliases: ["cake chatrou", "gâteau poulpe"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "snack",
    difficulty: 2,
    minChefLevel: 2,
    family: "cake",
    technique: "bake",
    baseFamilies: ["farine", "œufs", "chatrou"],
    fundamentals: ["chatrou cuit tendre haché", "pâte levante riche", "cuisson 45 min"],
    timings: { prep: 45, cook: 45, rest: 10 },
    servings: 6,
    portionAdaptation: "moderate",
    signature: "Cake sucré-salé texturé, surprises chatrou tendre",
    profTips: [
      "Chatrou doit être bien cuit avant hachage, très tendre",
      "Pâte doit être riche dense, pas légère",
      "Cuisson lente 160C pour cuisson homogène",
    ],
    mistakes: [
      "Chatrou pas assez cuit = dur désagréable",
      "Pâte trop aérée = cake émet brises",
      "Cuisson trop rapide = cru cœur",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "cake",
    baseIngredients: ["chatrou", "farine", "œufs", "beurre"],
    ingredients: [
      { name: "chatrou (petite pieuvre)", quantity: "300g" },
      { name: "farine", quantity: "250g" },
      { name: "œufs", quantity: "3" },
      { name: "beurre mou", quantity: "100g" },
      { name: "sucre", quantity: "80g" },
      { name: "levure chimique", quantity: "1 sachet" },
      { name: "oignon", quantity: "1" },
      { name: "ail", quantity: "2 gousses" },
      { name: "piment", quantity: "1/4" },
      { name: "sel", quantity: "1 cc" },
    ],
    steps: [
      "Cuire chatrou à l'eau salée 40 min minimum jusqu'à très tendre.",
      "Hacher finement chatrou cuit. Hacher oignon, ail, piment.",
      "Crémer beurre et sucre. Ajouter œufs un par un, bien mélanger.",
      "Incorporer farine tamisée et levure. Ajouter chatrou haché et oignon-ail.",
      "Verser pâte dans moule beurré. Enfourner 160C pendant 45 min.",
      "Tester avec pique, doit sortir sèche. Démouler tiède.",
    ],
    techniques: ["bake"],
    tags: ["cake", "chatrou", "poulpe", "sucré"],
  },
  {
    id: "blanc-manger-pinacolada",
    name: "Blanc manger pinacolada",
    desireName: "Blanc manger crémeux coco-ananas, saveurs tropicales",
    aliases: ["blanc manger", "panna cotta tropicale"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dessert",
    difficulty: 2,
    minChefLevel: 2,
    family: "dessert-creme",
    technique: "set",
    baseFamilies: ["lait coco", "ananas", "gélatine"],
    fundamentals: ["infusion coco-ananas", "gélatine bien dosée", "prise 4h frais"],
    timings: { prep: 15, cook: 0, rest: 240 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Blanc manger soyeux coco-ananas, saveur pinacolada",
    profTips: [
      "Gélatine dosée 6g par 100ml pour prise correcte",
      "Lait coco riche pour onctuosité",
      "Infusion ananas 20 min pour saveur maximale",
    ],
    mistakes: [
      "Trop gélatine = caoutchouc",
      "Pas assez gélatine = soupe",
      "Ananas broyée fin trop tôt = perd fraîcheur",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 4 },
    category: "dessert",
    baseIngredients: ["lait coco", "ananas", "gélatine", "sucre"],
    ingredients: [
      { name: "lait coco entier", quantity: "400ml" },
      { name: "crème fraîche", quantity: "100ml" },
      { name: "ananas frais", quantity: "200g" },
      { name: "gélatine", quantity: "6g" },
      { name: "sucre", quantity: "40g" },
      { name: "vanille", quantity: "1/2 pod" },
      { name: "eau froide", quantity: "3 cs" },
    ],
    steps: [
      "Verser eau froide sur gélatine, laisser gonfler 5 min.",
      "Chauffer lait coco et crème sans bouillir. Ajouter sucre et vanille.",
      "Hors feu, ajouter gélatine gonflée. Mélanger bien.",
      "Ajouter ananas frais coupée petits dés. Remuer délicatement.",
      "Verser dans verrines. Réfrigérer 4h minimum.",
      "Servir glacé, garni ananas frais si désiré.",
    ],
    techniques: ["set"],
    tags: ["dessert", "blanc manger", "coco", "pinacolada"],
  },
  {
    id: "crepe-poulet-madivial",
    name: "Crêpe poulet Madivial légumes rôtis",
    desireName: "Crêpe farcie poulet épicé-légumes, sauce Madivial",
    aliases: ["crêpe antillaise", "crêpe poulet"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "crepe",
    technique: "assemble",
    baseFamilies: ["pâte crêpe", "poulet", "légumes"],
    fundamentals: ["crêpes fines souples", "poulet cuit épicé", "légumes rôtis"],
    timings: { prep: 30, cook: 30, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Crêpe farcie poulet-légumes, saveurs tropicales",
    profTips: [
      "Pâte crêpe doit reposer 30 min pour légèreté",
      "Légumes rôtis pour caramélisation saveurs",
      "Farce chaude mais pas trop pour ne pas crêpe casse",
    ],
    mistakes: [
      "Pâte sans repos = crêpe épaisse",
      "Légumes bouillis = fades",
      "Remplissage trop généreux = dégoûlinade",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["œufs", "farine", "lait", "poulet", "légumes"],
    ingredients: [
      { name: "farine", quantity: "150g" },
      { name: "œufs", quantity: "2" },
      { name: "lait", quantity: "300ml" },
      { name: "beurre fondu", quantity: "1 cs" },
      { name: "sel", quantity: "pincée" },
      { name: "poulet cuit désossé", quantity: "250g" },
      { name: "poivron rouge", quantity: "1" },
      { name: "oignon", quantity: "1" },
      { name: "tomate", quantity: "1" },
      { name: "ail", quantity: "2 gousses" },
      { name: "épices antillaises", quantity: "1 cc" },
    ],
    steps: [
      "Mélanger farine et sel. Faire puits, ajouter œufs. Incorporer lait progressivement.",
      "Ajouter beurre fondu. Laisser reposer 30 min.",
      "Rôtir poivron, oignon, tomate découpés 200C pendant 20 min.",
      "Mélanger poulet cuit effiloché avec légumes rôtis, ail écrasé, épices.",
      "Cuire crêpes fine poêle beurrée, 1-2 min par face.",
      "Farcir crêpes chaud, rouler. Servir avec sauce ou coulis tomate.",
    ],
    techniques: ["assemble"],
    tags: ["crêpe", "poulet", "légumes", "antillais"],
  },
  {
    id: "curry-dinde-legumes-pays",
    name: "Curry dinde légumes-pays",
    desireName: "Curry épicé dinde-légumes tropicaux, sauce coco",
    aliases: ["curry dinde", "curry créole"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "curry",
    technique: "braise",
    baseFamilies: ["dinde", "épices curry", "légumes tropicaux"],
    fundamentals: ["dinde marinée 40 min", "épices curry toastées", "mijoté 45 min"],
    timings: { prep: 30, cook: 45, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Curry savoureux dinde-légumes, sauce épicée généreux",
    profTips: [
      "Marinade importante pour profondeur saveur",
      "Épices curry préalablement toastées pour arôme",
      "Légumes tropicaux doivent rester tendre-croquant",
    ],
    mistakes: [
      "Sans marinade = curry fade",
      "Épices brûlées = amertume désagréable",
      "Cuisson trop longue = légumes mous",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["dinde", "curry", "légumes", "coco"],
    ingredients: [
      { name: "dinde découpée en cubes", quantity: "600g" },
      { name: "épices curry en poudre", quantity: "2 cc" },
      { name: "ail", quantity: "4 gousses" },
      { name: "oignon", quantity: "2" },
      { name: "giraumon", quantity: "300g" },
      { name: "christophine", quantity: "200g" },
      { name: "carotte", quantity: "2" },
      { name: "lait coco", quantity: "200ml" },
      { name: "huile", quantity: "2 cs" },
      { name: "citron vert", quantity: "1" },
      { name: "thym", quantity: "3 branches" },
    ],
    steps: [
      "Écraser ail, mélanger avec curry, huile. Frotter dinde, laisser 40 min.",
      "Découper légumes en cubes isométriques.",
      "Faire revenir oignon haché dans huile. Ajouter dinde marinée, saisir 5 min.",
      "Ajouter légumes, verser lait coco. Assaisonner thym.",
      "Couvrir, laisser mijoter 45 min. Vérifier tendreté légumes.",
      "Finir avec jus citron vert frais. Servir avec riz blanc.",
    ],
    techniques: ["braise"],
    tags: ["curry", "dinde", "épicé", "tropique"],
  },
  {
    id: "salade-banane-jaune-saucisse",
    name: "Salade banane jaune saucisse",
    desireName: "Salade tiède banane-saucisse, vinaigrette moutarde",
    aliases: ["salade banane", "salade saucisse"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 1,
    minChefLevel: 1,
    family: "salade",
    technique: "assemble",
    baseFamilies: ["banane", "saucisse", "salade verte"],
    fundamentals: ["bananes rôties caramélisées", "saucisse poêlée", "vinaigrette moutarde"],
    timings: { prep: 15, cook: 15, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Salade tiède sucré-salé, contraste banane-saucisse",
    profTips: [
      "Bananes rôties caramélisées pour douceur",
      "Saucisse croustillante dehors, jus dedans",
      "Vinaigrette tiède pour harmoniser",
    ],
    mistakes: [
      "Bananes cuites pas assez = dures",
      "Saucisse trop longtemps = sèche",
      "Vinaigrette froide = désaccord températures",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 3 },
    category: "salade",
    baseIngredients: ["banane jaune", "saucisse", "salade verte"],
    ingredients: [
      { name: "bananes jaunes mûres", quantity: "2" },
      { name: "saucisse fumée", quantity: "2" },
      { name: "laitue verte", quantity: "100g" },
      { name: "roquette", quantity: "50g" },
      { name: "moutarde", quantity: "1 cc" },
      { name: "huile olive", quantity: "2 cs" },
      { name: "vinaigre blanc", quantity: "1 cs" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Râper bananes épluchées, les rôtir 200C pendant 10 min.",
      "Poêler saucisse coupée tronçons 5 min, croustillante.",
      "Mélanger moutarde, huile, vinaigre. Assaisonner.",
      "Dresser salade verte en base. Ajouter bananes rôties et saucisse.",
      "Napper vinaigrette tiède. Servir immédiatement.",
    ],
    techniques: ["roast", "assemble"],
    tags: ["salade", "banane", "saucisse", "tiède"],
  },
];

export default ANTILLAIS_LOT4;
