/**
 * PLATS ANTILLAIS — Base qualitative vérifiée
 * Chaque plat est réel, avec ingrédients cohérents et étapes crédibles.
 * Organisé par lots validés.
 */

import { DishProfile } from "../dishKnowledge";

// ============================================
// LOT 1 — 7 plats existants (vérifiés phase 2-4)
// ============================================
const LOT_1: DishProfile[] = [
  {
    id: "bokit-classique",
    name: "Bokit traditionnel",
    desireName: "Bokit doré croustillant, garni poulet épicé",
    aliases: ["bokit", "bokits"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "snack",
    difficulty: 2,
    minChefLevel: 2,
    family: "friture",
    technique: "fry",
    baseFamilies: ["farine", "levure"],
    fundamentals: ["pate levee legere", "friture exact 165C", "repos essentiellement"],
    timings: { prep: 15, cook: 20, rest: 30 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Poche gonflée dorée avec intérieur moelleux, garnie après",
    profTips: [
      "Mesurer huile a 165C exactement pour texture croustillante",
      "Laisser reposer la pate 30+ minutes pour que la poche gonfle",
      "Garnir APRES friture quand bokit est encore chaud",
    ],
    mistakes: [
      "Huile trop chaude = bokit compact et sec intérieur",
      "Pas de repos = poche mal gonflée",
      "Garnir AVANT = garniture degouline",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 5, visuel: 3, arome: 4 },
    category: "street_food",
    baseIngredients: ["farine", "levure boulangere", "eau", "sel", "huile de friture"],
    ingredients: [
      { name: "farine", quantity: "250g" },
      { name: "levure boulangere", quantity: "7g" },
      { name: "eau tiede", quantity: "150ml" },
      { name: "sel", quantity: "1 cc" },
      { name: "huile de friture", quantity: "1L" },
    ],
    steps: [
      "Melanger farine, sel et levure. Ajouter eau tiede progressivement.",
      "Petrir 5 min jusqu'a pate souple et homogene.",
      "Couvrir et laisser reposer 30 min minimum a temperature ambiante.",
      "Diviser en boules de 80g, etaler en disques de 15cm.",
      "Chauffer huile a 165C exactement (thermometre obligatoire).",
      "Frire chaque disque 2-3 min par face, il doit gonfler en poche.",
      "Egoutter sur papier absorbant, ouvrir et garnir immediatement.",
    ],
    techniques: ["fry", "knead"],
    tags: ["street-food", "guadeloupe", "friture", "rapide"],
  },
  {
    id: "colombo-poulet",
    name: "Colombo de poulet",
    desireName: "Colombo de poulet fondant aux épices créoles",
    aliases: ["colombo", "colombo poulet", "colombo de poulet antillais"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "curry-arom",
    technique: "braise",
    baseFamilies: ["poulet", "oignon", "ail", "tomate", "epices"],
    fundamentals: ["marinade 30min avant", "epices colombo toastees", "mijotage 45min min"],
    timings: { prep: 20, cook: 50, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Poulet tendre dans sauce riche epices colombo, légumes fondants",
    profTips: [
      "Toaster les epices colombo 2 min avant pour reveler aromes",
      "Laisser poulet mariner minimum 30 min avec epices, ail, citron",
      "Mijoter basse temperature pour viande tendre, pas coriace",
    ],
    mistakes: [
      "Pas toaster epices = gout plat",
      "Cuisson trop rapide = poulet sec",
      "Trop eau = sauce diluee, pas onctueuse",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 5 },
    category: "plat",
    baseIngredients: ["poulet", "poudre colombo", "oignon", "ail", "tomate", "citron vert", "thym", "aubergine", "pomme de terre"],
    ingredients: [
      { name: "cuisses de poulet", quantity: "800g" },
      { name: "poudre de colombo", quantity: "2 cs" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "4 gousses" },
      { name: "tomate", quantity: "3" },
      { name: "citron vert", quantity: "1" },
      { name: "thym frais", quantity: "3 branches" },
      { name: "aubergine", quantity: "1" },
      { name: "pomme de terre", quantity: "2" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Decouper poulet en morceaux, frotter avec colombo, ail ecrase, jus de citron vert.",
      "Laisser mariner 30 min minimum au frais.",
      "Faire revenir oignon emince 5 min dans huile chaude.",
      "Ajouter le poulet marine, saisir 5 min sur chaque face.",
      "Ajouter tomate concassee, aubergine et pomme de terre en cubes.",
      "Mouiller a hauteur, ajouter thym. Couvrir et mijoter 45 min a feu doux.",
      "Rectifier assaisonnement, servir avec riz blanc.",
    ],
    techniques: ["braise", "sear", "marinate"],
    tags: ["mijoté", "guadeloupe", "épicé", "familial"],
  },
  {
    id: "blaff-poisson",
    name: "Blaff de poisson",
    desireName: "Blaff de poisson frais, bouillon citronné parfumé",
    aliases: ["blaff", "blaff poisson"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dinner",
    difficulty: 3,
    minChefLevel: 3,
    family: "poisson-bouillon",
    technique: "poach",
    baseFamilies: ["poisson-blanc", "citron", "oignon", "tomate"],
    fundamentals: ["bouillon aromatique fort", "pochage doux 6-8 min", "jus citron apres"],
    timings: { prep: 15, cook: 40, rest: 0 },
    servings: 2,
    portionAdaptation: "moderate",
    signature: "Poisson blanc juste poché dans bouillon tomate-citron, jus vivace",
    profTips: [
      "Construire bouillon aromatique fort avant d'ajouter poisson",
      "Poisson ne doit jamais bouillir = eau juste fremissante",
      "Finition citron frais pour acidite, pas avant cuisson",
    ],
    mistakes: [
      "Bouillon pas assez aromatise = plat sans saveur",
      "Poisson bouillie = chair cassante, seche",
      "Ajouter citron trop tot = perte acidite",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 3, visuel: 4, arome: 5 },
    category: "poisson",
    baseIngredients: ["poisson blanc", "citron vert", "oignon", "ail", "piment", "thym", "bois d'inde", "cive"],
    ingredients: [
      { name: "filets de poisson blanc (vivaneau, dorade)", quantity: "400g" },
      { name: "citron vert", quantity: "2" },
      { name: "oignon", quantity: "1" },
      { name: "ail", quantity: "3 gousses" },
      { name: "piment antillais", quantity: "1" },
      { name: "thym frais", quantity: "3 branches" },
      { name: "bois d'inde", quantity: "2 feuilles", optional: true },
      { name: "cive (oignon vert)", quantity: "4 tiges" },
      { name: "eau", quantity: "500ml" },
    ],
    steps: [
      "Porter eau a ebullition avec oignon emince, ail, thym, bois d'inde et piment entier.",
      "Laisser infuser 15 min pour construire le bouillon aromatique.",
      "Baisser a fremissement doux (jamais bouillir avec le poisson).",
      "Deposer les filets de poisson dans le bouillon, pocher 6-8 min.",
      "Retirer poisson delicatement. Ajouter cive ciselée et jus de citron vert.",
      "Servir poisson nappe de bouillon, avec riz blanc ou pain.",
    ],
    techniques: ["poach"],
    tags: ["poisson", "guadeloupe", "léger", "bouillon"],
  },
  {
    id: "accras-morue",
    name: "Accras de morue",
    desireName: "Accras dorés croustillants, coeur moelleux à la morue",
    aliases: ["accras", "acras", "accras morue"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "snack",
    difficulty: 2,
    minChefLevel: 2,
    family: "friture",
    technique: "fry",
    baseFamilies: ["morue", "farine", "levure"],
    fundamentals: ["morue dessalee bien drainee", "pate legere", "friture 170C"],
    timings: { prep: 20, cook: 15, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Boules dorées croustillantes morue, dedans tendre",
    profTips: [
      "Bien essorer morue apres dessalage = aucune eau surplus",
      "Pate doit etre legere, ailee, pas compacte",
      "Friture 170C exactement pour dorage maitrise",
    ],
    mistakes: [
      "Morue pas bien essores = accras gras",
      "Pate trop epaisse = cuit pas au coeur",
      "Huile trop chaude = brule dehors, cru dedans",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 4 },
    category: "street_food",
    baseIngredients: ["morue", "farine", "levure chimique", "oignon", "ail", "persil", "piment", "cive"],
    ingredients: [
      { name: "morue dessalee", quantity: "200g" },
      { name: "farine", quantity: "150g" },
      { name: "levure chimique", quantity: "1 cc" },
      { name: "oignon", quantity: "1 petit" },
      { name: "ail", quantity: "2 gousses" },
      { name: "persil frais", quantity: "1 bouquet" },
      { name: "piment antillais", quantity: "1/2" },
      { name: "cive", quantity: "3 tiges" },
      { name: "huile de friture", quantity: "1L" },
    ],
    steps: [
      "Dessaler la morue 24h en changeant l'eau 3 fois.",
      "Emietter finement la morue, bien essorer (aucune eau).",
      "Melanger farine, levure, oignon/ail/persil/cive haches tres fin.",
      "Incorporer morue emiettee, ajouter eau progressivement pour pate souple.",
      "Chauffer huile a 170C. Former des boulettes a la cuillere.",
      "Frire 3-4 min en retournant, jusqu'a dore uniforme.",
      "Egoutter sur papier absorbant, servir chaud.",
    ],
    techniques: ["fry"],
    tags: ["street-food", "guadeloupe", "apéritif", "friture"],
  },
  {
    id: "dombre-crevettes",
    name: "Dombré aux crevettes",
    desireName: "Dombré fondants aux crevettes, sauce tomate épicée",
    aliases: ["dombre", "dombré", "dombrés aux crevettes"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "pate-epicee",
    technique: "braise",
    baseFamilies: ["farine", "crevette", "oignon", "tomate", "ail"],
    fundamentals: ["petits dombrés reguliers", "sauce tomate simple", "cuisson ensemble"],
    timings: { prep: 20, cook: 30, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Petits dombrés pates dans sauce tomate-crevette mijotée",
    profTips: [
      "Dombrés reguliers (3-4cm) pour cuisson homogene dans sauce",
      "Sauce simple: tomate, oignon, ail, crevettes",
      "Cuire dombrés EN sauce, pas a part",
    ],
    mistakes: [
      "Dombrés trop gros = pas cuit au coeur",
      "Sauce trop bouillon-e = plat sans corps",
      "Trop crevettes = deseq vers fruit de mer",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 5 },
    category: "plat",
    baseIngredients: ["farine", "crevettes", "concentre de tomate", "oignon", "ail", "thym", "piment"],
    ingredients: [
      { name: "farine", quantity: "200g" },
      { name: "eau", quantity: "100ml" },
      { name: "crevettes decortiquees", quantity: "300g" },
      { name: "concentre de tomate", quantity: "2 cs" },
      { name: "oignon", quantity: "1" },
      { name: "ail", quantity: "3 gousses" },
      { name: "thym", quantity: "2 branches" },
      { name: "piment antillais", quantity: "1" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Preparer dombrés: melanger farine + eau + pincee sel, former petites boules de 3cm.",
      "Faire revenir oignon et ail haches dans huile 3 min.",
      "Ajouter concentre de tomate, mouiller avec 400ml eau, porter a ebullition.",
      "Deposer les dombrés dans la sauce, couvrir et cuire 15 min.",
      "Ajouter crevettes et piment entier, cuire encore 8-10 min.",
      "Retirer piment, rectifier assaisonnement. Servir chaud.",
    ],
    techniques: ["braise"],
    tags: ["mijoté", "guadeloupe", "crevettes", "pâtes"],
  },
  {
    id: "court-bouillon",
    name: "Court-bouillon antillais",
    desireName: "Court-bouillon de poisson à la créole, sauce relevée",
    aliases: ["court-bouillon", "court bouillon"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dinner",
    difficulty: 3,
    minChefLevel: 3,
    family: "poisson-sauce",
    technique: "braise",
    baseFamilies: ["poisson-blanc", "tomate", "citron", "oignon"],
    fundamentals: ["base tomate riche", "poisson fin de cuisson", "oignon fondant"],
    timings: { prep: 15, cook: 40, rest: 0 },
    servings: 2,
    portionAdaptation: "moderate",
    signature: "Poisson blanc dans sauce tomate onctueuse, oignons fondants",
    profTips: [
      "Faire fondre oignon 10 min avant d'ajouter poisson",
      "Sauce tomate doit etre riche, concentree",
      "Poisson ajoute fin pour juste cuit, pas trop",
    ],
    mistakes: [
      "Sauce trop aqueuse = pas de saveur",
      "Poisson trop longtemps = chair cassante",
      "Oignon pas fondu = texture desagreable",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 3, visuel: 5, arome: 5 },
    category: "poisson",
    baseIngredients: ["poisson blanc", "tomate", "oignon", "ail", "citron vert", "piment", "thym", "persil"],
    ingredients: [
      { name: "darne de poisson (vivaneau, merou)", quantity: "400g" },
      { name: "tomate", quantity: "4" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "3 gousses" },
      { name: "citron vert", quantity: "1" },
      { name: "piment antillais", quantity: "1" },
      { name: "thym", quantity: "3 branches" },
      { name: "persil", quantity: "1 bouquet" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Faire fondre oignon emince dans huile 10 min a feu doux.",
      "Ajouter ail, tomate concassee, thym et piment entier.",
      "Mijoter la sauce 15 min jusqu'a epaississement.",
      "Deposer les darnes de poisson dans la sauce, couvrir.",
      "Cuire 10-12 min a feu doux (poisson juste cuit).",
      "Arroser de jus de citron vert, parsemer de persil. Servir avec riz.",
    ],
    techniques: ["braise"],
    tags: ["poisson", "guadeloupe", "sauce tomate", "mijoté"],
  },
  {
    id: "matoutou-crabes",
    name: "Matoutou crabe",
    desireName: "Matoutou de crabe royal, riz parfumé aux épices",
    aliases: ["matoutou", "matoutou crabe", "crabes matoutou"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 4,
    minChefLevel: 4,
    family: "crustace-riz",
    technique: "braise",
    baseFamilies: ["crabe", "riz", "epinard", "oignon", "ail"],
    fundamentals: ["crabe cuit d'abord", "riz cuit dans chair crabe", "saveur iodee"],
    timings: { prep: 25, cook: 40, rest: 5 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Riz melange a chair crabe, epinard, cuisine dans carapace",
    profTips: [
      "Crabe cuire d'abord, puis extraire chair",
      "Riz cuit dans jus extraction crabe + epinard",
      "Farce servie EN carapace crabe pour presentation",
    ],
    mistakes: [
      "Crabe cru = danger sanitaire",
      "Riz pas assez cuit = grain dur",
      "Trop epinard = gout amer domine",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 5, arome: 5 },
    category: "plat",
    baseIngredients: ["crabe", "riz", "epinard", "oignon", "ail", "thym", "piment", "cive"],
    ingredients: [
      { name: "crabes (tourteaux ou crabes de terre)", quantity: "4" },
      { name: "riz long grain", quantity: "300g" },
      { name: "epinard frais", quantity: "200g" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "4 gousses" },
      { name: "thym", quantity: "3 branches" },
      { name: "piment antillais", quantity: "1" },
      { name: "cive", quantity: "4 tiges" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Cuire les crabes 15 min dans eau bouillante salee. Decortiquer et recuperer la chair.",
      "Faire revenir oignon et ail dans huile 5 min.",
      "Ajouter epinard, cuire 3 min jusqu'a reduction.",
      "Ajouter riz, thym, piment entier. Mouiller avec 600ml d'eau de cuisson du crabe.",
      "Cuire couvert 18 min a feu doux.",
      "Incorporer chair de crabe, melanger delicatement. Laisser reposer 5 min couvert.",
      "Servir dans les carapaces de crabe pour presentation traditionnelle.",
    ],
    techniques: ["braise", "boil"],
    tags: ["fête", "guadeloupe", "crabe", "riz", "Pâques"],
  },
];

// ============================================
// LOT 2 — 3 nouveaux plats vérifiés
// ============================================
const LOT_2: DishProfile[] = [
  {
    id: "gratin-christophine",
    name: "Gratin de christophines",
    desireName: "Gratin doré de christophines, béchamel créole",
    aliases: ["gratin christophine", "gratin christophines", "christophine gratin"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratin",
    technique: "bake",
    baseFamilies: ["christophine", "creme", "fromage", "oignon"],
    fundamentals: ["christophines cuites mais encore fermes", "bechamel legere", "gratinage final"],
    timings: { prep: 20, cook: 30, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Christophines fondantes sous croute gratinee doree, bechamel legere",
    profTips: [
      "Cuire christophines 15 min max, elles doivent rester legèrement fermes",
      "Ecraser grossièrement, pas en purée lisse",
      "Bechamel légère, pas épaisse, le gratin ne doit pas être lourd",
    ],
    mistakes: [
      "Christophines trop cuites = purée aqueuse",
      "Trop de bechamel = gratin noyé",
      "Four pas assez chaud = pas de croute doree",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 3 },
    category: "plat",
    baseIngredients: ["christophine", "lait", "farine", "beurre", "fromage rape", "oignon", "muscade"],
    ingredients: [
      { name: "christophines", quantity: "4" },
      { name: "lait", quantity: "250ml" },
      { name: "farine", quantity: "30g" },
      { name: "beurre", quantity: "30g" },
      { name: "fromage rape", quantity: "80g" },
      { name: "oignon", quantity: "1" },
      { name: "muscade", quantity: "1 pincee" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Peler et couper christophines en morceaux. Cuire 15 min a l'eau bouillante.",
      "Egoutter et ecraser grossierement a la fourchette.",
      "Preparer bechamel: fondre beurre, ajouter farine, puis lait en fouettant.",
      "Melanger christophines ecrasees + bechamel + oignon hache + muscade.",
      "Verser dans plat beurre, couvrir de fromage rape.",
      "Enfourner 25-30 min a 200C jusqu'a gratinage dore.",
    ],
    techniques: ["bake", "boil"],
    tags: ["gratin", "guadeloupe", "accompagnement", "familial"],
  },
  {
    id: "poulet-boucane",
    name: "Poulet boucané",
    desireName: "Poulet boucané fumé au bois de canne, marinade créole",
    aliases: ["poulet boucane", "poulet boucanné", "boucane", "chicken boucane"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "viande-grillee",
    technique: "smoke",
    baseFamilies: ["poulet", "epices", "citron", "piment"],
    fundamentals: ["marinade longue 4h minimum", "fumage au bois de canne", "cuisson lente indirecte"],
    timings: { prep: 20, cook: 90, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Poulet fumé lentement au bois, chair tendre et peau croustillante dorée",
    profTips: [
      "Mariner minimum 4h, idealement la veille",
      "Cuisson indirecte: pas de flamme directe sur le poulet",
      "Arroser regulierement avec la marinade pendant cuisson",
    ],
    mistakes: [
      "Pas assez de marinade = poulet sec et fade",
      "Flamme directe = carbonisé dehors, cru dedans",
      "Cuisson trop rapide = chair seche",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 5, arome: 5 },
    category: "viande",
    baseIngredients: ["poulet", "citron vert", "ail", "piment", "thym", "oignon", "epices colombo", "rhum"],
    ingredients: [
      { name: "poulet entier ou cuisses", quantity: "1.2kg" },
      { name: "citron vert", quantity: "3" },
      { name: "ail", quantity: "6 gousses" },
      { name: "piment antillais", quantity: "1" },
      { name: "thym frais", quantity: "4 branches" },
      { name: "oignon", quantity: "1" },
      { name: "poudre de colombo", quantity: "1 cs" },
      { name: "rhum vieux", quantity: "2 cs", optional: true },
      { name: "sel, poivre" },
    ],
    steps: [
      "Mixer ail, oignon, piment, thym, jus de citron, colombo et rhum en marinade.",
      "Inciser le poulet, frotter partout avec la marinade. Refrigerer 4h minimum.",
      "Preparer un barbecue ou four a 160C avec coupelle d'eau pour humidite.",
      "Cuire poulet en cuisson indirecte 1h30, en arrosant toutes les 20 min.",
      "Augmenter chaleur les 10 dernieres minutes pour croustiller la peau.",
      "Laisser reposer 10 min couvert avant decoupe.",
    ],
    techniques: ["smoke", "sear"],
    tags: ["barbecue", "guadeloupe", "fumé", "fête"],
  },
  {
    id: "chatrou-fricassee",
    name: "Fricassée de chatrou",
    desireName: "Fricassée de chatrou tendre, sauce créole mijotée",
    aliases: ["chatrou", "fricassee chatrou", "poulpe antillais", "chatrou fricasse"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dinner",
    difficulty: 4,
    minChefLevel: 4,
    family: "fruit-de-mer",
    technique: "braise",
    baseFamilies: ["poulpe", "tomate", "oignon", "ail", "piment"],
    fundamentals: ["attendrir le chatrou avant cuisson", "cuisson longue et douce", "sauce tomate concentree"],
    timings: { prep: 25, cook: 60, rest: 5 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Poulpe ultra tendre dans sauce tomate épicée, fondant en bouche",
    profTips: [
      "Battre ou congeler le chatrou avant pour attendrir les fibres",
      "Cuisson lente obligatoire: 1h minimum a feu tres doux",
      "Sauce doit reduire et devenir epaisse, pas liquide",
    ],
    mistakes: [
      "Chatrou pas attendri = caoutchouteux immangeable",
      "Cuisson trop rapide = dur",
      "Sauce trop liquide = pas de corps",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 5 },
    category: "poisson",
    baseIngredients: ["poulpe", "tomate", "oignon", "ail", "citron vert", "thym", "piment", "persil"],
    ingredients: [
      { name: "chatrou (poulpe)", quantity: "600g" },
      { name: "tomate", quantity: "4" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "4 gousses" },
      { name: "citron vert", quantity: "1" },
      { name: "thym", quantity: "3 branches" },
      { name: "piment antillais", quantity: "1" },
      { name: "persil", quantity: "1 bouquet" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Nettoyer le chatrou, retirer bec et yeux. Battre pour attendrir.",
      "Couper en morceaux de 3cm. Frotter au citron vert.",
      "Faire revenir oignon et ail 5 min dans huile.",
      "Ajouter tomate concassee, thym et piment entier. Mijoter 10 min.",
      "Ajouter les morceaux de chatrou. Couvrir et cuire 1h a feu tres doux.",
      "Verifier tendrete (la fourchette doit entrer sans resistance).",
      "Parsemer de persil, servir avec riz ou igname.",
    ],
    techniques: ["braise"],
    tags: ["fruit de mer", "guadeloupe", "mijoté", "traditionnel"],
  },
];

/** Tous les plats antillais validés */
export const PLATS_ANTILLAIS: DishProfile[] = [...LOT_1, ...LOT_2];
