/**
 * PLATS ANTILLAIS — Base qualitative vérifiée
 * Chaque plat est réel, avec ingrédients cohérents et étapes crédibles.
 * Organisé par lots validés.
 */

import { DishProfile } from "../dishKnowledge";
import ANTILLAIS_LOT4 from "./antillais_LOT4";

// ============================================
// LOT 1 — 7 plats existants (vérifiés phase 2-4)
// ============================================
const LOT_1: DishProfile[] = [
  {
    id: "bokit-classique",
    name: "Bokit traditionnel",
    desireName: "Bokit doré croustillant, garni poulet épicé",
    aliases: ["bokit", "bokits"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "snack",
    difficulty: 2,
    minChefLevel: 2,
    family: "friture",
    technique: "fry",
    baseFamilies: ["farine", "levure"],
    fundamentals: ["pate levee legere", "friture exact 165C", "repos essentiellement"],
    timings: { prep: 15, cook: 20, rest: 30 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Poche gonflée dorée avec intérieur moelleux, garnie après",
    profTips: [
      "Mesurer huile a 165C exactement pour texture croustillante",
      "Laisser reposer la pate 30+ minutes pour que la poche gonfle",
      "Garnir APRES friture quand bokit est encore chaud",
    ],
    mistakes: [
      "Huile trop chaude = bokit compact et sec intérieur",
      "Pas de repos = poche mal gonflée",
      "Garnir AVANT = garniture degouline",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 5, visuel: 3, arome: 4 },
    category: "street_food",
    baseIngredients: ["farine", "levure boulangere", "eau", "sel", "huile de friture"],
    ingredients: [
      { name: "farine", quantity: "250g" },
      { name: "levure boulangere", quantity: "7g" },
      { name: "eau tiede", quantity: "150ml" },
      { name: "sel", quantity: "1 cc" },
      { name: "huile de friture", quantity: "1L" },
    ],
    steps: [
      "Melanger farine, sel et levure. Ajouter eau tiede progressivement.",
      "Petrir 5 min jusqu'a pate souple et homogene.",
      "Couvrir et laisser reposer 30 min minimum a temperature ambiante.",
      "Diviser en boules de 80g, etaler en disques de 15cm.",
      "Chauffer huile a 165C exactement (thermometre obligatoire).",
      "Frire chaque disque 2-3 min par face, il doit gonfler en poche.",
      "Egoutter sur papier absorbant, ouvrir et garnir immediatement.",
    ],
    techniques: ["fry", "knead"],
    tags: ["street-food", "guadeloupe", "friture", "rapide"],
  },
  {
    id: "colombo-poulet",
    name: "Colombo de poulet",
    desireName: "Colombo de poulet fondant aux épices créoles",
    aliases: ["colombo", "colombo poulet", "colombo de poulet antillais"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "curry-arom",
    technique: "braise",
    baseFamilies: ["poulet", "oignon", "ail", "tomate", "epices"],
    fundamentals: ["marinade 30min avant", "epices colombo toastees", "mijotage 45min min"],
    timings: { prep: 20, cook: 50, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Poulet tendre dans sauce riche epices colombo, légumes fondants",
    profTips: [
      "Toaster les epices colombo 2 min avant pour reveler aromes",
      "Laisser poulet mariner minimum 30 min avec epices, ail, citron",
      "Mijoter basse temperature pour viande tendre, pas coriace",
    ],
    mistakes: [
      "Pas toaster epices = gout plat",
      "Cuisson trop rapide = poulet sec",
      "Trop eau = sauce diluee, pas onctueuse",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 5 },
    category: "plat",
    baseIngredients: ["poulet", "poudre colombo", "oignon", "ail", "tomate", "citron vert", "thym", "aubergine", "pomme de terre"],
    ingredients: [
      { name: "cuisses de poulet", quantity: "800g" },
      { name: "poudre de colombo", quantity: "2 cs" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "4 gousses" },
      { name: "tomate", quantity: "3" },
      { name: "citron vert", quantity: "1" },
      { name: "thym frais", quantity: "3 branches" },
      { name: "aubergine", quantity: "1" },
      { name: "pomme de terre", quantity: "2" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Decouper poulet en morceaux, frotter avec colombo, ail ecrase, jus de citron vert.",
      "Laisser mariner 30 min minimum au frais.",
      "Faire revenir oignon emince 5 min dans huile chaude.",
      "Ajouter le poulet marine, saisir 5 min sur chaque face.",
      "Ajouter tomate concassee, aubergine et pomme de terre en cubes.",
      "Mouiller a hauteur, ajouter thym. Couvrir et mijoter 45 min a feu doux.",
      "Rectifier assaisonnement, servir avec riz blanc.",
    ],
    techniques: ["braise", "sear", "marinate"],
    tags: ["mijoté", "guadeloupe", "épicé", "familial"],
  },
  {
    id: "blaff-poisson",
    name: "Blaff de poisson",
    desireName: "Blaff de poisson frais, bouillon citronné parfumé",
    aliases: ["blaff", "blaff poisson"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dinner",
    difficulty: 3,
    minChefLevel: 3,
    family: "poisson-bouillon",
    technique: "poach",
    baseFamilies: ["poisson-blanc", "citron", "oignon", "tomate"],
    fundamentals: ["bouillon aromatique fort", "pochage doux 6-8 min", "jus citron apres"],
    timings: { prep: 15, cook: 40, rest: 0 },
    servings: 2,
    portionAdaptation: "moderate",
    signature: "Poisson blanc juste poché dans bouillon tomate-citron, jus vivace",
    profTips: [
      "Construire bouillon aromatique fort avant d'ajouter poisson",
      "Poisson ne doit jamais bouillir = eau juste fremissante",
      "Finition citron frais pour acidite, pas avant cuisson",
    ],
    mistakes: [
      "Bouillon pas assez aromatise = plat sans saveur",
      "Poisson bouillie = chair cassante, seche",
      "Ajouter citron trop tot = perte acidite",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 3, visuel: 4, arome: 5 },
    category: "poisson",
    baseIngredients: ["poisson blanc", "citron vert", "oignon", "ail", "piment", "thym", "bois d'inde", "cive"],
    ingredients: [
      { name: "filets de poisson blanc (vivaneau, dorade)", quantity: "400g" },
      { name: "citron vert", quantity: "2" },
      { name: "oignon", quantity: "1" },
      { name: "ail", quantity: "3 gousses" },
      { name: "piment antillais", quantity: "1" },
      { name: "thym frais", quantity: "3 branches" },
      { name: "bois d'inde", quantity: "2 feuilles", optional: true },
      { name: "cive (oignon vert)", quantity: "4 tiges" },
      { name: "eau", quantity: "500ml" },
    ],
    steps: [
      "Porter eau a ebullition avec oignon emince, ail, thym, bois d'inde et piment entier.",
      "Laisser infuser 15 min pour construire le bouillon aromatique.",
      "Baisser a fremissement doux (jamais bouillir avec le poisson).",
      "Deposer les filets de poisson dans le bouillon, pocher 6-8 min.",
      "Retirer poisson delicatement. Ajouter cive ciselée et jus de citron vert.",
      "Servir poisson nappe de bouillon, avec riz blanc ou pain.",
    ],
    techniques: ["poach"],
    tags: ["poisson", "guadeloupe", "léger", "bouillon"],
  },
  {
    id: "accras-morue",
    name: "Accras de morue",
    desireName: "Accras dorés croustillants, coeur moelleux à la morue",
    aliases: ["accras", "acras", "accras morue"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "snack",
    difficulty: 2,
    minChefLevel: 2,
    family: "friture",
    technique: "fry",
    baseFamilies: ["morue", "farine", "levure"],
    fundamentals: ["morue dessalee bien drainee", "pate legere", "friture 170C"],
    timings: { prep: 20, cook: 15, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Boules dorées croustillantes morue, dedans tendre",
    profTips: [
      "Bien essorer morue apres dessalage = aucune eau surplus",
      "Pate doit etre legere, ailee, pas compacte",
      "Friture 170C exactement pour dorage maitrise",
    ],
    mistakes: [
      "Morue pas bien essores = accras gras",
      "Pate trop epaisse = cuit pas au coeur",
      "Huile trop chaude = brule dehors, cru dedans",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 4 },
    category: "street_food",
    baseIngredients: ["morue", "farine", "levure chimique", "oignon", "ail", "persil", "piment", "cive"],
    ingredients: [
      { name: "morue dessalee", quantity: "200g" },
      { name: "farine", quantity: "150g" },
      { name: "levure chimique", quantity: "1 cc" },
      { name: "oignon", quantity: "1 petit" },
      { name: "ail", quantity: "2 gousses" },
      { name: "persil frais", quantity: "1 bouquet" },
      { name: "piment antillais", quantity: "1/2" },
      { name: "cive", quantity: "3 tiges" },
      { name: "huile de friture", quantity: "1L" },
    ],
    steps: [
      "Dessaler la morue 24h en changeant l'eau 3 fois.",
      "Emietter finement la morue, bien essorer (aucune eau).",
      "Melanger farine, levure, oignon/ail/persil/cive haches tres fin.",
      "Incorporer morue emiettee, ajouter eau progressivement pour pate souple.",
      "Chauffer huile a 170C. Former des boulettes a la cuillere.",
      "Frire 3-4 min en retournant, jusqu'a dore uniforme.",
      "Egoutter sur papier absorbant, servir chaud.",
    ],
    techniques: ["fry"],
    tags: ["street-food", "guadeloupe", "apéritif", "friture"],
  },
  {
    id: "dombre-crevettes",
    name: "Dombré aux crevettes",
    desireName: "Dombré fondants aux crevettes, sauce tomate épicée",
    aliases: ["dombre", "dombré", "dombrés aux crevettes"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "pate-epicee",
    technique: "braise",
    baseFamilies: ["farine", "crevette", "oignon", "tomate", "ail"],
    fundamentals: ["petits dombrés reguliers", "sauce tomate simple", "cuisson ensemble"],
    timings: { prep: 20, cook: 30, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Petits dombrés pates dans sauce tomate-crevette mijotée",
    profTips: [
      "Dombrés reguliers (3-4cm) pour cuisson homogene dans sauce",
      "Sauce simple: tomate, oignon, ail, crevettes",
      "Cuire dombrés EN sauce, pas a part",
    ],
    mistakes: [
      "Dombrés trop gros = pas cuit au coeur",
      "Sauce trop bouillon-e = plat sans corps",
      "Trop crevettes = deseq vers fruit de mer",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 5 },
    category: "plat",
    baseIngredients: ["farine", "crevettes", "concentre de tomate", "oignon", "ail", "thym", "piment"],
    ingredients: [
      { name: "farine", quantity: "200g" },
      { name: "eau", quantity: "100ml" },
      { name: "crevettes decortiquees", quantity: "300g" },
      { name: "concentre de tomate", quantity: "2 cs" },
      { name: "oignon", quantity: "1" },
      { name: "ail", quantity: "3 gousses" },
      { name: "thym", quantity: "2 branches" },
      { name: "piment antillais", quantity: "1" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Preparer dombrés: melanger farine + eau + pincee sel, former petites boules de 3cm.",
      "Faire revenir oignon et ail haches dans huile 3 min.",
      "Ajouter concentre de tomate, mouiller avec 400ml eau, porter a ebullition.",
      "Deposer les dombrés dans la sauce, couvrir et cuire 15 min.",
      "Ajouter crevettes et piment entier, cuire encore 8-10 min.",
      "Retirer piment, rectifier assaisonnement. Servir chaud.",
    ],
    techniques: ["braise"],
    tags: ["mijoté", "guadeloupe", "crevettes", "pâtes"],
  },
  {
    id: "court-bouillon",
    name: "Court-bouillon antillais",
    desireName: "Court-bouillon de poisson à la créole, sauce relevée",
    aliases: ["court-bouillon", "court bouillon"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dinner",
    difficulty: 3,
    minChefLevel: 3,
    family: "poisson-sauce",
    technique: "braise",
    baseFamilies: ["poisson-blanc", "tomate", "citron", "oignon"],
    fundamentals: ["base tomate riche", "poisson fin de cuisson", "oignon fondant"],
    timings: { prep: 15, cook: 40, rest: 0 },
    servings: 2,
    portionAdaptation: "moderate",
    signature: "Poisson blanc dans sauce tomate onctueuse, oignons fondants",
    profTips: [
      "Faire fondre oignon 10 min avant d'ajouter poisson",
      "Sauce tomate doit etre riche, concentree",
      "Poisson ajoute fin pour juste cuit, pas trop",
    ],
    mistakes: [
      "Sauce trop aqueuse = pas de saveur",
      "Poisson trop longtemps = chair cassante",
      "Oignon pas fondu = texture desagreable",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 3, visuel: 5, arome: 5 },
    category: "poisson",
    baseIngredients: ["poisson blanc", "tomate", "oignon", "ail", "citron vert", "piment", "thym", "persil"],
    ingredients: [
      { name: "darne de poisson (vivaneau, merou)", quantity: "400g" },
      { name: "tomate", quantity: "4" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "3 gousses" },
      { name: "citron vert", quantity: "1" },
      { name: "piment antillais", quantity: "1" },
      { name: "thym", quantity: "3 branches" },
      { name: "persil", quantity: "1 bouquet" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Faire fondre oignon emince dans huile 10 min a feu doux.",
      "Ajouter ail, tomate concassee, thym et piment entier.",
      "Mijoter la sauce 15 min jusqu'a epaississement.",
      "Deposer les darnes de poisson dans la sauce, couvrir.",
      "Cuire 10-12 min a feu doux (poisson juste cuit).",
      "Arroser de jus de citron vert, parsemer de persil. Servir avec riz.",
    ],
    techniques: ["braise"],
    tags: ["poisson", "guadeloupe", "sauce tomate", "mijoté"],
  },
  {
    id: "matoutou-crabes",
    name: "Matoutou crabe",
    desireName: "Matoutou de crabe royal, riz parfumé aux épices",
    aliases: ["matoutou", "matoutou crabe", "crabes matoutou"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 4,
    minChefLevel: 4,
    family: "crustace-riz",
    technique: "braise",
    baseFamilies: ["crabe", "riz", "epinard", "oignon", "ail"],
    fundamentals: ["crabe cuit d'abord", "riz cuit dans chair crabe", "saveur iodee"],
    timings: { prep: 25, cook: 40, rest: 5 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Riz melange a chair crabe, epinard, cuisine dans carapace",
    profTips: [
      "Crabe cuire d'abord, puis extraire chair",
      "Riz cuit dans jus extraction crabe + epinard",
      "Farce servie EN carapace crabe pour presentation",
    ],
    mistakes: [
      "Crabe cru = danger sanitaire",
      "Riz pas assez cuit = grain dur",
      "Trop epinard = gout amer domine",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 5, arome: 5 },
    category: "plat",
    baseIngredients: ["crabe", "riz", "epinard", "oignon", "ail", "thym", "piment", "cive"],
    ingredients: [
      { name: "crabes (tourteaux ou crabes de terre)", quantity: "4" },
      { name: "riz long grain", quantity: "300g" },
      { name: "epinard frais", quantity: "200g" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "4 gousses" },
      { name: "thym", quantity: "3 branches" },
      { name: "piment antillais", quantity: "1" },
      { name: "cive", quantity: "4 tiges" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Cuire les crabes 15 min dans eau bouillante salee. Decortiquer et recuperer la chair.",
      "Faire revenir oignon et ail dans huile 5 min.",
      "Ajouter epinard, cuire 3 min jusqu'a reduction.",
      "Ajouter riz, thym, piment entier. Mouiller avec 600ml d'eau de cuisson du crabe.",
      "Cuire couvert 18 min a feu doux.",
      "Incorporer chair de crabe, melanger delicatement. Laisser reposer 5 min couvert.",
      "Servir dans les carapaces de crabe pour presentation traditionnelle.",
    ],
    techniques: ["braise", "boil"],
    tags: ["fête", "guadeloupe", "crabe", "riz", "Pâques"],
  },
];

// ============================================
// LOT 2 — 3 nouveaux plats vérifiés
// ============================================
const LOT_2: DishProfile[] = [
  {
    id: "gratin-christophine",
    name: "Gratin de christophines",
    desireName: "Gratin doré de christophines, béchamel créole",
    aliases: ["gratin christophine", "gratin christophines", "christophine gratin"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratin",
    technique: "bake",
    baseFamilies: ["christophine", "creme", "fromage", "oignon"],
    fundamentals: ["christophines cuites mais encore fermes", "bechamel legere", "gratinage final"],
    timings: { prep: 20, cook: 30, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Christophines fondantes sous croute gratinee doree, bechamel legere",
    profTips: [
      "Cuire christophines 15 min max, elles doivent rester legèrement fermes",
      "Ecraser grossièrement, pas en purée lisse",
      "Bechamel légère, pas épaisse, le gratin ne doit pas être lourd",
    ],
    mistakes: [
      "Christophines trop cuites = purée aqueuse",
      "Trop de bechamel = gratin noyé",
      "Four pas assez chaud = pas de croute doree",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 3 },
    category: "plat",
    baseIngredients: ["christophine", "lait", "farine", "beurre", "fromage rape", "oignon", "muscade"],
    ingredients: [
      { name: "christophines", quantity: "4" },
      { name: "lait", quantity: "250ml" },
      { name: "farine", quantity: "30g" },
      { name: "beurre", quantity: "30g" },
      { name: "fromage rape", quantity: "80g" },
      { name: "oignon", quantity: "1" },
      { name: "muscade", quantity: "1 pincee" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Peler et couper christophines en morceaux. Cuire 15 min a l'eau bouillante.",
      "Egoutter et ecraser grossierement a la fourchette.",
      "Preparer bechamel: fondre beurre, ajouter farine, puis lait en fouettant.",
      "Melanger christophines ecrasees + bechamel + oignon hache + muscade.",
      "Verser dans plat beurre, couvrir de fromage rape.",
      "Enfourner 25-30 min a 200C jusqu'a gratinage dore.",
    ],
    techniques: ["bake", "boil"],
    tags: ["gratin", "guadeloupe", "accompagnement", "familial"],
  },
  {
    id: "poulet-boucane",
    name: "Poulet boucané",
    desireName: "Poulet boucané fumé au bois de canne, marinade créole",
    aliases: ["poulet boucane", "poulet boucanné", "boucane", "chicken boucane"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "viande-grillee",
    technique: "smoke",
    baseFamilies: ["poulet", "epices", "citron", "piment"],
    fundamentals: ["marinade longue 4h minimum", "fumage au bois de canne", "cuisson lente indirecte"],
    timings: { prep: 20, cook: 90, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Poulet fumé lentement au bois, chair tendre et peau croustillante dorée",
    profTips: [
      "Mariner minimum 4h, idealement la veille",
      "Cuisson indirecte: pas de flamme directe sur le poulet",
      "Arroser regulierement avec la marinade pendant cuisson",
    ],
    mistakes: [
      "Pas assez de marinade = poulet sec et fade",
      "Flamme directe = carbonisé dehors, cru dedans",
      "Cuisson trop rapide = chair seche",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 5, arome: 5 },
    category: "viande",
    baseIngredients: ["poulet", "citron vert", "ail", "piment", "thym", "oignon", "epices colombo", "rhum"],
    ingredients: [
      { name: "poulet entier ou cuisses", quantity: "1.2kg" },
      { name: "citron vert", quantity: "3" },
      { name: "ail", quantity: "6 gousses" },
      { name: "piment antillais", quantity: "1" },
      { name: "thym frais", quantity: "4 branches" },
      { name: "oignon", quantity: "1" },
      { name: "poudre de colombo", quantity: "1 cs" },
      { name: "rhum vieux", quantity: "2 cs", optional: true },
      { name: "sel, poivre" },
    ],
    steps: [
      "Mixer ail, oignon, piment, thym, jus de citron, colombo et rhum en marinade.",
      "Inciser le poulet, frotter partout avec la marinade. Refrigerer 4h minimum.",
      "Preparer un barbecue ou four a 160C avec coupelle d'eau pour humidite.",
      "Cuire poulet en cuisson indirecte 1h30, en arrosant toutes les 20 min.",
      "Augmenter chaleur les 10 dernieres minutes pour croustiller la peau.",
      "Laisser reposer 10 min couvert avant decoupe.",
    ],
    techniques: ["smoke", "sear"],
    tags: ["barbecue", "guadeloupe", "fumé", "fête"],
  },
  {
    id: "chatrou-fricassee",
    name: "Fricassée de chatrou",
    desireName: "Fricassée de chatrou tendre, sauce créole mijotée",
    aliases: ["chatrou", "fricassee chatrou", "poulpe antillais", "chatrou fricasse"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dinner",
    difficulty: 4,
    minChefLevel: 4,
    family: "fruit-de-mer",
    technique: "braise",
    baseFamilies: ["poulpe", "tomate", "oignon", "ail", "piment"],
    fundamentals: ["attendrir le chatrou avant cuisson", "cuisson longue et douce", "sauce tomate concentree"],
    timings: { prep: 25, cook: 60, rest: 5 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Poulpe ultra tendre dans sauce tomate épicée, fondant en bouche",
    profTips: [
      "Battre ou congeler le chatrou avant pour attendrir les fibres",
      "Cuisson lente obligatoire: 1h minimum a feu tres doux",
      "Sauce doit reduire et devenir epaisse, pas liquide",
    ],
    mistakes: [
      "Chatrou pas attendri = caoutchouteux immangeable",
      "Cuisson trop rapide = dur",
      "Sauce trop liquide = pas de corps",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 5 },
    category: "poisson",
    baseIngredients: ["poulpe", "tomate", "oignon", "ail", "citron vert", "thym", "piment", "persil"],
    ingredients: [
      { name: "chatrou (poulpe)", quantity: "600g" },
      { name: "tomate", quantity: "4" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "4 gousses" },
      { name: "citron vert", quantity: "1" },
      { name: "thym", quantity: "3 branches" },
      { name: "piment antillais", quantity: "1" },
      { name: "persil", quantity: "1 bouquet" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Nettoyer le chatrou, retirer bec et yeux. Battre pour attendrir.",
      "Couper en morceaux de 3cm. Frotter au citron vert.",
      "Faire revenir oignon et ail 5 min dans huile.",
      "Ajouter tomate concassee, thym et piment entier. Mijoter 10 min.",
      "Ajouter les morceaux de chatrou. Couvrir et cuire 1h a feu tres doux.",
      "Verifier tendrete (la fourchette doit entrer sans resistance).",
      "Parsemer de persil, servir avec riz ou igname.",
    ],
    techniques: ["braise"],
    tags: ["fruit de mer", "guadeloupe", "mijoté", "traditionnel"],
  },
];

// ============================================
// LOT 3 — 12 plats supplémentaires (variété créole)
// ============================================
const LOT_3: DishProfile[] = [
  {
    id: "ferocee-avocat",
    name: "Féroce d'avocat",
    desireName: "Féroce d'avocat crémeux, morue dessalée, manioc",
    aliases: ["ferocee", "féroce avocat", "feroce d'avocat"],
    cuisine: "antillaise",
    region: "Martinique",
    slot: "snack",
    difficulty: 1,
    minChefLevel: 1,
    family: "puree",
    technique: "mix",
    baseFamilies: ["avocat", "morue", "manioc", "citron"],
    fundamentals: ["avocat bien mûr", "morue bien dessalée", "ecrasé à la fourchette"],
    timings: { prep: 15, cook: 0, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Purée crémeuse avocat-morue, texture riche et acidulée",
    profTips: [
      "Avocat doit être très mûr pour texture crémeuse",
      "Morue bien essorer après dessalage sinon aqueux",
      "Écraser à la fourchette, pas mixer",
    ],
    mistakes: [
      "Avocat pas mûr = texture fibreuse",
      "Morue trop salée = féroce inédible",
      "Trop d'eau = purée se désagrège",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "plat",
    baseIngredients: ["avocat", "morue", "manioc râpé", "citron vert", "oignon", "persil"],
    ingredients: [
      { name: "avocat bien mûr", quantity: "2" },
      { name: "morue dessalée", quantity: "150g" },
      { name: "manioc râpé", quantity: "100g" },
      { name: "citron vert", quantity: "1" },
      { name: "oignon", quantity: "1 petit" },
      { name: "persil", quantity: "1 bouquet" },
    ],
    steps: [
      "Essorer bien la morue après dessalage, émietter finement.",
      "Couper avocat en deux, récupérer la chair.",
      "Écraser avocat à la fourchette, mélanger morue émiettée.",
      "Ajouter manioc râpé, oignon haché fin, persil ciselé.",
      "Arroser de jus de citron vert pour acidité et liaison.",
      "Servir immédiatement avec pain ou crackers.",
    ],
    techniques: ["mix", "blend"],
    tags: ["apéritif", "martinique", "facile", "rapide"],
  },
  {
    id: "crabe-farci",
    name: "Crabe farci",
    desireName: "Crabe royale farcie aux épices, chair de crabe sauce créole",
    aliases: ["crabe farci", "crab stuffed", "crabs farcis"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 4,
    minChefLevel: 4,
    family: "crustace-farci",
    technique: "bake",
    baseFamilies: ["crabe", "oignon", "ail", "tomate", "oeuf"],
    fundamentals: ["crabe cuit et decortiquer", "farce chair + liant", "au four 20 min"],
    timings: { prep: 30, cook: 45, rest: 5 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Carapace crabe remplie chair-farceau, croustillant dessus",
    profTips: [
      "Cuire crab d'abord avant de le décortiquer",
      "Garder carapaces intactes pour présentation",
      "Compacter la farce bien, sinon se désagrège en cuisant",
    ],
    mistakes: [
      "Crabe cru = risque sanitaire",
      "Farce trop mouille = s'écoule à la cuisson",
      "Pas assez d'épices = crabe fade",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 5, arome: 5 },
    category: "crustace",
    baseIngredients: ["crabe", "oeuf", "oignon", "ail", "tomate", "chapelure", "persil", "thym"],
    ingredients: [
      { name: "crabes (entiers)", quantity: "4" },
      { name: "oeuf", quantity: "2" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "4 gousses" },
      { name: "tomate", quantity: "2" },
      { name: "chapelure", quantity: "100g" },
      { name: "persil", quantity: "2 bouquets" },
      { name: "thym", quantity: "1 branche" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Cuire crabes 15 min dans eau bouillante. Refroidir.",
      "Casser les carapaces avec soin, garder comme récipients.",
      "Piquer la chair brune, décortiquer complètement.",
      "Faire base: sauter oignon/ail, ajouter tomate/persil, cuire 10 min.",
      "Mélanger chair crabe + oeuf + tomate prép + chapelure.",
      "Remplir carapaces compactant bien.",
      "Enfourner 200C 20 min jusqu'à dorage. Servir chaud.",
    ],
    techniques: ["bake", "boil"],
    tags: ["fête", "crabe", "farci", "guadeloupe"],
  },
  {
    id: "oursin-antillais",
    name: "Oursins à la créole",
    desireName: "Oursins frais unis, sauce tomate-citron épicée",
    aliases: ["oursin", "oursins", "sea urchin creole"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dinner",
    difficulty: 1,
    minChefLevel: 2,
    family: "fruit-mer",
    technique: "raw",
    baseFamilies: ["oursin", "tomate", "citron", "piment"],
    fundamentals: ["oursins frais du jour", "sauce tomate légère", "citron frais"],
    timings: { prep: 10, cook: 0, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Chair d'oursin vive et crémeuse, sauce tomate-citron vivace",
    profTips: [
      "Acheter oursins de jour même, ultra frais",
      "Ouvrir délicatement à la pointe du couteau",
      "Sauce simple: tomate fraîche, citron, piment",
    ],
    mistakes: [
      "Oursins pas frais = goût iodé agressif",
      "Trop de sauce = noie la subtilité",
      "Pas assez de citron = mou sans acidité",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 3, visuel: 4, arome: 4 },
    category: "fruits_mer",
    baseIngredients: ["oursin", "tomate", "citron vert", "piment"],
    ingredients: [
      { name: "oursins frais", quantity: "6" },
      { name: "tomate fraîche", quantity: "2" },
      { name: "citron vert", quantity: "1" },
      { name: "piment antillais", quantity: "1" },
      { name: "sel fin" },
    ],
    steps: [
      "Tenir oursin dans main gauche (piquants vers haut).",
      "Couper l'arête-sommet avec couteau pointu, l'enlever.",
      "Racler la chair rose (corail) à la cuillère.",
      "Préparer sauce: tomate concassée + jus citron + piment haché fin.",
      "Servir oursins dans leur carapace avec sauce en accompagnement.",
      "Manger à la cuillère la chair + sauce.",
    ],
    techniques: ["raw"],
    tags: ["fruits de mer", "guadeloupe", "frais", "luxe"],
  },
  {
    id: "moules-creoles",
    name: "Moules à la créole",
    desireName: "Moules fraîches à l'ail, vin blanc, sauce créole tomate",
    aliases: ["moules creoles", "mouli creole", "steamed mussels"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dinner",
    difficulty: 2,
    minChefLevel: 2,
    family: "fruit-mer",
    technique: "steam",
    baseFamilies: ["moules", "ail", "tomate", "persil"],
    fundamentals: ["moules propres", "cuisson rapide", "bouillon léger"],
    timings: { prep: 15, cook: 10, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Moules ouvertes jus réduit tomate-ail-persil frais",
    profTips: [
      "Nettoyer moules à l'eau fraîche, brosser",
      "Vin blanc sec crée vapeur et saveur",
      "Ne pas trop cuire: 3-4 min suffisent",
    ],
    mistakes: [
      "Moules déjà mortes en cuisant = toxiques",
      "Cuisson trop longue = caoutchouteuses",
      "Pas de persil frais = gout plat",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 5 },
    category: "fruits_mer",
    baseIngredients: ["moules", "ail", "vin blanc", "tomate", "persil"],
    ingredients: [
      { name: "moules fraîches", quantity: "1kg" },
      { name: "ail", quantity: "4 gousses" },
      { name: "vin blanc sec", quantity: "200ml" },
      { name: "tomate concassée", quantity: "200g" },
      { name: "persil", quantity: "1 bouquet" },
      { name: "beurre", quantity: "30g" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Nettoyer moules, enlever les barbes.",
      "Sauter ail haché dans beurre 2 min.",
      "Ajouter tomate concassée, cuire 5 min.",
      "Verser vin blanc, augmenter chaleur.",
      "Ajouter moules, couvrir, cuire 4 min jusqu'à ouverture.",
      "Jeter celles fermées, parsemer persil.",
      "Servir immédiatement dans le jus.",
    ],
    techniques: ["steam", "braise"],
    tags: ["fruits de mer", "guadeloupe", "rapide", "délicieux"],
  },
  {
    id: "tournant",
    name: "Tournant créole",
    desireName: "Tournant mou croustillant, farce banane-œuf",
    aliases: ["tournant", "crepe creole", "banana crepe"],
    cuisine: "antillaise",
    region: "Martinique",
    slot: "snack",
    difficulty: 2,
    minChefLevel: 2,
    family: "galette",
    technique: "fry",
    baseFamilies: ["farine", "banane", "œuf", "levure"],
    fundamentals: ["pâte levée légère", "banane bien mûre", "cuisson 2 min"],
    timings: { prep: 20, cook: 20, rest: 30 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Crêpe dorée moelleuse, farce banane-œuf sucrée",
    profTips: [
      "Bananes bien mûres pour saveur sucre",
      "Pâte levée = légèreté",
      "Friture 165C exactement",
    ],
    mistakes: [
      "Bananes trop vertes = fades",
      "Pâte pas levée = dense",
      "Huile trop chaude = brûlé",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 5, visuel: 3, arome: 4 },
    category: "street_food",
    baseIngredients: ["farine", "banane", "œuf", "sucre", "levure"],
    ingredients: [
      { name: "farine", quantity: "300g" },
      { name: "bananes bien mûres", quantity: "3" },
      { name: "œuf", quantity: "2" },
      { name: "sucre", quantity: "50g" },
      { name: "levure boulangère", quantity: "7g" },
      { name: "eau tiède", quantity: "150ml" },
      { name: "sel", quantity: "1 cc" },
      { name: "huile de friture", quantity: "1L" },
    ],
    steps: [
      "Mélanger farine, sel, levure. Ajouter eau tiède progressivement.",
      "Pétrir 5 min, couvrir, laisser reposer 30 min à T ambiante.",
      "Écraser bananes à la fourchette, mélanger œuf crème + sucre.",
      "Diviser pâte en boules, aplatir en disques fins.",
      "Mettre farce banane-œuf au centre, sceller bords.",
      "Frire 165C 2 min par face, dorer uniforme.",
      "Égoutter sur papier, servir tiède.",
    ],
    techniques: ["fry", "knead"],
    tags: ["street-food", "martinique", "sucré", "banane"],
  },
  {
    id: "calalou",
    name: "Calalou antillais",
    desireName: "Calalou velouté aux épinards, crabe et fruits de mer",
    aliases: ["calalou", "callaloo", "creamy greens"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "legume-soupe",
    technique: "braise",
    baseFamilies: ["epinard", "crabe", "crevette", "oignon"],
    fundamentals: ["épinards frais cuits", "fruits de mer", "sauce crémeuse"],
    timings: { prep: 15, cook: 25, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Purée épinards-fruits de mer crémeuse, délicate et riche",
    profTips: [
      "Épinards cuits puis mixés pour texture lisse",
      "Fruits de mer cuits rapidement en fin",
      "Créme de coco allège et enrichit saveur",
    ],
    mistakes: [
      "Épinards trop cuits = goût amer",
      "Trop bouillon = soupe au lieu de purée",
      "Fruits de mer trop cuits = caoutchouteux",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 4 },
    category: "plat",
    baseIngredients: ["épinard", "crabe", "crevette", "oignon", "ail", "coconut milk"],
    ingredients: [
      { name: "épinard frais", quantity: "400g" },
      { name: "crabe (ou écrevisses)", quantity: "300g decortiquées" },
      { name: "crevettes", quantity: "200g" },
      { name: "oignon", quantity: "1" },
      { name: "ail", quantity: "3 gousses" },
      { name: "lait de coco", quantity: "200ml" },
      { name: "bouillon poisson", quantity: "300ml" },
      { name: "thym", quantity: "2 branches" },
    ],
    steps: [
      "Faire cuire épinard 8 min dans eau bouillante, égoutter.",
      "Faire sauter oignon/ail dans huile 3 min.",
      "Ajouter épinard cuit, mixe r finement.",
      "Verser bouillon, ajouter thym, mijoter 10 min.",
      "Ajouter crabe et crevettes, cuire 5 min.",
      "Verser lait de coco en trait fin, mélanger.",
      "Servir chaud avec riz blanc ou pain.",
    ],
    techniques: ["braise", "boil"],
    tags: ["épinard", "fruits de mer", "guadeloupe", "soupe"],
  },
  {
    id: "lambi-anis",
    name: "Lambi à l'anis",
    desireName: "Lambi braissé tendre aux épices anisées et caramélisées",
    aliases: ["lambi", "conque", "lambi anis"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "crustace-braisse",
    technique: "braise",
    baseFamilies: ["lambi", "anis", "tomate", "oignon"],
    fundamentals: ["lambi attendri au marteau", "braisage lent 60 min", "sauce anis riche"],
    timings: { prep: 20, cook: 75, rest: 5 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Lambi tendre braissé sauce anis-tomate, saveur iodée et sucrée",
    profTips: [
      "Battre lambi au marteau pour attendrir",
      "Braisage lent: jamais ébullition",
      "Anis appelle accompagnement rhum vieux",
    ],
    mistakes: [
      "Lambi pas attendri = caoutchouteux",
      "Trop rapide cuisson = dur",
      "Trop peu anis = plat impersonnel",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 3, visuel: 4, arome: 5 },
    category: "fruits_mer",
    baseIngredients: ["lambi", "anis etoile", "tomate", "oignon", "ail", "citron"],
    ingredients: [
      { name: "lambi (entier ou tranches)", quantity: "1kg" },
      { name: "anis étoilé", quantity: "3" },
      { name: "tomate concassée", quantity: "300g" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "4 gousses" },
      { name: "citron vert", quantity: "1" },
      { name: "huile", quantity: "2 cs" },
      { name: "eau", quantity: "400ml" },
    ],
    steps: [
      "Battre lambi énergiquement au marteau pour attendrir.",
      "Sauter oignon/ail dans huile 5 min.",
      "Ajouter anis étoilé, tomate, limiter 5 min.",
      "Ajouter lambi, arroser d'eau.",
      "Couvrir, mijoter très doux 1h jusqu'à tendre.",
      "Rectifier assaisonnement, ajouter jus citron.",
      "Servir chaud avec riz blanc ou igname.",
    ],
    techniques: ["braise"],
    tags: ["fruits de mer", "guadeloupe", "anis", "luxe"],
  },
  {
    id: "patate-douce-gateau",
    name: "Gâteau de patate douce",
    desireName: "Gâteau patate douce sucré-épicé, texture fondante",
    aliases: ["gateau patate", "sweet potato cake", "gâteau de patates"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "dessert",
    difficulty: 2,
    minChefLevel: 2,
    family: "gateau-sucre",
    technique: "bake",
    baseFamilies: ["patate-douce", "cannelle", "rhum", "oeuf"],
    fundamentals: ["patates cuites et écrasées", "épices: cannelle/muscade", "cuisson bas tempér"],
    timings: { prep: 25, cook: 45, rest: 10 },
    servings: 8,
    portionAdaptation: "linear",
    signature: "Gâteau doré spongieux saveur patate-épices, tendre et moelleux",
    profTips: [
      "Patates bien cuites et écrasées lisse",
      "Épices: cannelle+muscade obligatoires",
      "Pas trop sucré pour laisser saveur patate",
    ],
    mistakes: [
      "Patates lumpeuses = texture désagréable",
      "Pas épices = gâteau ennuyeux",
      "Four trop chaud = craquelé",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 4 },
    category: "dessert",
    baseIngredients: ["patate-douce", "œuf", "sucre", "beurre", "cannelle", "muscade"],
    ingredients: [
      { name: "patate douce", quantity: "800g" },
      { name: "œuf", quantity: "3" },
      { name: "sucre", quantity: "150g" },
      { name: "beurre", quantity: "100g mou" },
      { name: "farine", quantity: "100g" },
      { name: "cannelle", quantity: "1 cc" },
      { name: "muscade", quantity: "1/2 cc" },
      { name: "rhum vieux", quantity: "1 cs", optional: true },
    ],
    steps: [
      "Cuire patates 20 min, peler, écraser finement.",
      "Mélanger patates + beurre + sucre jusqu'à crème.",
      "Incorporer œufs un par un (mélange bien).",
      "Ajouter farine tamisée, cannelle, muscade, rhum.",
      "Verser dans moule beurré.",
      "Enfourner 180C 40-45 min (toothpick test).",
      "Laisser refroidir 10 min, démouler.",
    ],
    techniques: ["bake"],
    tags: ["dessert", "guadeloupe", "épices", "sucré"],
  },
  {
    id: "poisson-escabeche",
    name: "Poisson à l'escabèche",
    desireName: "Poisson frit sauce vinaigre-épices, servi froid ou tiède",
    aliases: ["escabeche", "poisson vinaigre", "fish escabache"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "poisson-frit",
    technique: "fry",
    baseFamilies: ["poisson-blanc", "vinaigre", "oignon", "carotte"],
    fundamentals: ["poisson frit croustillant", "sauce vinaigre épicée", "repos 2h"],
    timings: { prep: 20, cook: 25, rest: 120 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Poisson croustillant nacré, sauce vinaigre-oignon aigre-douce",
    profTips: [
      "Poisson sec complètement avant friture",
      "Sauce meilleure après repos 2h minimum",
      "Se consomme froid en escabèche traditionnel",
    ],
    mistakes: [
      "Poisson humide = éclaboussures huile",
      "Vinaigre brûlé = gout désagréable",
      "Pas assez épices = plat fade",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 5, visuel: 4, arome: 4 },
    category: "poisson",
    baseIngredients: ["poisson-blanc", "vinaigre blanc", "oignon", "carotte", "piment"],
    ingredients: [
      { name: "poisson blanc (entier ou filets)", quantity: "800g" },
      { name: "vinaigre blanc", quantity: "150ml" },
      { name: "oignon", quantity: "3" },
      { name: "carotte", quantity: "2" },
      { name: "piment antillais", quantity: "1" },
      { name: "huile friture", quantity: "1L" },
      { name: "thym", quantity: "2 branches" },
      { name: "baie de genièvre", quantity: "5", optional: true },
    ],
    steps: [
      "Préparer sauce: faire revenir oignon tranché + carotte dans huile.",
      "Ajouter vinaigre, thym, piment, baies de genièvre.",
      "Mijoter 10 min, laisser tiédir.",
      "Frire poisson 170C 8-10 min (bien sec), dorer.",
      "Déposer poisson chaud dans sauce tiède.",
      "Laisser reposer 2h minimum au frais pour imprégnation.",
      "Servir froid ou tiède selon saison.",
    ],
    techniques: ["fry", "braise"],
    tags: ["poisson", "guadeloupe", "conserve", "voyages"],
  },
  {
    id: "fricassee-tripes",
    name: "Fricassée de tripes",
    desireName: "Tripes braisées épices créoles, sauce tomate-vinaigre",
    aliases: ["fricassee tripes", "offal creole", "tripa guisada"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "viande-braisee",
    technique: "braise",
    baseFamilies: ["tripes", "tomate", "oignon", "ail"],
    fundamentals: ["tripes bien nettoyées", "blanchissage 45 min", "braisage 90 min"],
    timings: { prep: 30, cook: 150, rest: 10 },
    servings: 6,
    portionAdaptation: "moderate",
    signature: "Tripes fondantes sauce tomate riche, saveur profonde",
    profTips: [
      "Tripes bien nettoyées et blanchies avant",
      "Braisage très lent pour tendreté",
      "Vinaigre essentialiel en fin pour équilibre",
    ],
    mistakes: [
      "Pas blanchir = goût très fort",
      "Cuisson trop rapide = coriaces",
      "Pas vinaigre = gras déséquilibré",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 3, visuel: 2, arome: 5 },
    category: "viande",
    baseIngredients: ["tripes", "tomate", "oignon", "ail", "vinaigre blanc"],
    ingredients: [
      { name: "tripes bien preparées", quantity: "800g" },
      { name: "tomate concassée", quantity: "400g" },
      { name: "oignon", quantity: "3" },
      { name: "ail", quantity: "5 gousses" },
      { name: "bouillon", quantity: "1L" },
      { name: "vinaigre blanc", quantity: "2 cs" },
      { name: "thym", quantity: "3 branches" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Blanchir tripes 45 min eau bouillante, égoutter, découper.",
      "Sauter oignon/ail dans huile 5 min.",
      "Ajouter tripes, revenir 10 min.",
      "Ajouter tomate, thym, bouillon.",
      "Couvrir, mijoter très doux 90 min.",
      "En fin, ajouter vinaigre blanc pour équilibre acide.",
      "Servir chaud avec riz blanc.",
    ],
    techniques: ["braise", "boil"],
    tags: ["tripes", "guadeloupe", "braisé", "complet"],
  },
  {
    id: "piment-fourre",
    name: "Piment farci créole",
    desireName: "Piments doux farcis viande-tomate, sauce créole",
    aliases: ["piment farci", "stuffed peppers", "pimen relleno"],
    cuisine: "antillaise",
    region: "Guadeloupe",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "legume-farci",
    technique: "bake",
    baseFamilies: ["piment-doux", "viande", "tomate", "riz"],
    fundamentals: ["piments doux évider", "farce viande-riz", "braisage sauce"],
    timings: { prep: 25, cook: 40, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Piments doux farce saveur, sauce tomate onctueuse",
    profTips: [
      "Piments doux, pas piments forts",
      "Cuire riz farce 3/4 avant (finira en piment)",
      "Sauce riche mais pas noyée",
    ],
    mistakes: [
      "Piments forts = écrasant",
      "Riz cru = croustille désagréable",
      "Pas assez sauce = sec",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 5, arome: 4 },
    category: "plat",
    baseIngredients: ["piment-doux", "viande haché", "riz", "oignon", "tomate"],
    ingredients: [
      { name: "piments doux rouges/jaunes", quantity: "4" },
      { name: "viande hachée", quantity: "300g" },
      { name: "riz blanc", quantity: "100g" },
      { name: "oignon", quantity: "2" },
      { name: "tomate concassée", quantity: "300g" },
      { name: "ail", quantity: "3 gousses" },
      { name: "olives", quantity: "12", optional: true },
      { name: "œuf", quantity: "1" },
    ],
    steps: [
      "Cuire riz 12 min (semi-cuit).",
      "Découper chapeau piments, enlever graines.",
      "Sauter viande + oignon/ail, ajouter riz cuit, œuf.",
      "Remplir piments, replacer chapeaux.",
      "Ranger dans plat beurré.",
      "Verser sauce tomate autour (pas dessus).",
      "Enfourner 180C 30-40 min.",
    ],
    techniques: ["bake", "braise"],
    tags: ["piment", "guadeloupe", "farci", "familial"],
  },
];

/** Tous les plats antillais validés */
export const PLATS_ANTILLAIS: DishProfile[] = [...LOT_1, ...LOT_2, ...LOT_3, ...ANTILLAIS_LOT4];
