/**
 * PLATS FRANÇAIS — Base qualitative vérifiée
 * Chaque plat est réel, avec ingrédients cohérents et étapes crédibles.
 * Organisé par lots validés.
 */

import { DishProfile } from "../dishKnowledge";
import FRANCAIS_LOT4 from "./francais_LOT4";

// ============================================
// LOT 1 — 9 plats existants (vérifiés phase 2-4)
// ============================================
const LOT_1: DishProfile[] = [
  {
    id: "quiche-lorraine",
    name: "Quiche lorraine",
    desireName: "Quiche lorraine crémeuse, lardons fumés dorés",
    aliases: ["quiche", "quiche lorraine"],
    cuisine: "francaise",
    region: "Lorraine",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "tarte-oeufs",
    technique: "bake",
    baseFamilies: ["farine", "oeuf", "creme", "lard"],
    fundamentals: ["fond pate regulier", "lard cuit d'abord", "creme oeuf bien lie"],
    timings: { prep: 20, cook: 35, rest: 8 },
    servings: 6,
    portionAdaptation: "linear",
    signature: "Tarte crémeuse lard croustillant, custard doree, texture legere",
    profTips: [
      "Pate foncer sans bulles, piquer fond",
      "Lard cuire 5 min avant pour croustillant",
      "Creme et oeufs ne JAMAIS bouillir = texture grumeleuse",
    ],
    mistakes: [
      "Pate pas cuite = soupe dessous",
      "Lard brule = amertume",
      "Cuisson trop longue = creme seche et caoutchouteuse",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "plat",
    baseIngredients: ["pate brisee", "lardons", "oeufs", "creme fraiche", "lait", "muscade"],
    ingredients: [
      { name: "pate brisee", quantity: "1 rouleau" },
      { name: "lardons fumes", quantity: "200g" },
      { name: "oeufs", quantity: "3" },
      { name: "creme fraiche", quantity: "200ml" },
      { name: "lait", quantity: "100ml" },
      { name: "muscade", quantity: "1 pincee" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Prechauffer four a 180C. Foncer le moule avec la pate, piquer le fond.",
      "Faire revenir lardons 5 min a sec pour les rendre croustillants.",
      "Repartir lardons sur le fond de tarte.",
      "Battre oeufs + creme + lait + muscade + sel + poivre.",
      "Verser l'appareil sur les lardons.",
      "Enfourner 35 min jusqu'a surface doree et ferme au toucher.",
      "Laisser reposer 8 min avant de demouler.",
    ],
    techniques: ["bake"],
    tags: ["tarte", "lorraine", "classique", "familial"],
  },
  {
    id: "gratin-dauphinois",
    name: "Gratin dauphinois",
    desireName: "Gratin dauphinois crémeux, croûte gratinée dorée",
    aliases: ["gratin", "gratin dauphinois", "gratin pommes de terre"],
    cuisine: "francaise",
    region: "Dauphiné",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratin",
    technique: "bake",
    baseFamilies: ["pomme-terre", "creme", "lait"],
    fundamentals: ["tranches regulieres 2-3mm", "sauce creme-ail", "cuisson lente 50 min"],
    timings: { prep: 20, cook: 55, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Pommes de terre cremeuses fondantes, surface doree et croustillante",
    profTips: [
      "Tranches regulieres pour cuisson uniforme",
      "Verser sauce creme-ail sur pommes de terre crues",
      "Cuisson four 180C lente pour texture creme",
    ],
    mistakes: [
      "Tranches trop epaisses = pommes de terre crues dedans",
      "Sauce trop peu liquide = gratin sec",
      "Four trop chaud = surface brulee, dedans cru",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 3 },
    category: "plat",
    baseIngredients: ["pomme de terre", "creme fraiche", "lait", "ail", "muscade", "beurre"],
    ingredients: [
      { name: "pommes de terre (type bintje)", quantity: "1kg" },
      { name: "creme fraiche", quantity: "300ml" },
      { name: "lait", quantity: "200ml" },
      { name: "ail", quantity: "2 gousses" },
      { name: "muscade", quantity: "1 pincee" },
      { name: "beurre", quantity: "20g" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Prechauffer four a 180C. Beurrer un plat a gratin, frotter a l'ail.",
      "Eplucher et emincer pommes de terre en tranches de 2-3mm.",
      "Melanger creme + lait + ail hache + muscade + sel + poivre.",
      "Disposer couches de pommes de terre en nappant chaque couche de sauce.",
      "Enfourner 55 min a 180C. Verifier que les pommes de terre sont fondantes.",
      "Laisser reposer 10 min avant de servir.",
    ],
    techniques: ["bake"],
    tags: ["gratin", "dauphiné", "accompagnement", "hiver"],
  },
  {
    id: "coq-au-vin",
    name: "Coq au vin",
    desireName: "Coq au vin mijoté, sauce onctueuse au vin rouge",
    aliases: ["coq au vin", "poulet au vin rouge"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "dinner",
    difficulty: 4,
    minChefLevel: 4,
    family: "braise-rouge",
    technique: "braise",
    baseFamilies: ["poulet", "vin-rouge", "lard", "oignon", "champignon"],
    fundamentals: ["marinade 2-4h avant", "saisir volaille bien", "vin reduce de moitie"],
    timings: { prep: 30, cook: 90, rest: 10 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Poulet tendre vin rouge riche, sauce onctueuse, garniture lard-champignon",
    profTips: [
      "Mariner poule dans vin rouge + herbes 2-4 heures",
      "Saisir poule 3 min chaque face pour croute",
      "Vin doit etre reduit de moitie avant ajouter poule",
    ],
    mistakes: [
      "Pas mariner = gout plat",
      "Poule pas bien saisie = pas couleur",
      "Vin pas reduit = sauce aqueuse et alcool trop fort",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 5, arome: 5 },
    category: "viande",
    baseIngredients: ["poulet", "vin rouge", "lardons", "champignons", "oignon", "carotte", "ail", "bouquet garni"],
    ingredients: [
      { name: "poulet decoupé", quantity: "1.5kg" },
      { name: "vin rouge (Bourgogne)", quantity: "75cl" },
      { name: "lardons", quantity: "150g" },
      { name: "champignons de Paris", quantity: "250g" },
      { name: "petits oignons", quantity: "12" },
      { name: "carotte", quantity: "2" },
      { name: "ail", quantity: "3 gousses" },
      { name: "bouquet garni", quantity: "1" },
      { name: "farine", quantity: "2 cs" },
      { name: "beurre", quantity: "30g" },
    ],
    steps: [
      "Mariner poulet dans vin rouge + bouquet garni + oignon 2-4h au frais.",
      "Egoutter poulet, secher. Reserver la marinade.",
      "Saisir poulet dans beurre 3 min chaque face, reserver.",
      "Faire revenir lardons + oignons + carotte 5 min.",
      "Singer la farine, mouiller avec la marinade. Porter a ebullition.",
      "Remettre le poulet, couvrir et mijoter 1h30 a feu doux.",
      "Ajouter champignons sautes les 15 dernieres minutes.",
      "Rectifier assaisonnement. Laisser reposer 10 min avant servir.",
    ],
    techniques: ["braise", "sear", "marinate"],
    tags: ["mijoté", "bourgogne", "vin rouge", "classique"],
  },
  {
    id: "beef-bourguignon",
    name: "Beef bourguignon",
    desireName: "Boeuf bourguignon fondant, sauce au vin profonde",
    aliases: ["beef bourguignon", "boeuf bourguignon"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "dinner",
    difficulty: 4,
    minChefLevel: 4,
    family: "braise-rouge",
    technique: "braise",
    baseFamilies: ["boeuf", "vin-rouge", "lard", "oignon", "champignon"],
    fundamentals: ["boeuf persille", "saisir cubes tres bien", "vin + bouillon reduit"],
    timings: { prep: 40, cook: 150, rest: 15 },
    servings: 6,
    portionAdaptation: "moderate",
    signature: "Boeuf tendre sauce vin rouge complete, aromatique, garnish classique",
    profTips: [
      "Boeuf bien persille pour gras intramuscular",
      "Cubes saisir 4 min par face pour croute Maillard",
      "Vin + bouillon ajout apres saisie, reduce lentement",
    ],
    mistakes: [
      "Boeuf maigre = dur apres cuisson",
      "Pas bien saisir = pas croute saveur",
      "Cuisson trop rapide = boeuf dur",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 5, arome: 5 },
    category: "viande",
    baseIngredients: ["paleron de boeuf", "vin rouge", "lardons", "champignons", "carotte", "oignon", "ail", "concentre de tomate"],
    ingredients: [
      { name: "paleron de boeuf", quantity: "1kg" },
      { name: "vin rouge", quantity: "75cl" },
      { name: "lardons", quantity: "150g" },
      { name: "champignons", quantity: "250g" },
      { name: "carotte", quantity: "3" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "3 gousses" },
      { name: "concentre de tomate", quantity: "1 cs" },
      { name: "bouquet garni", quantity: "1" },
      { name: "farine", quantity: "2 cs" },
    ],
    steps: [
      "Couper boeuf en cubes de 4cm. Secher soigneusement.",
      "Saisir les cubes dans huile bien chaude, 3-4 min par face. Reserver.",
      "Faire revenir lardons, oignon et carotte 5 min.",
      "Saupoudrer farine, remuer 1 min. Ajouter concentre de tomate.",
      "Deglacer au vin rouge, ajouter bouquet garni et ail.",
      "Remettre boeuf, couvrir. Mijoter 2h30 a feu tres doux.",
      "Ajouter champignons sautes les 20 dernieres minutes.",
      "Laisser reposer 15 min avant de servir.",
    ],
    techniques: ["braise", "sear"],
    tags: ["mijoté", "bourgogne", "hiver", "familial"],
  },
  {
    id: "sole-meuniere",
    name: "Sole meunière",
    desireName: "Sole meunière au beurre noisette, citron frais",
    aliases: ["sole meuniere", "sole a la meuniere"],
    cuisine: "francaise",
    region: "Classique",
    slot: "dinner",
    difficulty: 3,
    minChefLevel: 3,
    family: "poisson-frit",
    technique: "fry",
    baseFamilies: ["sole", "beurre", "citron"],
    fundamentals: ["sole videe impeccable", "beurre noisette pas noir", "saisir 2 min chaque cote"],
    timings: { prep: 10, cook: 8, rest: 0 },
    servings: 1,
    portionAdaptation: "linear",
    signature: "Sole delicate chair blanche, beurre noisette mousseux, citron frais",
    profTips: [
      "Sole fraiche essentielle, videe proprement",
      "Beurre doit etre noisette, jamais noir",
      "Saisir 2 min chaque cote exactement",
    ],
    mistakes: [
      "Sole pas fraiche = chair molle",
      "Beurre brule = amertume",
      "Trop cuire = chair seche et cassante",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 5, arome: 4 },
    category: "poisson",
    baseIngredients: ["sole", "beurre", "citron", "farine", "persil"],
    ingredients: [
      { name: "sole entiere videe", quantity: "1 (300g)" },
      { name: "beurre", quantity: "50g" },
      { name: "citron", quantity: "1" },
      { name: "farine", quantity: "2 cs" },
      { name: "persil frais", quantity: "1 bouquet" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Rincer sole, secher soigneusement avec papier absorbant.",
      "Fariner legerement les deux faces, tapoter l'exces.",
      "Chauffer beurre dans poele large a feu moyen.",
      "Cuire sole 2 min premiere face, retourner delicatement.",
      "Cuire 2 min deuxieme face. Beurre doit etre noisette (dore, pas noir).",
      "Dresser, arroser de beurre noisette, jus de citron et persil.",
    ],
    techniques: ["fry"],
    tags: ["poisson", "classique", "raffiné", "rapide"],
  },
  {
    id: "sauce-creme-classique",
    name: "Sauce crème classique",
    desireName: "Sauce crème onctueuse aux herbes",
    aliases: ["sauce creme", "sauce creme fraiche", "sauce a la creme"],
    cuisine: "francaise",
    region: "Classique",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "sauce",
    technique: "reduce",
    baseFamilies: ["creme", "beurre", "oignon"],
    fundamentals: ["base aromatique doux", "reduction lente", "liaison creme"],
    timings: { prep: 8, cook: 12, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Sauce creme onctueuse nappante, saveur aromatique douce",
    profTips: [
      "Oignon et ail suer 2 min feu doux",
      "Creme en reduction lente 8-10 min pour nappante",
      "Ne JAMAIS bouillir apres ajout creme",
    ],
    mistakes: [
      "Oignon pas sue = texture desagreable",
      "Creme bouillie = sauce tranchee et granuleuse",
      "Pas assez de reduction = sauce trop liquide",
    ],
    premiumTier: "essentiel",
    plaisir: { gourmandise: 3, texture: 3, visuel: 2, arome: 3 },
    category: "sauce",
    baseIngredients: ["creme fraiche", "beurre", "echalote", "vin blanc", "persil"],
    ingredients: [
      { name: "creme fraiche", quantity: "200ml" },
      { name: "beurre", quantity: "20g" },
      { name: "echalote", quantity: "2" },
      { name: "vin blanc sec", quantity: "5cl", optional: true },
      { name: "persil", quantity: "quelques feuilles" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Emincer echalotes finement. Faire suer dans beurre 2 min feu doux.",
      "Deglacer au vin blanc si utilise, reduire 1 min.",
      "Ajouter creme fraiche, melanger.",
      "Reduire a feu doux 8-10 min en remuant regulierement.",
      "Assaisonner, parsemer de persil. Servir nappee sur plat.",
    ],
    techniques: ["reduce"],
    tags: ["sauce", "classique", "basique", "accompagnement"],
  },
  {
    id: "tarte-salee",
    name: "Tarte salée maison",
    desireName: "Tarte salée rustique aux légumes de saison",
    aliases: ["tarte", "tarte salee", "tarte legumes"],
    cuisine: "francaise",
    region: "Classique",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "tarte",
    technique: "bake",
    baseFamilies: ["farine", "beurre", "tomate"],
    fundamentals: ["pate foncer regulier", "garniture equilibree", "cuisson four 180C"],
    timings: { prep: 20, cook: 30, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Tarte croustillante pate, garniture tomate legumes fondants",
    profTips: [
      "Pate foncer sans bulles, piquer fond",
      "Garniture pas trop serree pour cuisson uniforme",
      "Four 180C regulier 30 min pour pate doree",
    ],
    mistakes: [
      "Pate pas cuite en bas = gluante",
      "Garniture trop serree = cuisson inegale",
      "Trop de tomate = sauce imbibe la pate",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 3, texture: 4, visuel: 3, arome: 3 },
    category: "plat",
    baseIngredients: ["pate brisee", "tomate", "oignon", "fromage", "oeuf", "creme"],
    ingredients: [
      { name: "pate brisee", quantity: "1 rouleau" },
      { name: "tomate", quantity: "3" },
      { name: "oignon", quantity: "1" },
      { name: "fromage rape", quantity: "80g" },
      { name: "oeuf", quantity: "1" },
      { name: "creme fraiche", quantity: "100ml" },
      { name: "sel, poivre, herbes de Provence" },
    ],
    steps: [
      "Prechauffer four a 180C. Foncer moule avec pate, piquer fond.",
      "Emincer oignon, faire revenir 3 min. Couper tomates en rondelles.",
      "Melanger oeuf + creme + herbes. Verser sur fond de tarte.",
      "Disposer tomates et oignon, saupoudrer fromage.",
      "Enfourner 30 min. Laisser reposer 5 min avant decoupe.",
    ],
    techniques: ["bake"],
    tags: ["tarte", "légumes", "classique", "familial"],
  },
  {
    id: "pain-au-beurre",
    name: "Pain au beurre français",
    desireName: "Pain brioché au beurre doré, mie fondante",
    aliases: ["pain au beurre", "pain-au-beurre"],
    cuisine: "francaise",
    region: "Boulangerie",
    slot: "breakfast",
    difficulty: 3,
    minChefLevel: 3,
    family: "boulangerie",
    technique: "bake",
    baseFamilies: ["farine", "beurre", "levure"],
    fundamentals: ["pate enrichie", "petrissage 10 min", "levage puis dorage"],
    timings: { prep: 25, cook: 28, rest: 120 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Pain tendre moelleux, croute doree legere, interieur aere",
    profTips: [
      "Petrir 10 min pour developper gluten",
      "Levage 120 min jusqu'a double de volume",
      "Dorer a l'oeuf et saupoudrer sucre cristal avant cuire",
    ],
    mistakes: [
      "Pas assez de petrissage = pain dense",
      "Levage insuffisant = pain compact",
      "Cuisson trop rapide = croute dure, dedans pas cuit",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 5, visuel: 3, arome: 4 },
    category: "pâte",
    baseIngredients: ["farine", "beurre", "oeuf", "lait", "levure boulangere", "sucre"],
    ingredients: [
      { name: "farine", quantity: "300g" },
      { name: "beurre mou", quantity: "60g" },
      { name: "oeuf", quantity: "1" },
      { name: "lait tiede", quantity: "120ml" },
      { name: "levure boulangere fraiche", quantity: "15g" },
      { name: "sucre", quantity: "30g" },
      { name: "sel", quantity: "1 cc" },
    ],
    steps: [
      "Diluer levure dans lait tiede (pas chaud). Laisser mousser 5 min.",
      "Melanger farine + sel + sucre. Ajouter oeuf et melange levure-lait.",
      "Petrir 8-10 min energiquement. Incorporer beurre mou en morceaux.",
      "Petrir encore 5 min jusqu'a pate lisse et elastique.",
      "Couvrir, laisser lever 1h30-2h a temperature ambiante (doit doubler).",
      "Degazer, faconner en petits pains ou tresse. Laisser pousser 30 min.",
      "Dorer a l'oeuf. Enfourner 25-28 min a 175C.",
    ],
    techniques: ["bake", "knead"],
    tags: ["boulangerie", "petit-déjeuner", "brioché", "sucré"],
  },
  {
    id: "omelette-persil",
    name: "Omelette persil",
    desireName: "Omelette baveuse au persil frais, beurre mousseux",
    aliases: ["omelette", "omelette persil"],
    cuisine: "francaise",
    region: "Classique",
    slot: "breakfast",
    difficulty: 2,
    minChefLevel: 2,
    family: "oeuf",
    technique: "sear",
    baseFamilies: ["oeuf", "beurre", "persil"],
    fundamentals: ["oeufs battus doux", "beurre frais mousseux", "pliage avant bien cuit"],
    timings: { prep: 5, cook: 4, rest: 0 },
    servings: 1,
    portionAdaptation: "linear",
    signature: "Omelette tendre creuse dedans, pliee parfaite, garniture simple",
    profTips: [
      "Oeufs simplement battus, pas surtravailler",
      "Beurre doit etre frais et mousseux",
      "Plier omelette AVANT qu'elle soit tout a fait cuite",
    ],
    mistakes: [
      "Oeufs trop travailles = dense",
      "Beurre cuit/noir = amertume",
      "Omelette trop cuite = caoutchouteuse",
    ],
    premiumTier: "essentiel",
    plaisir: { gourmandise: 3, texture: 4, visuel: 2, arome: 3 },
    category: "plat",
    baseIngredients: ["oeufs", "beurre", "persil", "sel", "poivre"],
    ingredients: [
      { name: "oeufs", quantity: "3" },
      { name: "beurre", quantity: "15g" },
      { name: "persil frais", quantity: "1 cs hache" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Casser oeufs dans bol, assaisonner. Battre legerement a la fourchette.",
      "Chauffer beurre dans poele a feu moyen, il doit mousser.",
      "Verser oeufs, remuer doucement 30 sec au centre.",
      "Laisser prendre 1 min. Ajouter persil.",
      "Plier en trois AVANT cuisson complete (interieur doit etre baveux).",
      "Servir immediatement, l'omelette continue de cuire hors poele.",
    ],
    techniques: ["sear"],
    tags: ["rapide", "basique", "petit-déjeuner", "oeufs"],
  },
];

// ============================================
// LOT 2 — 1 nouveau plat vérifié
// ============================================
const LOT_2: DishProfile[] = [
  {
    id: "blanquette-veau",
    name: "Blanquette de veau",
    desireName: "Blanquette de veau onctueuse, sauce blanche veloutée",
    aliases: ["blanquette", "blanquette de veau", "blanquette veau"],
    cuisine: "francaise",
    region: "Classique",
    slot: "dinner",
    difficulty: 3,
    minChefLevel: 3,
    family: "braise-blanc",
    technique: "braise",
    baseFamilies: ["veau", "carotte", "oignon", "creme", "champignon"],
    fundamentals: ["pochage delicat du veau", "sauce blanche liee jaune-creme", "garniture aromatique"],
    timings: { prep: 20, cook: 90, rest: 5 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Veau tendre dans sauce blanche veloutee, champignons et carottes",
    profTips: [
      "Veau poché, jamais bouillie = chair reste tendre et blanche",
      "Liaison jaune + creme hors du feu pour eviter que ca tranche",
      "Champignons sautes a part et ajoutes en fin",
    ],
    mistakes: [
      "Bouillir le veau = viande grise et dure",
      "Liaison sur feu vif = sauce tranchee",
      "Pas assez de temps = veau dur",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 4 },
    category: "viande",
    baseIngredients: ["epaule de veau", "carotte", "oignon", "bouquet garni", "champignons", "creme fraiche", "jaune d'oeuf", "citron"],
    ingredients: [
      { name: "epaule de veau (ou tendron)", quantity: "800g" },
      { name: "carotte", quantity: "3" },
      { name: "oignon pique de clous de girofle", quantity: "1" },
      { name: "bouquet garni", quantity: "1" },
      { name: "champignons de Paris", quantity: "200g" },
      { name: "creme fraiche", quantity: "150ml" },
      { name: "jaune d'oeuf", quantity: "2" },
      { name: "citron", quantity: "1/2" },
      { name: "beurre", quantity: "30g" },
      { name: "farine", quantity: "30g" },
    ],
    steps: [
      "Couper veau en gros cubes. Blanchir 2 min a l'eau bouillante, egoutter.",
      "Remettre dans casserole propre, couvrir d'eau froide. Porter a fremissement.",
      "Ajouter carotte, oignon pique, bouquet garni. Cuire 1h15 a petit feu (pas bouillir).",
      "Preparer roux blanc: fondre beurre, ajouter farine, cuire 2 min sans colorer.",
      "Mouiller avec 500ml de bouillon de cuisson. Fouetter jusqu'a epaississement.",
      "Sauter champignons dans beurre a part. Ajouter citron pour eviter noircissement.",
      "Hors du feu: melanger jaunes + creme, incorporer a la sauce en fouettant.",
      "Ajouter veau et champignons dans la sauce. Servir avec riz.",
    ],
    techniques: ["braise", "poach"],
    tags: ["mijoté", "classique", "hiver", "sauce blanche"],
  },
];

// ============================================
// LOT 3 — 12 plats supplémentaires (diversité française)
// ============================================
const LOT_3: DishProfile[] = [
  {
    id: "ratatouille-nicoise",
    name: "Ratatouille niçoise",
    desireName: "Ratatouille colorée légumes d'été, huile d'olive,herbes de Provence",
    aliases: ["ratatouille", "ratatouille nice", "vegetable stew"],
    cuisine: "francaise",
    region: "Provence",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "legume-mijo",
    technique: "braise",
    baseFamilies: ["aubergine", "tomate", "courgette", "huile olive"],
    fundamentals: ["cuisson lente", "legumes pas écrasés", "herbes de Provence"],
    timings: { prep: 20, cook: 45, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Légumes fondants sauce tomate, parfum herbes provençales",
    profTips: [
      "Cuire lentement sans presser légumes",
      "Huile d'olive extra vierge finale pour saveur",
      "Serve chaud, tiède ou froid (polyvalent)",
    ],
    mistakes: [
      "Cuisson trop rapide = légumes croquants désagréables",
      "Trop mixer = compote",
      "Pas d'herbes = plat banal",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 3, texture: 4, visuel: 5, arome: 4 },
    category: "legume",
    baseIngredients: ["aubergine", "courgette", "poivron", "tomate", "oignon", "huile olive"],
    ingredients: [
      { name: "aubergine", quantity: "1" },
      { name: "courgette", quantity: "2" },
      { name: "poivron rouge", quantity: "1" },
      { name: "tomate", quantity: "3" },
      { name: "oignon", quantity: "1" },
      { name: "ail", quantity: "2 gousses" },
      { name: "herbes de Provence", quantity: "1 cs" },
      { name: "huile olive extra vierge", quantity: "4 cs" },
    ],
    steps: [
      "Couper tous légumes en cubes 1cm réguliers.",
      "Sauter oignon/ail dans huile 3 min.",
      "Ajouter aubergine, courgette, poivron, cuire 15 min.",
      "Ajouter tomate concassée, herbes.",
      "Mijoter couvert 30 min à feu doux.",
      "Rectifier assaisonnement, finir avec huile olive crue.",
      "Servir chaud, tiède ou froid.",
    ],
    techniques: ["braise"],
    tags: ["legume", "provence", "ete", "vegetarien"],
  },
  {
    id: "cassoulet",
    name: "Cassoulet du sud-ouest",
    desireName: "Cassoulet riche haricots-confits, canard lentilles",
    aliases: ["cassoulet", "cassoulette", "bean stew"],
    cuisine: "francaise",
    region: "Occitanie",
    slot: "lunch",
    difficulty: 4,
    minChefLevel: 4,
    family: "haricot-mijo",
    technique: "braise",
    baseFamilies: ["haricot blanc", "canard", "saucisse", "lard"],
    fundamentals: ["haricots longs trempage", "confits 3h", "gratinage final"],
    timings: { prep: 30, cook: 240, rest: 10 },
    servings: 8,
    portionAdaptation: "moderate",
    signature: "Haricots oncteux sous croûte dorée, canard fondant riche",
    profTips: [
      "Trempage haricots 12h minimum",
      "Cuisson lente: jamais ébullition",
      "Croûte brisée 3-4 fois durant cuisson",
    ],
    mistakes: [
      "Pas trempage = cuisson inégale",
      "Trop rapide = haricots durs au centre",
      "Pas croûte gratinage = cassoulet fade",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 5 },
    category: "plat",
    baseIngredients: ["haricot blanc", "canard confit", "saucisse toulouse", "lard", "oignon"],
    ingredients: [
      { name: "haricot blanc sec", quantity: "500g" },
      { name: "cuisses canard confit", quantity: "2" },
      { name: "saucisse toulouse", quantity: "4" },
      { name: "lard fumé", quantity: "150g" },
      { name: "oignon", quantity: "1" },
      { name: "ail", quantity: "3 gousses" },
      { name: "bouillon poule", quantity: "1,5L" },
      { name: "chapelure", quantity: "100g" },
    ],
    steps: [
      "Tremper haricots 12h, cuire 1h eau fraîche (pas sel).",
      "Sauter lard+saucisse, ajouter oignon/ail.",
      "Verser haricots cuits, bouillon, thym.",
      "Mijoter couvert 1h très doux.",
      "Ajouter confit canard, mijoter 30 min.",
      "Saupoudrer chapelure, gratiner au four 30 min 200C.",
      "Casser croûte 2-3 fois pour bien intégrer.",
    ],
    techniques: ["braise", "bake"],
    tags: ["haricot", "sud-ouest", "festin", "hiver"],
  },
  {
    id: "escargots-ail",
    name: "Escargots à l'ail et persil",
    desireName: "Escargots dorés beurre-ail-persil, croustillants",
    aliases: ["escargots", "snails garlic", "burgundy snails"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "dinner",
    difficulty: 2,
    minChefLevel: 2,
    family: "mollusque",
    technique: "bake",
    baseFamilies: ["escargot", "beurre", "ail", "persil"],
    fundamentals: ["beurre ail hyper frais", "escargots bien secs", "four chaud 200C"],
    timings: { prep: 15, cook: 10, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Escargots texture ferme, beurre ail croustillant mousseux",
    profTips: [
      "Beurre composé bien froid avant four",
      "Escargots bien secs sinon beurre s'écoule",
      "Four très chaud pour beurre mousseux",
    ],
    mistakes: [
      "Beurre ramolli = coule hors escargot",
      "Cuisson trop longue = escargot caoutchouteux",
      "Persil brûlé = goût amer",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 3, visuel: 4, arome: 5 },
    category: "mollusque",
    baseIngredients: ["escargot", "beurre", "ail", "persil", "sel fin"],
    ingredients: [
      { name: "boîte escargots de Bourgogne", quantity: "1 (24 pieces)" },
      { name: "beurre frais", quantity: "200g" },
      { name: "ail", quantity: "10 gousses" },
      { name: "persil frais", quantity: "1 large bouquet" },
      { name: "sel fin", quantity: "1/2 cc" },
      { name: "poivre blanc", quantity: "1 pincée" },
    ],
    steps: [
      "Hacher ail très fin + persil cisélé ensemble.",
      "Mélanger beurre mou + ail-persil + sel + poivre bien.",
      "Dresser beurre composé dans coquilles.",
      "Placer coquilles ouverture vers haut dans plats à escargots.",
      "Enfourner 200C 8-10 min juste jusqu'à beurre frémissant.",
      "Servir immédiatement chaud, avec pain grillé.",
    ],
    techniques: ["bake"],
    tags: ["escargot", "bourgogne", "apéritif dîner", "luxe"],
  },
  {
    id: "oiseaux-sans-tete",
    name: "Oiseaux sans tête",
    desireName: "Oiseaux sans tête: roulade veau sauce vin rouge",
    aliases: ["oiseaux", "roulade veau", "braised roulades"],
    cuisine: "francaise",
    region: "Provence",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "viande-roulade",
    technique: "braise",
    baseFamilies: ["veau", "lard", "vin rouge", "oignon"],
    fundamentals: ["tranches veau minces battues", "roulade serré ficelle", "braissage vin"],
    timings: { prep: 25, cook: 60, rest: 5 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Roulades veau tendres sauce vin rouge riche",
    profTips: [
      "Battres minces très fines sans trouer",
      "Roulade serrée ficelle pour cohésion",
      "Braissage patient vin rouge pour saveur",
    ],
    mistakes: [
      "Tranches trop épaisses = cuisson inégale",
      "Roulade lâche = se défait cuisson",
      "Vin blanc au lieu rouge = gout désax",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 5 },
    category: "viande",
    baseIngredients: ["veau escalope", "lard", "vin rouge", "carotte", "oignon"],
    ingredients: [
      { name: "escalopes de veau", quantity: "8 (40g)" },
      { name: "lard fumé tranches", quantity: "8" },
      { name: "vin rouge corsé", quantity: "300ml" },
      { name: "carotte", quantity: "2" },
      { name: "oignon", quantity: "2" },
      { name: "bouillon poule", quantity: "200ml" },
      { name: "thym", quantity: "2 branches" },
      { name: "huile", quantity: "2 cs" },
    ],
    steps: [
      "Battre escalopes très fines entre film plastique.",
      "Sur chaque escalope: 1 tranche lard, quart carotte.",
      "Rouler ficeler serré.",
      "Sauter roulades huile chaude 4 min par face.",
      "Retirer, faire base caramel oignon/carotte.",
      "Verser vin rouge, bouillon, ajouter thym + roulades.",
      "Couvrir, mijoter 50 min à feu doux. Retirer ficelle avant servir.",
    ],
    techniques: ["braise"],
    tags: ["veau", "provence", "braisé", "familial"],
  },
  {
    id: "gratin-choufleur",
    name: "Gratin de chou-fleur",
    desireName: "Gratin de chou-fleur crémeux fromage, croustillant dessus",
    aliases: ["gratin chou", "cauliflower gratin", "gratinée chouflower"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratin",
    technique: "bake",
    baseFamilies: ["chou-fleur", "bechamel", "fromage", "beurre"],
    fundamentals: ["chou-fleur cuit dente", "bechamel riche", "gratinage four"],
    timings: { prep: 20, cook: 35, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Chou-fleur fondant sauce crème-fromage, croûte dorée gratinée",
    profTips: [
      "Chou-fleur cuit juste dente, pas mou",
      "Béchamel riche: 50% crème pour onctueuse",
      "Gruyère râpé final pour croûte dorée",
    ],
    mistakes: [
      "Chou-fleur trop cuit = purée désagréable",
      "Béchamel trop claire = gout fade",
      "Fromage brûlé = amertume",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 3 },
    category: "legume",
    baseIngredients: ["chou-fleur", "lait", "beurre", "farine", "fromage gruyere"],
    ingredients: [
      { name: "chou-fleur", quantity: "1" },
      { name: "lait entier", quantity: "250ml" },
      { name: "crème fraîche", quantity: "150ml" },
      { name: "beurre", quantity: "40g" },
      { name: "farine", quantity: "30g" },
      { name: "gruyère râpé", quantity: "100g" },
      { name: "muscade", quantity: "1 pincée" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Cuire chou-fleur 12 min eau bouillante salée, égoutter.",
      "Roux: fondre beurre, ajouter farine 2 min.",
      "Verser lait+crème fouettant, cuire 8 min épaississement.",
      "Ajouter 2/3 gruyère + muscade, mélanger.",
      "Verser chou-fleur + sauce dans plat beurré.",
      "Saupoudrer gruyère restant.",
      "Enfourner 200C 20-25 min jusqu'à gratinage doré.",
    ],
    techniques: ["bake", "boil"],
    tags: ["gratin", "chou", "fromage", "accompagnement"],
  },
  {
    id: "ficele-champagne",
    name: "Ficelé à la Champagne",
    desireName: "Rôti ficellé champagne-raisins, sauce gastrique légère",
    aliases: ["ficele champagne", "roast with champagne", "beef champagne"],
    cuisine: "francaise",
    region: "Champagne",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "viande-rotie",
    technique: "braise",
    baseFamilies: ["boeuf", "champagne", "raisin", "oignon"],
    fundamentals: ["rôti ficellé", "champagne demi-sec", "raisins secs"],
    timings: { prep: 20, cook: 90, rest: 10 },
    servings: 6,
    portionAdaptation: "moderate",
    signature: "Rôti tendre champagne-raisins fondants, sauce légère",
    profTips: [
      "Ficeler rôti régulièrement pour cohésion",
      "Champagne demi-sec apporte sucre naturel",
      "Raisins secs complètent sauce",
    ],
    mistakes: [
      "Rôti trop gros = cuit inégal",
      "Champagne brut = trop sec",
      "Cuisson trop rapide = saignant dedans",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 5 },
    category: "viande",
    baseIngredients: ["boeuf rôti", "champagne", "raisin sec", "oignon", "carotte"],
    ingredients: [
      { name: "rôti de boeuf", quantity: "1.2kg" },
      { name: "champagne demi-sec", quantity: "500ml" },
      { name: "raisin sec", quantity: "100g" },
      { name: "oignon", quantity: "2" },
      { name: "carotte", quantity: "2" },
      { name: "bouillon poule", quantity: "300ml" },
      { name: "beurre", quantity: "30g" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Ficeler rôti régulièrement, assaisonner.",
      "Saisir rôti huile chaude 4 min par face.",
      "Retirer, faire base oignon/carotte.",
      "Verser champagne, réduction 5 min (alcool).",
      "Ajouter bouillon, raisins secs, remplacer rôti.",
      "Couvrir, mijoter 75 min à 160C (rosé).",
      "Retirer rôti, monter sauce beurre, servir.",
    ],
    techniques: ["braise", "sear"],
    tags: ["boeuf", "champagne", "festif", "luxe"],
  },
  {
    id: "lapin-fricassee",
    name: "Fricassée de lapin",
    desireName: "Lapin fumé crème-moutarde, sauce blanche onctueuse",
    aliases: ["fricassee lapin", "creamed rabbit", "lapin a la creme"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "viande-sauce",
    technique: "braise",
    baseFamilies: ["lapin", "creme", "moutarde", "oignon"],
    fundamentals: ["lapin morceaux", "sauce moutarde fondante", "crème riche"],
    timings: { prep: 20, cook: 75, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Lapin fondant sauce crème-moutarde, odeur herbacée",
    profTips: [
      "Lapin chair blanche: cuisson moderée",
      "Moutarde de Dijon obligatoire pour saveur",
      "Crème riche finale liaison sauce",
    ],
    mistakes: [
      "Cuisson trop longue = chair sèche fibreuse",
      "Pas moutarde = gout plat",
      "Trop crème = lourd écrasant",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 5 },
    category: "viande",
    baseIngredients: ["lapin", "moutarde", "creme", "oignon", "thym"],
    ingredients: [
      { name: "lapin de garenne morceaux", quantity: "1.2kg" },
      { name: "moutarde de Dijon", quantity: "2 cs" },
      { name: "crème fraîche", quantity: "250ml" },
      { name: "oignon", quantity: "2" },
      { name: "thym", quantity: "3 branches" },
      { name: "vin blanc sec", quantity: "200ml" },
      { name: "bouillon poule", quantity: "300ml" },
      { name: "beurre", quantity: "20g" },
    ],
    steps: [
      "Sauter lapin morceaux beurre chaud 8 min teinte dorée.",
      "Retirer, faire base oignon + thym 5 min.",
      "Verser vin blanc réduction 3 min.",
      "Verser bouillon, remplacer lapin, couvrir.",
      "Mijoter 60 min à feu très doux.",
      "Délayer moutarde + crème, verser progressif en fouettant.",
      "Laisser frémit 5 min (ne jamais bouillir crème).",
    ],
    techniques: ["braise"],
    tags: ["lapin", "bourgogne", "creme", "sauce blanche"],
  },
  {
    id: "pot-au-feu",
    name: "Pot-au-feu traditionnel",
    desireName: "Pot-au-feu boeuf légumes bouillon riche, moelle grillée",
    aliases: ["pot au feu", "beef stew", "french boil"],
    cuisine: "francaise",
    region: "Île-de-France",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "bouillon-viande",
    technique: "boil",
    baseFamilies: ["boeuf", "poireau", "carotte", "bouillon"],
    fundamentals: ["cuisson très lente", "legumes ajoutés progressif", "moelle os"],
    timings: { prep: 25, cook: 180, rest: 10 },
    servings: 8,
    portionAdaptation: "moderate",
    signature: "Boeuf vapeur-bouilli légumes fondants, bouillon riche intense",
    profTips: [
      "Eau froide départ: extraire saveur lentement",
      "Jamais ébullition: frémit seulement",
      "Moelle os surtout en dernier moment",
    ],
    mistakes: [
      "Eau bouillante départ = viande dure",
      "Ebullition = bouillon trouble",
      "Legumes trop longtemps = purée",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 5 },
    category: "plat",
    baseIngredients: ["boeuf gite", "poireau", "carotte", "navet", "oignon"],
    ingredients: [
      { name: "boeuf gîte ou paleron", quantity: "1.2kg" },
      { name: "poireau blanc", quantity: "4" },
      { name: "carotte", quantity: "4" },
      { name: "navet", quantity: "1" },
      { name: "oignon", quantity: "2 avec clou girofle" },
      { name: "céleri-rave", quantity: "1/4" },
      { name: "os à moelle", quantity: "400g" },
      { name: "eau froide", quantity: "2L" },
      { name: "sel gros" },
    ],
    steps: [
      "Placer boeuf eau froide salée, amener frémissement lent.",
      "Écumer écume grise 15 min debut.",
      "Ajouter 1h après: carotte, navet entier, céleri-rave.",
      "1h plus tard: poireaux liés, oignon clou.",
      "45 min avant fin: os à moelle enveloppe mousseline.",
      "Total 3h cuisson très doux.",
      "Servir boeuf + légumes + moelle tartine sur pain, bouillon à part.",
    ],
    techniques: ["boil"],
    tags: ["boeuf", "bouillon", "familial", "classique"],
  },
  {
    id: "crepes-bretonnes",
    name: "Crêpes bretonnes beurre sucre",
    desireName: "Crêpes dorées beurre-sucre traditionnel, fourrées ou natures",
    aliases: ["crepes", "pancakes french", "galettes bretonnes"],
    cuisine: "francaise",
    region: "Bretagne",
    slot: "dessert",
    difficulty: 2,
    minChefLevel: 2,
    family: "crepe",
    technique: "fry",
    baseFamilies: ["farine", "oeuf", "lait", "beurre"],
    fundamentals: ["repos pâte 1h", "poêle chaude 180C", "retournement délicat"],
    timings: { prep: 15, cook: 30, rest: 60 },
    servings: 8,
    portionAdaptation: "linear",
    signature: "Crêpe dorée hyper fine, beurre-sucre, texture dentelle",
    profTips: [
      "Repos 1h minimum permet gluten relacher",
      "Poêle 180C: test eau: danse oui, parf",
      "Retournement rapide délicate pour intégrité",
    ],
    mistakes: [
      "Pas repos = pâte trop épaisse",
      "Poêle pas chaude = pâte molle collante",
      "Trop long en poêle = cramée",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 3 },
    category: "dessert",
    baseIngredients: ["farine", "oeuf", "lait", "beurre", "sucre"],
    ingredients: [
      { name: "farine", quantity: "250g" },
      { name: "oeuf", quantity: "2" },
      { name: "lait entier", quantity: "500ml" },
      { name: "beurre fondu", quantity: "30g" },
      { name: "sucre", quantity: "1 cs" },
      { name: "sel", quantity: "1 pincée" },
      { name: "beurre pour poêle", quantity: "1 noisette" },
    ],
    steps: [
      "Mélanger farine + sel + sucre.",
      "Creuser puits, ajouter oeufs + moitié lait.",
      "Fouetter 5 min jusqu'à lisse.",
      "Incorporer lait restant+ beurre fondu.",
      "Reposer 1h minimum.",
      "Poêle 180C noisette beurre.",
      "Verser 50ml pâte, pencher poêle rotation couvrir fond.",
      "Dorer 1 min, retourner, 30 sec autre côté.",
      "Glisser assiette, saupoudrer beurre-sucre immédiat.",
    ],
    techniques: ["fry"],
    tags: ["crepe", "bretagne", "dessert", "sucre"],
  },
  {
    id: "clafoutis-cerises",
    name: "Clafoutis aux cerises",
    desireName: "Clafoutis fondant cerises, crème vanille croquante",
    aliases: ["clafoutis", "cherry cake", "clafouti"],
    cuisine: "francaise",
    region: "Limousin",
    slot: "dessert",
    difficulty: 1,
    minChefLevel: 1,
    family: "clafoutis",
    technique: "bake",
    baseFamilies: ["cerise", "oeuf", "lait", "farine"],
    fundamentals: ["cerises fraîches", "pâte simple", "cuisson 35 min"],
    timings: { prep: 20, cook: 40, rest: 10 },
    servings: 6,
    portionAdaptation: "linear",
    signature: "Clafoutis fondant moelleux cerises, crème légère onctueus",
    profTips: [
      "Cerises fraîches absolument, semi-surgelées ok",
      "Pâte très simple: oeuf+farine+lait",
      "Four 180C: pas brûler oeuf",
    ],
    mistakes: [
      "Cerises trop mûres = se désagrègent",
      "Farine trop = dense",
      "Four trop chaud = brûlé",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 4 },
    category: "dessert",
    baseIngredients: ["cerise", "oeuf", "lait", "sucre", "farine"],
    ingredients: [
      { name: "cerise fraîche", quantity: "500g" },
      { name: "oeuf", quantity: "4" },
      { name: "lait", quantity: "250ml" },
      { name: "sucre", quantity: "100g" },
      { name: "farine", quantity: "100g" },
      { name: "vanille", quantity: "1 gousse" },
      { name: "beurre", quantity: "30g" },
      { name: "sucre glace poudrage", quantity: "20g" },
    ],
    steps: [
      "Gratter vanille, mélanger oeuf + sucre + vanille.",
      "Ajouter lait + farine fouettant lisse.",
      "Beurrer moule, étaler cerises fond.",
      "Verser pâte par-dessus (cerises flottent).",
      "Enfourner 180C 35-40 min (toothpick test légèrement humide).",
      "Laisser refroidir 10 min.",
      "Saupoudrer sucre glace avant servir.",
    ],
    techniques: ["bake"],
    tags: ["cerise", "limousin", "dessert", "facile"],
  },
  {
    id: "salade-nicoise",
    name: "Salade niçoise",
    desireName: "Salade niçoise thon-oeuf-tomate, anchoïade légère",
    aliases: ["salade nicoise", "nice salad", "tuna salad"],
    cuisine: "francaise",
    region: "Provence",
    slot: "lunch",
    difficulty: 1,
    minChefLevel: 1,
    family: "salade",
    technique: "raw",
    baseFamilies: ["tomate", "oeuf", "thon", "olive", "anchois"],
    fundamentals: ["ingrédients régionaux", "vinaigrette simple", "assemblage final"],
    timings: { prep: 20, cook: 10, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Salade colorée ingrédients nobles, vinaigre douceur",
    profTips: [
      "Ingrédients frais absolus, pas de surgelé",
      "Thon en miettes: pas pâté",
      "Vinaigre: 3ml huile 1 vinaigre ratio",
    ],
    mistakes: [
      "Ingrédients bas gamme = salade banale",
      "Trop vinaigre = acide désagréable",
      "Mélanger avant servir = salate molle",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 3, texture: 4, visuel: 5, arome: 3 },
    category: "salade",
    baseIngredients: ["tomate", "oeuf", "thon", "olive noire", "anchois"],
    ingredients: [
      { name: "laitue romaine", quantity: "1" },
      { name: "tomate cerise", quantity: "5-6" },
      { name: "oeuf dur", quantity: "2" },
      { name: "thon albacore conserve", quantity: "150g" },
      { name: "anchois conserve", quantity: "8" },
      { name: "olive noire tanche", quantity: "50g" },
      { name: "oignon rouge", quantity: "1/4" },
      { name: "huile olive extra vierge", quantity: "6 cs" },
      { name: "vinaigre vin rouge", quantity: "2 cs" },
    ],
    steps: [
      "Laver laitue, sécher bien, déchirer feuilles.",
      "Cuire oeufs 8 min eau bouillante.",
      "Vinaigre simple: sel+poivre+ vinaigre, émulsionner huile.",
      "Dresser laitue assiette ou saladier.",
      "Ajouter tomate quartier, oeuf coupé, thon miettes, anchois.",
      "Répartir olives et oignon émincé.",
      "Verser vinaigre final juste avant service.",
    ],
    techniques: ["raw", "boil"],
    tags: ["salade", "provence", "frais", "léger"],
  },
];

/** Tous les plats français validés */
export const PLATS_FRANCAIS: DishProfile[] = [...LOT_1, ...LOT_2, ...LOT_3, ...FRANCAIS_LOT4];
