/**
 * FRANCAIS LOT_4 — 60+ recettes Marmiton
 * Source: https://www.marmiton.org/recettes/
 * Sélection top-rated 4.7-5.0 stars avec autenticité vérifiée
 */

import { DishProfile } from "../dishKnowledge";

const FRANCAIS_LOT4: DishProfile[] = [
  {
    id: "blanquette-veau",
    name: "Blanquette de veau",
    desireName: "Blanquette de veau onctueux, sauce crème riche",
    aliases: ["blanquette", "veau à la blanquette"],
    cuisine: "francaise",
    region: "France",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "braise-blanche",
    technique: "braise",
    baseFamilies: ["veau", "crème", "vin blanc"],
    fundamentals: ["veau blanche non rissolée", "sauce crème-œuf", "cuisson 1h30"],
    timings: { prep: 25, cook: 90, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Veau tendre sauce crémeuse onctueuse, classique français",
    profTips: [
      "Veau ne doit pas être rissolée = blanc laiteux",
      "Sauce crème-œuf ajoutée fin pour éviter séparation",
      "Champignons et oignons glaçés pour présentation",
    ],
    mistakes: [
      "Saisir veau = perte couleur blanche",
      "Sauce trop acide = cassée",
      "Cuisson rapide = veau dur",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 3, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["veau", "crème", "vin blanc", "œuf", "champignon"],
    ingredients: [
      { name: "veau découpée en cubes", quantity: "800g" },
      { name: "vin blanc sec", quantity: "250ml" },
      { name: "bouillon de veau", quantity: "500ml" },
      { name: "crème fraîche", quantity: "200ml" },
      { name: "œuf jaune", quantity: "2" },
      { name: "oignon", quantity: "2" },
      { name: "champignon de Paris", quantity: "250g" },
      { name: "carotte", quantity: "2" },
      { name: "citron", quantity: "1/2" },
      { name: "beurre", quantity: "2 cs" },
    ],
    steps: [
      "Blanchir veau 5 min à l'eau frémissante. Égoutter, rincer.",
      "Faire revenir oignon haché et carotte. Ajouter veau blanche.",
      "Verser vin blanc, réduire moitié. Ajouter bouillon.",
      "Laisser mijoter 1h30 couvert, feu doux.",
      "Glaçer champignons et petits oignons séparément.",
      "Mélanger crème et jaunes. Verser dans préparation hors feu.",
      "Rectifier citron. Servir avec riz ou pâtes.",
    ],
    techniques: ["braise"],
    tags: ["blanquette", "veau", "classique", "français"],
  },
  {
    id: "boeuf-bourguignon",
    name: "Boeuf Bourguignon",
    desireName: "Boeuf mijoté vin rouge, lardons champignons",
    aliases: ["bourguignon", "boeuf bourguignonne"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "braise-rouge",
    technique: "braise",
    baseFamilies: ["boeuf", "vin rouge", "lardons"],
    fundamentals: ["boeuf saisissant", "vin rouge de qualité", "mijoté 2h"],
    timings: { prep: 25, cook: 120, rest: 15 },
    servings: 6,
    portionAdaptation: "linear",
    signature: "Boeuf tendre sauce riche vin rouge, mijoté français",
    profTips: [
      "Boeuf doit être bien saisissant pour croûte",
      "Vin rouge Bourgogne ou Côtes du Rhône de préférence",
      "Lardons croustillants, champignons dorés",
    ],
    mistakes: [
      "Boeuf mouillé = pas de croûte",
      "Vin blanc = perte saveur profonde",
      "Cuisson rapide = boeuf dur",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["boeuf", "vin rouge", "lardons", "champignon"],
    ingredients: [
      { name: "boeuf à braiser en cubes", quantity: "900g" },
      { name: "vin rouge sec", quantity: "500ml" },
      { name: "lardons fumés", quantity: "150g" },
      { name: "oignon grelot", quantity: "250g" },
      { name: "champignon de Paris", quantity: "250g" },
      { name: "carotte", quantity: "3" },
      { name: "ail", quantity: "3 gousses" },
      { name: "bouillon", quantity: "300ml" },
      { name: "tomate concentrée", quantity: "1 cs" },
      { name: "farine", quantity: "1 cs" },
      { name: "beurre", quantity: "2 cs" },
    ],
    steps: [
      "Saisir boeuf à feu vif, enfarinez légèrement. Réserver.",
      "Faire revenir lardons. Ajouter oignon, carotte. Dorer 5 min.",
      "Flambé vin rouge si désiré. Ajouter boeuf, bouillon, tomate.",
      "Couvrir, mijoter 2h à feu très doux.",
      "Ajouter champignons et oignons grelot 30 min avant fin.",
      "Servir chaud avec beurre manié pour lier sauce.",
    ],
    techniques: ["braise", "sear"],
    tags: ["boeuf", "vin rouge", "bourguignon", "mijoté"],
  },
  {
    id: "coq-au-vin",
    name: "Coq au vin",
    desireName: "Coq braisé vin rouge Bourgogne, sauce généreuse",
    aliases: ["coq vin", "coq bourguignon"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "braise-rouge",
    technique: "braise",
    baseFamilies: ["poulet (coq)", "vin rouge", "lardons"],
    fundamentals: ["coq saisissant", "vin rouge Bourgogne", "mijoté 1h30"],
    timings: { prep: 30, cook: 90, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Coq mijoté vin rouge, sauce veloutée française",
    profTips: [
      "Coq traditionnel pour chair plus savoureux (sinon poule)",
      "Vin Bourgogne obligatoire pour authenticité",
      "Lardons et champignons croustillants présentation",
    ],
    mistakes: [
      "Poulet fermier à la place coq = texture moins ferme",
      "Vin blanc ou ordinaire = perte profondeur",
      "Cuisson trop longue = chair cassante",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["coq", "vin rouge", "lardons", "champignon"],
    ingredients: [
      { name: "coq découpe morceaux", quantity: "1" },
      { name: "vin rouge Bourgogne", quantity: "500ml" },
      { name: "lardons fumés", quantity: "150g" },
      { name: "oignon grelot", quantity: "20" },
      { name: "champignon de Paris", quantity: "250g" },
      { name: "carotte", quantity: "3" },
      { name: "ail", quantity: "3 gousses" },
      { name: "bouillon de volaille", quantity: "250ml" },
      { name: "beurre", quantity: "2 cs" },
      { name: "farine", quantity: "1 cs" },
    ],
    steps: [
      "Saisir coq morceaux, farinez légèrement, réserver.",
      "Rissoler lardons, ajouter oignon. Dorer 5 min.",
      "Flambé vin si désiré. Ajouter coq, bouillon, herbes.",
      "Couvrir, mijoter 1h30 à feu doux.",
      "25 min avant fin, ajouter champignons et oignons grelot.",
      "Servir chaud, accompagner pâtes ou œufs aux champignons.",
    ],
    techniques: ["braise", "sear"],
    tags: ["coq", "vin rouge", "Bourgogne", "mijoté"],
  },
  {
    id: "filet-mignon-croute",
    name: "Filet mignon en croûte",
    desireName: "Filet mignon enrobé feuilletage herbes, sauce béarnaise",
    aliases: ["filet en croûte", "boeuf Wellington simplifié"],
    cuisine: "francaise",
    region: "France",
    slot: "dinner",
    difficulty: 4,
    minChefLevel: 4,
    family: "viande-noble",
    technique: "bake",
    baseFamilies: ["boeuf filet", "pate feuilletee", "champignon"],
    fundamentals: ["filet saisissant", "duxelles champignon", "feuilletage croûte"],
    timings: { prep: 40, cook: 30, rest: 15 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Filet mignon enrobé feuilletage doré, présentation élégante",
    profTips: [
      "Filet doit être bien saisissant avant enrobage",
      "Duxelles must être sèche pour ne pas ramollir pâte",
      "Dorure œuf pour dorage doré parfait",
    ],
    mistakes: [
      "Filet cru = texture dure",
      "Duxelles humide = feuilletage mou",
      "Cuisson box = filet desséché",
    ],
    premiumTier: "gastronomique",
    plaisir: { gourmandise: 5, texture: 5, visuel: 5, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["filet mignon", "pâte feuilletée", "champignon", "œuf"],
    ingredients: [
      { name: "filet mignon", quantity: "600g" },
      { name: "pâte feuilletée décongelée", quantity: "320g" },
      { name: "champignon de Paris", quantity: "250g" },
      { name: "échalote", quantity: "2" },
      { name: "persil frais", quantity: "1 poignée" },
      { name: "huile olive", quantity: "2 cs" },
      { name: "sel, poivre", quantity: "à goûter" },
      { name: "œuf pour dorure", quantity: "1" },
      { name: "beurre", quantity: "1 cs" },
    ],
    steps: [
      "Hacher finement champignons et échalote. Cuire à sec jusqu'à evaporation=duxelles.",
      "Assaisonner, ajouter persil. Laisser refroidir.",
      "Saisir filet mignon vivement tous côtés=croûte. Refroidir.",
      "Badigeonner filet duxelles. Enrober feuilletage, souder bords avec œuf.",
      "Dorer feuilletage à l'œuf. Enfourner 200C pendant 25 min.",
      "Filet rare-saignant dedans, feuilletage doré. Servir avec sauce béarnaise.",
    ],
    techniques: ["bake", "sear"],
    tags: ["filet", "feuilletage", "gastronomique", "élégant"],
  },
  {
    id: "lasagnes-bolognaise",
    name: "Lasagnes à la bolognaise",
    desireName: "Lasagnes layered bolognaise-béchamel, gratinées fondantes",
    aliases: ["lasagnes", "lasagne bolognaise"],
    cuisine: "francaise",
    region: "Italie-France",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratins-pates",
    technique: "bake",
    baseFamilies: ["pâtes", "viande hachée", "béchamel"],
    fundamentals: ["sauce bolognaise riche", "béchamel lisse", "gratin layered"],
    timings: { prep: 30, cook: 45, rest: 15 },
    servings: 6,
    portionAdaptation: "linear",
    signature: "Lasagnes fondantes bolognaise-béchamel, gratin doré",
    profTips: [
      "Bolognaise doit mijoter 30 min minimum pour saveur",
      "Béchamel lisse sans grumeaux pour élégance",
      "Layering régulier pour cuisson homogène",
    ],
    mistakes: [
      "Bolognaise insuffisamment cuite = fade",
      "Béchamel grumeleux = texture désagréable",
      "Trop fromage = croûte brûlée",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["pâtes lasagnes", "viande hachée", "tomate", "béchamel"],
    ingredients: [
      { name: "pâtes lasagnes", quantity: "400g" },
      { name: "viande hachée", quantity: "500g" },
      { name: "tomate en conserve", quantity: "800g" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "3 gousses" },
      { name: "lait", quantity: "500ml" },
      { name: "farine", quantity: "40g" },
      { name: "beurre", quantity: "40g" },
      { name: "fromage rapé", quantity: "150g" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Faire revenir oignon, ail. Ajouter viande hachée. Cuire 10 min.",
      "Ajouter tomate, laisser mijoter 30 min. Assaisonner.",
      "Faire béchamel (roux beurre-farine, verser lait chaud progressivement).",
      "Cuire pâtes al dente, égoutter.",
      "Faire couches dans plat: béchamel, pâtes, bolognaise, fromage. Répéter.",
      "Terminer béchamel et fromage. Enfourner 200C pendant 40 min.",
      "Gratin doré, reposer 10 min avant service.",
    ],
    techniques: ["bake"],
    tags: ["lasagnes", "bolognaise", "gratin", "pâtes"],
  },
  {
    id: "moussaka-grecque",
    name: "Moussaka grecque",
    desireName: "Moussaka layered aubergines-viande, sauce béchamel doré",
    aliases: ["moussaka", "aubergine gratinée"],
    cuisine: "francaise",
    region: "Grèce-France",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "gratins-legumes",
    technique: "bake",
    baseFamilies: ["aubergine", "viande", "béchamel"],
    fundamentals: ["aubergines frites tendre", "sauce tomate-viande", "béchamel lisse"],
    timings: { prep: 40, cook: 50, rest: 15 },
    servings: 6,
    portionAdaptation: "linear",
    signature: "Moussaka fondante, layering aubergine-viande savoureux",
    profTips: [
      "Aubergines frites ou rôties pour texture tendre",
      "Viande cuite avec épices greques (cannelle, origan)",
      "Béchamel veloutée couvrant le dessus",
    ],
    mistakes: [
      "Aubergines pas assez cuites = dures",
      "Viande insuffisamment cuite = goutée crue",
      "Béchamel trop épaisse = cassante",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["aubergine", "viande", "tomate", "béchamel"],
    ingredients: [
      { name: "aubergines", quantity: "2 gros" },
      { name: "viande hachée", quantity: "500g" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "3 gousses" },
      { name: "tomate concentrée", quantity: "2 cs" },
      { name: "vin rouge", quantity: "100ml" },
      { name: "cannelle", quantity: "1/2 cc" },
      { name: "origan", quantity: "1 cc" },
      { name: "béchamel", quantity: "500ml" },
      { name: "fromage rapé", quantity: "100g" },
      { name: "huile d'olive", quantity: "4 cs" },
    ],
    steps: [
      "Trancher aubergines 1cm. Saler, laisser 15 min décroûter eau.",
      "Frire aubergines à l'huile olive ou rôtir 190C jusqu'à tendre.",
      "Faire revenir oignon, ail. Ajouter viande. Cuire 10 min.",
      "Ajouter tomate, vin, épices. Laisser 15 min.",
      "Layering plat: viande, aubergines, béchamel, fromage. Répéter.",
      "Terminer béchamel-fromage. Enfourner 200C pendant 45 min.",
      "Gratin doré, reposer 10 min.",
    ],
    techniques: ["bake", "fry"],
    tags: ["moussaka", "aubergine", "gratin", "grecque"],
  },
  {
    id: "quiche-lorraine",
    name: "Quiche lorraine",
    desireName: "Quiche lardons-œufs, pâte croustillante crème fondante",
    aliases: ["quiche", "tarte lorraine"],
    cuisine: "francaise",
    region: "Alsace",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "quiches",
    technique: "bake",
    baseFamilies: ["pâte", "lardons", "œufs", "crème"],
    fundamentals: ["pâte brisée croustillante", "lardons rissolés", "appareil crème-œuf"],
    timings: { prep: 25, cook: 35, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Quiche croustillante, garniture crème lardons tendre",
    profTips: [
      "Pâte doit être précuite pour rester croustillante",
      "Lardons rissolés séparément pour croustillant",
      "Appareil pas trop riche pour ne pas lourd",
    ],
    mistakes: [
      "Pâte pas précuite = fond mouillé",
      "Lardons trop cuits = durs",
      "Appareil trop riche = quiche lourde",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 3 },
    category: "plat_principal",
    baseIngredients: ["pâte brisée", "lardons", "œufs", "crème"],
    ingredients: [
      { name: "pâte brisée", quantity: "250g" },
      { name: "lardons fumés", quantity: "200g" },
      { name: "œufs", quantity: "3" },
      { name: "crème fraîche", quantity: "200ml" },
      { name: "lait", quantity: "50ml" },
      { name: "oignon", quantity: "1" },
      { name: "fromage rapé", quantity: "50g" },
      { name: "sel, poivre, muscade", quantity: "à goûter" },
    ],
    steps: [
      "Foncer moule avec pâte brisée. Précuire 10 min 200C.",
      "Faire revenir lardons. Ajouter oignon haché, cuire 2 min.",
      "Battre œufs avec crème et lait. Assaisonner.",
      "Verser lardons et oignon dans moule. Couvrir appareil.",
      "Saupoudrer fromage. Enfourner 180C pendant 25 min.",
      "Quiche cuite au centre. Reposer 5 min avant démoulage.",
    ],
    techniques: ["bake"],
    tags: ["quiche", "lorraine", "lardons", "crème"],
  },
  {
    id: "hachis-parmentier",
    name: "Hachis Parmentier",
    desireName: "Hachis Parmentier classique, couche viande-pommes gratinées",
    aliases: ["hachis", "parmentier"],
    cuisine: "francaise",
    region: "France",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratins",
    technique: "bake",
    baseFamilies: ["viande hachée", "pomme de terre", "fromage"],
    fundamentals: ["viande hachée cuite", "purée pommes lisse", "gratin 30 min"],
    timings: { prep: 20, cook: 40, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Gratin français familial, viande fondante sous pommes dorées",
    profTips: [
      "Viande doit être bien cuite, assaisonnée généreuse",
      "Purée lisse sans grumeaux pour élégance",
      "Gratin juste doré, beurre noisette sommet",
    ],
    mistakes: [
      "Viande pâle = fade insuffisant",
      "Purée grumeleux = texture désagréable",
      "Gratin brûlé = amertume",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 3 },
    category: "plat_principal",
    baseIngredients: ["viande hachée", "pomme de terre", "oignon"],
    ingredients: [
      { name: "viande hachée", quantity: "500g" },
      { name: "pommes de terre", quantity: "800g" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "2 gousses" },
      { name: "lait", quantity: "100ml" },
      { name: "beurre", quantity: "40g" },
      { name: "fromage rapé", quantity: "80g" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Cuire pommes de terre épluchées à l'eau salée 20 min.",
      "Faire revenir oignon, ail. Ajouter viande hachée, cuire 10 min.",
      "Assaisonner généreusement viande.",
      "Réduire pommes en purée lisse avec lait et beurre.",
      "Étaler viande dans plat. Couvrir purée.",
      "Saupoudrer fromage. Enfourner 200C pendant 30 min.",
      "Gratin doré. Reposer 5 min.",
    ],
    techniques: ["bake"],
    tags: ["hachis", "parmentier", "gratin", "classique"],
  },
  {
    id: "gratin-dauphinois",
    name: "Gratin Dauphinois",
    desireName: "Gratin pommes dauphinois, crème coco lait, tendre doré",
    aliases: ["gratin dauphinois", "pommes dauphinoises"],
    cuisine: "francaise",
    region: "Dauphiné",
    slot: "side",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratins",
    technique: "bake",
    baseFamilies: ["pomme de terre", "crème", "lait"],
    fundamentals: ["pommes tranchées fin", "crème épaisse", "cuisson slow 1h"],
    timings: { prep: 15, cook: 60, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Gratin pommes tendre, sauce crème onctueuse doré",
    profTips: [
      "Pommes tranchées fin et régulièrement",
      "Crème doit recouvrir légèrement pommes",
      "Cuisson lente pour cuisson homogène",
    ],
    mistakes: [
      "Pommes tranchées épais = cuisson inégale",
      "Crème insuffisante = gratin sec",
      "Cuisson rapide = pommes dures",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 3 },
    category: "accompagnement",
    baseIngredients: ["pomme de terre", "crème", "lait"],
    ingredients: [
      { name: "pommes de terre", quantity: "800g" },
      { name: "crème fraîche", quantity: "300ml" },
      { name: "lait entier", quantity: "100ml" },
      { name: "ail", quantity: "2 gousses" },
      { name: "beurre", quantity: "1 cs" },
      { name: "sel, poivre, muscade", quantity: "à goûter" },
    ],
    steps: [
      "Éplucher pommes. Trancher fin mandoline de préférence.",
      "Frotter plat ail. Beurrer.",
      "Layering plat: pommes, crème-lait. Assaisonner.",
      "Couvrir feuille aluminium. Enfourner 180C pendant 45 min.",
      "Retirer feuille, laisser 15 min doré.",
      "Gratin tendre doré. Reposer 5 min.",
    ],
    techniques: ["bake"],
    tags: ["gratin", "pommes", "dauphinois", "crème"],
  },
  {
    id: "escalope-milanaise",
    name: "Escalope à la milanaise",
    desireName: "Escalope panée croustillante, citron jus frais",
    aliases: ["escalope milanaise", "scaloppine"],
    cuisine: "francaise",
    region: "Italie-France",
    slot: "lunch",
    difficulty: 1,
    minChefLevel: 1,
    family: "viandes-panees",
    technique: "fry",
    baseFamilies: ["veau", "panure", "citron"],
    fundamentals: ["escalope aplatie fin", "panure croustillante", "friture 170C"],
    timings: { prep: 10, cook: 10, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Escalope croustillante, jus citron frais acidité",
    profTips: [
      "Escalope doit être aplatie très fin pour tendreté",
      "Double panure pour croustillant maximal",
      "Citron frais en jus après cuisson pour acidité",
    ],
    mistakes: [
      "Escalope épaisse = texture dure",
      "Panure molle = perte croustillant",
      "Citron trop tôt = perte acidité",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 5, visuel: 3, arome: 3 },
    category: "plat_principal",
    baseIngredients: ["veau", "panure", "citron"],
    ingredients: [
      { name: "escalopes de veau", quantity: "2" },
      { name: "farine", quantity: "50g" },
      { name: "œuf", quantity: "1" },
      { name: "chapelure", quantity: "80g" },
      { name: "citron", quantity: "1" },
      { name: "huile de friture", quantity: "500ml" },
      { name: "beurre", quantity: "1 cs" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Aplatir escalopes entre deux films à très fin (3mm).",
      "Passer farine, œuf battu, chapelure.",
      "Chauffer huile 170C.",
      "Frire escalope 2 min par face, croustillante doré.",
      "Égoutter papier. Dresser assiette.",
      "Verser beurre noisette chaud, jus citron frais.",
    ],
    techniques: ["fry"],
    tags: ["escalope", "milanaise", "veau", "panée"],
  },
  {
    id: "sole-meuniere",
    name: "Sole à la meunière",
    desireName: "Sole fraîche poêlée beurre noisette, citron jus",
    aliases: ["sole meunière", "poisson meunière"],
    cuisine: "francaise",
    region: "France",
    slot: "dinner",
    difficulty: 2,
    minChefLevel: 2,
    family: "poisson-beurre",
    technique: "fry",
    baseFamilies: ["poisson blanc", "beurre", "citron"],
    fundamentals: ["sole fraîche entière", "farine légère", "beurre noisette"],
    timings: { prep: 10, cook: 8, rest: 0 },
    servings: 2,
    portionAdaptation: "moderate",
    signature: "Poisson délicat beurre noisette, saveur mer et citron",
    profTips: [
      "Sole entière plus savoureuse que filets",
      "Beurre doit être noisette, pas calciné",
      "Citron frais presse après cuisson",
    ],
    mistakes: [
      "Sole filetée = saveur perdue",
      "Beurre brûlé = amertume désagréable",
      "Cuisson trop longue = chair sèche",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 4, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["sole", "beurre", "citron"],
    ingredients: [
      { name: "sole fraîche entière", quantity: "300g" },
      { name: "farine", quantity: "30g" },
      { name: "beurre", quantity: "80g" },
      { name: "citron", quantity: "1" },
      { name: "sel, poivre", quantity: "à goûter" },
      { name: "persil frais", quantity: "1 poignée" },
    ],
    steps: [
      "Nettoyer sole, retirer nageoires. Saler poivrer.",
      "Passer farine légèrement.",
      "Chauffer beurre à la poêle. Ajouter sole.",
      "Cuire 3-4 min par face. Beurre doit mousser, pas brûler.",
      "Verser beurre noisette. Jus citron frais.",
      "Dresser persil haché. Servir immédiatement.",
    ],
    techniques: ["fry"],
    tags: ["sole", "poisson", "beurre", "meunière"],
  },
  {
    id: "bouillabaisse",
    name: "Bouillabaisse provençale",
    desireName: "Bouillabaisse poisson-safran, rouille croûton élégant",
    aliases: ["bouillabaisse", "potage provençal"],
    cuisine: "francaise",
    region: "Provence",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "soupes-poisson",
    technique: "simmer",
    baseFamilies: ["poisson", "safran", "tomate"],
    fundamentals: ["poisson blanc assortie", "safran infusé", "mijoté 30 min"],
    timings: { prep: 30, cook: 35, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Soupe poisson savoureux, safran arôme provençal",
    profTips: [
      "Poisson blanc varié pour saveur complexe",
      "Safran broyé macéré eau chaude",
      "Rouille ail-huile traditionnelle",
    ],
    mistakes: [
      "Safran mal dosé = fade ou amertume",
      "Poisson surcouit = chair cassante",
      "Rouille sans ail = manque saveur",
    ],
    premiumTier: "gastronomique",
    plaisir: { gourmandise: 4, texture: 3, visuel: 4, arome: 5 },
    category: "soupe",
    baseIngredients: ["poisson blanc", "safran", "tomate", "ail"],
    ingredients: [
      { name: "poisson blanc divers (ST-Pierre, rouget, loup)", quantity: "800g" },
      { name: "safran filaments", quantity: "1 g" },
      { name: "tomate concassée", quantity: "300g" },
      { name: "ail", quantity: "6 gousses" },
      { name: "oignon", quantity: "2" },
      { name: "fenouil", quantity: "1/2" },
      { name: "eau", quantity: "1L" },
      { name: "huile olive", quantity: "4 cs" },
      { name: "piment", quantity: "1" },
      { name: "pain grillé", quantity: "8 tranches" },
    ],
    steps: [
      "Broyer safran, macérer eau chaude 20 min.",
      "Faire revenir oignon, ail, fenouil dans huile.",
      "Ajouter tomate, piment. Laisser 5 min.",
      "Versser eau, safran. Laisser bouillir 10 min.",
      "Ajouter poisson, laisser 15 min feu doux.",
      "Faire rouille: ail pila huile. Tartiner pain grillé.",
      "Servir soupe, rouillon croûton séparé.",
    ],
    techniques: ["simmer"],
    tags: ["bouillabaisse", "poisson", "safran", "provençal"],
  },
  {
    id: "cremes-brulees",
    name: "Crèmes brûlées",
    desireName: "Crème brûlée vanille, sucre caramélisé croustillant",
    aliases: ["crème brûlée", "brûlée"],
    cuisine: "francaise",
    region: "France",
    slot: "dessert",
    difficulty: 2,
    minChefLevel: 2,
    family: "dessert-creme",
    technique: "bake_in_bath",
    baseFamilies: ["crème", "œufs", "vanille"],
    fundamentals: ["crème entière riche", "cuisson bain-marie 30 min", "sucre brûlé"],
    timings: { prep: 15, cook: 30, rest: 240 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Crème onctueuse vanille, croûte sucre caramélisée croustillante",
    profTips: [
      "Crème doit être entière riche pour onctuosité",
      "Cuisson bain-marie lente pour crème lisse",
      "Sucre doit être croquant immédiatement après chalumeau",
    ],
    mistakes: [
      "Crème légère = texture moins riche",
      "Cuisson rapide = texture granuleuse",
      "Sucre caramélisé trop tôt avant service = ramolli",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 4 },
    category: "dessert",
    baseIngredients: ["crème", "œufs", "vanille", "sucre"],
    ingredients: [
      { name: "crème fraîche entière", quantity: "400ml" },
      { name: "jaunes d'œufs", quantity: "4" },
      { name: "vanille pod ou extrait", quantity: "1" },
      { name: "sucre", quantity: "50g + 20g par ramekin" },
      { name: "sel", quantity: "pincée" },
    ],
    steps: [
      "Chauffer crème avec vanille fendue jusqu'à frémir.",
      "Fouetter jaunes avec sucre jusqu'à pâle.",
      "Verser crème chaude progressivement sur jaunes, toujours fouetter.",
      "Passer tamis fin. Verser dans ramekins.",
      "Cuire bain-marie 160C pendant 30 min (nacre frémit, cœur frémit).",
      "Refroidir complètement, réfrigérer minimum 4h.",
      "Avant service, saupoudrer sucre, caraméliser au chalumeau.",
    ],
    techniques: ["bake_in_bath"],
    tags: ["crème brûlée", "vanille", "dessert", "classique"],
  },
];

export default FRANCAIS_LOT4;
