/**
 * PLATS FRANÇAIS — Base qualitative vérifiée
 * Chaque plat est réel, avec ingrédients cohérents et étapes crédibles.
 * Organisé par lots validés.
 */

import { DishProfile } from "../dishKnowledge";

// ============================================
// LOT 1 — 9 plats existants (vérifiés phase 2-4)
// ============================================
const LOT_1: DishProfile[] = [
  {
    id: "quiche-lorraine",
    name: "Quiche lorraine",
    desireName: "Quiche lorraine crémeuse, lardons fumés dorés",
    aliases: ["quiche", "quiche lorraine"],
    cuisine: "francaise",
    region: "Lorraine",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "tarte-oeufs",
    technique: "bake",
    baseFamilies: ["farine", "oeuf", "creme", "lard"],
    fundamentals: ["fond pate regulier", "lard cuit d'abord", "creme oeuf bien lie"],
    timings: { prep: 20, cook: 35, rest: 8 },
    servings: 6,
    portionAdaptation: "linear",
    signature: "Tarte crémeuse lard croustillant, custard doree, texture legere",
    profTips: [
      "Pate foncer sans bulles, piquer fond",
      "Lard cuire 5 min avant pour croustillant",
      "Creme et oeufs ne JAMAIS bouillir = texture grumeleuse",
    ],
    mistakes: [
      "Pate pas cuite = soupe dessous",
      "Lard brule = amertume",
      "Cuisson trop longue = creme seche et caoutchouteuse",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "plat",
    baseIngredients: ["pate brisee", "lardons", "oeufs", "creme fraiche", "lait", "muscade"],
    ingredients: [
      { name: "pate brisee", quantity: "1 rouleau" },
      { name: "lardons fumes", quantity: "200g" },
      { name: "oeufs", quantity: "3" },
      { name: "creme fraiche", quantity: "200ml" },
      { name: "lait", quantity: "100ml" },
      { name: "muscade", quantity: "1 pincee" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Prechauffer four a 180C. Foncer le moule avec la pate, piquer le fond.",
      "Faire revenir lardons 5 min a sec pour les rendre croustillants.",
      "Repartir lardons sur le fond de tarte.",
      "Battre oeufs + creme + lait + muscade + sel + poivre.",
      "Verser l'appareil sur les lardons.",
      "Enfourner 35 min jusqu'a surface doree et ferme au toucher.",
      "Laisser reposer 8 min avant de demouler.",
    ],
    techniques: ["bake"],
    tags: ["tarte", "lorraine", "classique", "familial"],
  },
  {
    id: "gratin-dauphinois",
    name: "Gratin dauphinois",
    desireName: "Gratin dauphinois crémeux, croûte gratinée dorée",
    aliases: ["gratin", "gratin dauphinois", "gratin pommes de terre"],
    cuisine: "francaise",
    region: "Dauphiné",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "gratin",
    technique: "bake",
    baseFamilies: ["pomme-terre", "creme", "lait"],
    fundamentals: ["tranches regulieres 2-3mm", "sauce creme-ail", "cuisson lente 50 min"],
    timings: { prep: 20, cook: 55, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Pommes de terre cremeuses fondantes, surface doree et croustillante",
    profTips: [
      "Tranches regulieres pour cuisson uniforme",
      "Verser sauce creme-ail sur pommes de terre crues",
      "Cuisson four 180C lente pour texture creme",
    ],
    mistakes: [
      "Tranches trop epaisses = pommes de terre crues dedans",
      "Sauce trop peu liquide = gratin sec",
      "Four trop chaud = surface brulee, dedans cru",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 3 },
    category: "plat",
    baseIngredients: ["pomme de terre", "creme fraiche", "lait", "ail", "muscade", "beurre"],
    ingredients: [
      { name: "pommes de terre (type bintje)", quantity: "1kg" },
      { name: "creme fraiche", quantity: "300ml" },
      { name: "lait", quantity: "200ml" },
      { name: "ail", quantity: "2 gousses" },
      { name: "muscade", quantity: "1 pincee" },
      { name: "beurre", quantity: "20g" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Prechauffer four a 180C. Beurrer un plat a gratin, frotter a l'ail.",
      "Eplucher et emincer pommes de terre en tranches de 2-3mm.",
      "Melanger creme + lait + ail hache + muscade + sel + poivre.",
      "Disposer couches de pommes de terre en nappant chaque couche de sauce.",
      "Enfourner 55 min a 180C. Verifier que les pommes de terre sont fondantes.",
      "Laisser reposer 10 min avant de servir.",
    ],
    techniques: ["bake"],
    tags: ["gratin", "dauphiné", "accompagnement", "hiver"],
  },
  {
    id: "coq-au-vin",
    name: "Coq au vin",
    desireName: "Coq au vin mijoté, sauce onctueuse au vin rouge",
    aliases: ["coq au vin", "poulet au vin rouge"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "dinner",
    difficulty: 4,
    minChefLevel: 4,
    family: "braise-rouge",
    technique: "braise",
    baseFamilies: ["poulet", "vin-rouge", "lard", "oignon", "champignon"],
    fundamentals: ["marinade 2-4h avant", "saisir volaille bien", "vin reduce de moitie"],
    timings: { prep: 30, cook: 90, rest: 10 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Poulet tendre vin rouge riche, sauce onctueuse, garniture lard-champignon",
    profTips: [
      "Mariner poule dans vin rouge + herbes 2-4 heures",
      "Saisir poule 3 min chaque face pour croute",
      "Vin doit etre reduit de moitie avant ajouter poule",
    ],
    mistakes: [
      "Pas mariner = gout plat",
      "Poule pas bien saisie = pas couleur",
      "Vin pas reduit = sauce aqueuse et alcool trop fort",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 5, arome: 5 },
    category: "viande",
    baseIngredients: ["poulet", "vin rouge", "lardons", "champignons", "oignon", "carotte", "ail", "bouquet garni"],
    ingredients: [
      { name: "poulet decoupé", quantity: "1.5kg" },
      { name: "vin rouge (Bourgogne)", quantity: "75cl" },
      { name: "lardons", quantity: "150g" },
      { name: "champignons de Paris", quantity: "250g" },
      { name: "petits oignons", quantity: "12" },
      { name: "carotte", quantity: "2" },
      { name: "ail", quantity: "3 gousses" },
      { name: "bouquet garni", quantity: "1" },
      { name: "farine", quantity: "2 cs" },
      { name: "beurre", quantity: "30g" },
    ],
    steps: [
      "Mariner poulet dans vin rouge + bouquet garni + oignon 2-4h au frais.",
      "Egoutter poulet, secher. Reserver la marinade.",
      "Saisir poulet dans beurre 3 min chaque face, reserver.",
      "Faire revenir lardons + oignons + carotte 5 min.",
      "Singer la farine, mouiller avec la marinade. Porter a ebullition.",
      "Remettre le poulet, couvrir et mijoter 1h30 a feu doux.",
      "Ajouter champignons sautes les 15 dernieres minutes.",
      "Rectifier assaisonnement. Laisser reposer 10 min avant servir.",
    ],
    techniques: ["braise", "sear", "marinate"],
    tags: ["mijoté", "bourgogne", "vin rouge", "classique"],
  },
  {
    id: "beef-bourguignon",
    name: "Beef bourguignon",
    desireName: "Boeuf bourguignon fondant, sauce au vin profonde",
    aliases: ["beef bourguignon", "boeuf bourguignon"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "dinner",
    difficulty: 4,
    minChefLevel: 4,
    family: "braise-rouge",
    technique: "braise",
    baseFamilies: ["boeuf", "vin-rouge", "lard", "oignon", "champignon"],
    fundamentals: ["boeuf persille", "saisir cubes tres bien", "vin + bouillon reduit"],
    timings: { prep: 40, cook: 150, rest: 15 },
    servings: 6,
    portionAdaptation: "moderate",
    signature: "Boeuf tendre sauce vin rouge complete, aromatique, garnish classique",
    profTips: [
      "Boeuf bien persille pour gras intramuscular",
      "Cubes saisir 4 min par face pour croute Maillard",
      "Vin + bouillon ajout apres saisie, reduce lentement",
    ],
    mistakes: [
      "Boeuf maigre = dur apres cuisson",
      "Pas bien saisir = pas croute saveur",
      "Cuisson trop rapide = boeuf dur",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 5, arome: 5 },
    category: "viande",
    baseIngredients: ["paleron de boeuf", "vin rouge", "lardons", "champignons", "carotte", "oignon", "ail", "concentre de tomate"],
    ingredients: [
      { name: "paleron de boeuf", quantity: "1kg" },
      { name: "vin rouge", quantity: "75cl" },
      { name: "lardons", quantity: "150g" },
      { name: "champignons", quantity: "250g" },
      { name: "carotte", quantity: "3" },
      { name: "oignon", quantity: "2" },
      { name: "ail", quantity: "3 gousses" },
      { name: "concentre de tomate", quantity: "1 cs" },
      { name: "bouquet garni", quantity: "1" },
      { name: "farine", quantity: "2 cs" },
    ],
    steps: [
      "Couper boeuf en cubes de 4cm. Secher soigneusement.",
      "Saisir les cubes dans huile bien chaude, 3-4 min par face. Reserver.",
      "Faire revenir lardons, oignon et carotte 5 min.",
      "Saupoudrer farine, remuer 1 min. Ajouter concentre de tomate.",
      "Deglacer au vin rouge, ajouter bouquet garni et ail.",
      "Remettre boeuf, couvrir. Mijoter 2h30 a feu tres doux.",
      "Ajouter champignons sautes les 20 dernieres minutes.",
      "Laisser reposer 15 min avant de servir.",
    ],
    techniques: ["braise", "sear"],
    tags: ["mijoté", "bourgogne", "hiver", "familial"],
  },
  {
    id: "sole-meuniere",
    name: "Sole meunière",
    desireName: "Sole meunière au beurre noisette, citron frais",
    aliases: ["sole meuniere", "sole a la meuniere"],
    cuisine: "francaise",
    region: "Classique",
    slot: "dinner",
    difficulty: 3,
    minChefLevel: 3,
    family: "poisson-frit",
    technique: "fry",
    baseFamilies: ["sole", "beurre", "citron"],
    fundamentals: ["sole videe impeccable", "beurre noisette pas noir", "saisir 2 min chaque cote"],
    timings: { prep: 10, cook: 8, rest: 0 },
    servings: 1,
    portionAdaptation: "linear",
    signature: "Sole delicate chair blanche, beurre noisette mousseux, citron frais",
    profTips: [
      "Sole fraiche essentielle, videe proprement",
      "Beurre doit etre noisette, jamais noir",
      "Saisir 2 min chaque cote exactement",
    ],
    mistakes: [
      "Sole pas fraiche = chair molle",
      "Beurre brule = amertume",
      "Trop cuire = chair seche et cassante",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 4, visuel: 5, arome: 4 },
    category: "poisson",
    baseIngredients: ["sole", "beurre", "citron", "farine", "persil"],
    ingredients: [
      { name: "sole entiere videe", quantity: "1 (300g)" },
      { name: "beurre", quantity: "50g" },
      { name: "citron", quantity: "1" },
      { name: "farine", quantity: "2 cs" },
      { name: "persil frais", quantity: "1 bouquet" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Rincer sole, secher soigneusement avec papier absorbant.",
      "Fariner legerement les deux faces, tapoter l'exces.",
      "Chauffer beurre dans poele large a feu moyen.",
      "Cuire sole 2 min premiere face, retourner delicatement.",
      "Cuire 2 min deuxieme face. Beurre doit etre noisette (dore, pas noir).",
      "Dresser, arroser de beurre noisette, jus de citron et persil.",
    ],
    techniques: ["fry"],
    tags: ["poisson", "classique", "raffiné", "rapide"],
  },
  {
    id: "sauce-creme-classique",
    name: "Sauce crème classique",
    desireName: "Sauce crème onctueuse aux herbes",
    aliases: ["sauce creme", "sauce creme fraiche", "sauce a la creme"],
    cuisine: "francaise",
    region: "Classique",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "sauce",
    technique: "reduce",
    baseFamilies: ["creme", "beurre", "oignon"],
    fundamentals: ["base aromatique doux", "reduction lente", "liaison creme"],
    timings: { prep: 8, cook: 12, rest: 0 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Sauce creme onctueuse nappante, saveur aromatique douce",
    profTips: [
      "Oignon et ail suer 2 min feu doux",
      "Creme en reduction lente 8-10 min pour nappante",
      "Ne JAMAIS bouillir apres ajout creme",
    ],
    mistakes: [
      "Oignon pas sue = texture desagreable",
      "Creme bouillie = sauce tranchee et granuleuse",
      "Pas assez de reduction = sauce trop liquide",
    ],
    premiumTier: "essentiel",
    plaisir: { gourmandise: 3, texture: 3, visuel: 2, arome: 3 },
    category: "sauce",
    baseIngredients: ["creme fraiche", "beurre", "echalote", "vin blanc", "persil"],
    ingredients: [
      { name: "creme fraiche", quantity: "200ml" },
      { name: "beurre", quantity: "20g" },
      { name: "echalote", quantity: "2" },
      { name: "vin blanc sec", quantity: "5cl", optional: true },
      { name: "persil", quantity: "quelques feuilles" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Emincer echalotes finement. Faire suer dans beurre 2 min feu doux.",
      "Deglacer au vin blanc si utilise, reduire 1 min.",
      "Ajouter creme fraiche, melanger.",
      "Reduire a feu doux 8-10 min en remuant regulierement.",
      "Assaisonner, parsemer de persil. Servir nappee sur plat.",
    ],
    techniques: ["reduce"],
    tags: ["sauce", "classique", "basique", "accompagnement"],
  },
  {
    id: "tarte-salee",
    name: "Tarte salée maison",
    desireName: "Tarte salée rustique aux légumes de saison",
    aliases: ["tarte", "tarte salee", "tarte legumes"],
    cuisine: "francaise",
    region: "Classique",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "tarte",
    technique: "bake",
    baseFamilies: ["farine", "beurre", "tomate"],
    fundamentals: ["pate foncer regulier", "garniture equilibree", "cuisson four 180C"],
    timings: { prep: 20, cook: 30, rest: 5 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Tarte croustillante pate, garniture tomate legumes fondants",
    profTips: [
      "Pate foncer sans bulles, piquer fond",
      "Garniture pas trop serree pour cuisson uniforme",
      "Four 180C regulier 30 min pour pate doree",
    ],
    mistakes: [
      "Pate pas cuite en bas = gluante",
      "Garniture trop serree = cuisson inegale",
      "Trop de tomate = sauce imbibe la pate",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 3, texture: 4, visuel: 3, arome: 3 },
    category: "plat",
    baseIngredients: ["pate brisee", "tomate", "oignon", "fromage", "oeuf", "creme"],
    ingredients: [
      { name: "pate brisee", quantity: "1 rouleau" },
      { name: "tomate", quantity: "3" },
      { name: "oignon", quantity: "1" },
      { name: "fromage rape", quantity: "80g" },
      { name: "oeuf", quantity: "1" },
      { name: "creme fraiche", quantity: "100ml" },
      { name: "sel, poivre, herbes de Provence" },
    ],
    steps: [
      "Prechauffer four a 180C. Foncer moule avec pate, piquer fond.",
      "Emincer oignon, faire revenir 3 min. Couper tomates en rondelles.",
      "Melanger oeuf + creme + herbes. Verser sur fond de tarte.",
      "Disposer tomates et oignon, saupoudrer fromage.",
      "Enfourner 30 min. Laisser reposer 5 min avant decoupe.",
    ],
    techniques: ["bake"],
    tags: ["tarte", "légumes", "classique", "familial"],
  },
  {
    id: "pain-au-beurre",
    name: "Pain au beurre français",
    desireName: "Pain brioché au beurre doré, mie fondante",
    aliases: ["pain au beurre", "pain-au-beurre"],
    cuisine: "francaise",
    region: "Boulangerie",
    slot: "breakfast",
    difficulty: 3,
    minChefLevel: 3,
    family: "boulangerie",
    technique: "bake",
    baseFamilies: ["farine", "beurre", "levure"],
    fundamentals: ["pate enrichie", "petrissage 10 min", "levage puis dorage"],
    timings: { prep: 25, cook: 28, rest: 120 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Pain tendre moelleux, croute doree legere, interieur aere",
    profTips: [
      "Petrir 10 min pour developper gluten",
      "Levage 120 min jusqu'a double de volume",
      "Dorer a l'oeuf et saupoudrer sucre cristal avant cuire",
    ],
    mistakes: [
      "Pas assez de petrissage = pain dense",
      "Levage insuffisant = pain compact",
      "Cuisson trop rapide = croute dure, dedans pas cuit",
    ],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 5, visuel: 3, arome: 4 },
    category: "pâte",
    baseIngredients: ["farine", "beurre", "oeuf", "lait", "levure boulangere", "sucre"],
    ingredients: [
      { name: "farine", quantity: "300g" },
      { name: "beurre mou", quantity: "60g" },
      { name: "oeuf", quantity: "1" },
      { name: "lait tiede", quantity: "120ml" },
      { name: "levure boulangere fraiche", quantity: "15g" },
      { name: "sucre", quantity: "30g" },
      { name: "sel", quantity: "1 cc" },
    ],
    steps: [
      "Diluer levure dans lait tiede (pas chaud). Laisser mousser 5 min.",
      "Melanger farine + sel + sucre. Ajouter oeuf et melange levure-lait.",
      "Petrir 8-10 min energiquement. Incorporer beurre mou en morceaux.",
      "Petrir encore 5 min jusqu'a pate lisse et elastique.",
      "Couvrir, laisser lever 1h30-2h a temperature ambiante (doit doubler).",
      "Degazer, faconner en petits pains ou tresse. Laisser pousser 30 min.",
      "Dorer a l'oeuf. Enfourner 25-28 min a 175C.",
    ],
    techniques: ["bake", "knead"],
    tags: ["boulangerie", "petit-déjeuner", "brioché", "sucré"],
  },
  {
    id: "omelette-persil",
    name: "Omelette persil",
    desireName: "Omelette baveuse au persil frais, beurre mousseux",
    aliases: ["omelette", "omelette persil"],
    cuisine: "francaise",
    region: "Classique",
    slot: "breakfast",
    difficulty: 2,
    minChefLevel: 2,
    family: "oeuf",
    technique: "sear",
    baseFamilies: ["oeuf", "beurre", "persil"],
    fundamentals: ["oeufs battus doux", "beurre frais mousseux", "pliage avant bien cuit"],
    timings: { prep: 5, cook: 4, rest: 0 },
    servings: 1,
    portionAdaptation: "linear",
    signature: "Omelette tendre creuse dedans, pliee parfaite, garniture simple",
    profTips: [
      "Oeufs simplement battus, pas surtravailler",
      "Beurre doit etre frais et mousseux",
      "Plier omelette AVANT qu'elle soit tout a fait cuite",
    ],
    mistakes: [
      "Oeufs trop travailles = dense",
      "Beurre cuit/noir = amertume",
      "Omelette trop cuite = caoutchouteuse",
    ],
    premiumTier: "essentiel",
    plaisir: { gourmandise: 3, texture: 4, visuel: 2, arome: 3 },
    category: "plat",
    baseIngredients: ["oeufs", "beurre", "persil", "sel", "poivre"],
    ingredients: [
      { name: "oeufs", quantity: "3" },
      { name: "beurre", quantity: "15g" },
      { name: "persil frais", quantity: "1 cs hache" },
      { name: "sel, poivre" },
    ],
    steps: [
      "Casser oeufs dans bol, assaisonner. Battre legerement a la fourchette.",
      "Chauffer beurre dans poele a feu moyen, il doit mousser.",
      "Verser oeufs, remuer doucement 30 sec au centre.",
      "Laisser prendre 1 min. Ajouter persil.",
      "Plier en trois AVANT cuisson complete (interieur doit etre baveux).",
      "Servir immediatement, l'omelette continue de cuire hors poele.",
    ],
    techniques: ["sear"],
    tags: ["rapide", "basique", "petit-déjeuner", "oeufs"],
  },
];

// ============================================
// LOT 2 — 1 nouveau plat vérifié
// ============================================
const LOT_2: DishProfile[] = [
  {
    id: "blanquette-veau",
    name: "Blanquette de veau",
    desireName: "Blanquette de veau onctueuse, sauce blanche veloutée",
    aliases: ["blanquette", "blanquette de veau", "blanquette veau"],
    cuisine: "francaise",
    region: "Classique",
    slot: "dinner",
    difficulty: 3,
    minChefLevel: 3,
    family: "braise-blanc",
    technique: "braise",
    baseFamilies: ["veau", "carotte", "oignon", "creme", "champignon"],
    fundamentals: ["pochage delicat du veau", "sauce blanche liee jaune-creme", "garniture aromatique"],
    timings: { prep: 20, cook: 90, rest: 5 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Veau tendre dans sauce blanche veloutee, champignons et carottes",
    profTips: [
      "Veau poché, jamais bouillie = chair reste tendre et blanche",
      "Liaison jaune + creme hors du feu pour eviter que ca tranche",
      "Champignons sautes a part et ajoutes en fin",
    ],
    mistakes: [
      "Bouillir le veau = viande grise et dure",
      "Liaison sur feu vif = sauce tranchee",
      "Pas assez de temps = veau dur",
    ],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 4, visuel: 4, arome: 4 },
    category: "viande",
    baseIngredients: ["epaule de veau", "carotte", "oignon", "bouquet garni", "champignons", "creme fraiche", "jaune d'oeuf", "citron"],
    ingredients: [
      { name: "epaule de veau (ou tendron)", quantity: "800g" },
      { name: "carotte", quantity: "3" },
      { name: "oignon pique de clous de girofle", quantity: "1" },
      { name: "bouquet garni", quantity: "1" },
      { name: "champignons de Paris", quantity: "200g" },
      { name: "creme fraiche", quantity: "150ml" },
      { name: "jaune d'oeuf", quantity: "2" },
      { name: "citron", quantity: "1/2" },
      { name: "beurre", quantity: "30g" },
      { name: "farine", quantity: "30g" },
    ],
    steps: [
      "Couper veau en gros cubes. Blanchir 2 min a l'eau bouillante, egoutter.",
      "Remettre dans casserole propre, couvrir d'eau froide. Porter a fremissement.",
      "Ajouter carotte, oignon pique, bouquet garni. Cuire 1h15 a petit feu (pas bouillir).",
      "Preparer roux blanc: fondre beurre, ajouter farine, cuire 2 min sans colorer.",
      "Mouiller avec 500ml de bouillon de cuisson. Fouetter jusqu'a epaississement.",
      "Sauter champignons dans beurre a part. Ajouter citron pour eviter noircissement.",
      "Hors du feu: melanger jaunes + creme, incorporer a la sauce en fouettant.",
      "Ajouter veau et champignons dans la sauce. Servir avec riz.",
    ],
    techniques: ["braise", "poach"],
    tags: ["mijoté", "classique", "hiver", "sauce blanche"],
  },
];

/** Tous les plats français validés */
export const PLATS_FRANCAIS: DishProfile[] = [...LOT_1, ...LOT_2];
