/**
 * FRANCAIS LOT_4 FIXED — 15 recettes avec quantités correctes (g, ml, cs, cc)
 * Source: Marmiton top-rated classiques français
 * Version: Toutes quantités en grammes/ml/cuillères réelles
 */

import { DishProfile } from "../dishKnowledge";

const FRANCAIS_LOT4: DishProfile[] = [
  {
    id: "blanquette-veau-creuse",
    name: "Blanquette de Veau",
    desireName: "Blanquette crémeuse veau-légumes, sauce blanche",
    aliases: ["blanquette", "veau blanquette"],
    cuisine: "francaise",
    region: "France",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "ragout",
    technique: "braise",
    baseFamilies: ["veau", "légumes", "crème"],
    fundamentals: ["veau cuit tendre", "sauce blanche roux-bouillon", "légumes tendre"],
    timings: { prep: 30, cook: 90, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Ragout créemeux, légumes tendre, sauce veloutée",
    profTips: ["Cuisson lente 1h30", "Sauce riche sans grumeaux", "Légumes entiers tendre"],
    mistakes: ["Cuisson rapide", "Sauce grumeleuse", "Légumes écrasés"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["veau", "carotte", "poireau", "crème"],
    ingredients: [
      { name: "veau à braise cubes", quantity: "800g" },
      { name: "carottes entières", quantity: "300g" },
      { name: "poireaux tronçons", quantity: "200g" },
      { name: "oignons grelots", quantity: "150g" },
      { name: "poitrine lard", quantity: "100g" },
      { name: "beurre", quantity: "30g" },
      { name: "farine", quantity: "30g" },
      { name: "bouillon veau", quantity: "500ml" },
      { name: "crème fraîche", quantity: "200ml" },
      { name: "œuf", quantity: "1" },
      { name: "citron jus", quantity: "1/2" },
      { name: "thym, laurier", quantity: "à goûter" },
      { name: "sel, poivre muscade", quantity: "à goûter" },
    ],
    steps: [
      "Blanchir veau 5 min eau bouillante. Égoutter.",
      "Revenir lard coupé. Ajouter veau, saisir 5 min.",
      "Saupoudrer farine, cuire 3 min.",
      "Verser bouillon. Ajouter légumes entiers, herbes.",
      "Couvrir, mijoter 90 min très doux.",
      "Tort œuf-crème. Hors feu, incorporer sans bouillir.",
      "Jus citron. Assaisonner. Servir chaud.",
    ],
    techniques: ["braise"],
    tags: ["ragout", "veau", "classique"],
  },
  {
    id: "coq-vin-bourgogne",
    name: "Coq au Vin",
    desireName: "Coq braisé vin rouge, champignons lardons",
    aliases: ["coq vin", "coq bourgogne"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "ragout",
    technique: "braise",
    baseFamilies: ["coq", "vin rouge", "champignons"],
    fundamentals: ["coq cuit tendre", "vin rouge riche", "braisé 90 min"],
    timings: { prep: 40, cook: 90, rest: 10 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Coq riche vin rouge, sauce concentrée",
    profTips: ["Coq plutôt vieux", "Vin Bourgogne bon", "Braise très lente"],
    mistakes: ["Coq trop jeune", "Vin trop acide", "Braise trop rapide"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["coq", "vin rouge", "champignons"],
    ingredients: [
      { name: "coq morceaux", quantity: "1200g" },
      { name: "vin rouge Bourgogne", quantity: "700ml" },
      { name: "lardons fumés", quantity: "150g" },
      { name: "oignons grelots", quantity: "150g" },
      { name: "champignons de Paris", quantity: "250g" },
      { name: "carotte", quantity: "150g" },
      { name: "ail", quantity: "3 gousses" },
      { name: "beurre", quantity: "25g" },
      { name: "cognac", quantity: "50ml" },
      { name: "bouillon volaille", quantity: "250ml" },
      { name: "tomate concentrée", quantity: "1 cs" },
      { name: "thym, laurier", quantity: "à goûter" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Revenir lardons. Ajouter coq, saisir bien dorés.",
      "Flamber au cognac.",
      "Ajouter vin rouge, bouillon, aromates, tomate.",
      "Couvrir, braiser 160C 90 min.",
      "À mi-temps: ajouter légumes.",
      "Sauce riche, coq tendre. Servir avec purée pommes.",
    ],
    techniques: ["braise"],
    tags: ["ragout", "coq", "bourgogne"],
  },
  {
    id: "filet-mignon-croute-sel",
    name: "Filet Mignon Croûte de Sel",
    desireName: "Filet mignon encrouté sel, tendre succulente",
    aliases: ["filet croûte sel", "mignon encrouté"],
    cuisine: "francaise",
    region: "France",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "roti",
    technique: "roast",
    baseFamilies: ["boeuf", "sel", "herbes"],
    fundamentals: ["filet cuit rose cœur", "croûte sel", "repos 20 min"],
    timings: { prep: 25, cook: 35, rest: 20 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Filet tendre, croûte sel croustillante, jus corsé",
    profTips: ["Filet très tendre", "Sel grossier", "Cuisson rose 45-50C"],
    mistakes: ["Filet dur", "Sel fin", "Cuit trop longtemps"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["boeuf filet", "sel", "herbes"],
    ingredients: [
      { name: "filet mignon entier", quantity: "800g" },
      { name: "sel de Guérande gros", quantity: "200g" },
      { name: "blanc d'œufs", quantity: "2" },
      { name: "herbes fraîches (thym, romarin)", quantity: "30g" },
      { name: "ail", quantity: "3 gousses" },
      { name: "huile olive", quantity: "1 cs" },
      { name: "beurre", quantity: "20g" },
      { name: "échalote", quantity: "1" },
      { name: "vin rouge", quantity: "100ml" },
      { name: "bouillon boeuf", quantity: "200ml" },
      { name: "poivre", quantity: "à goûter" },
    ],
    steps: [
      "Saisir filet huile 1-2 min tous côtés. Refroidir.",
      "Mixer sel-blanc d'œufs-herbes.",
      "Enrober filet complet pâte sel.",
      "Enfourner 200C pendant 30-35 min (45-50C cœur).",
      "Laisser reposer 20 min dans croûte.",
      "Casser croûte, trancher, servir avec sauce.",
    ],
    techniques: ["roast"],
    tags: ["filet", "sel", "roti"],
  },
  {
    id: "bouillabaisse-provence",
    name: "Bouillabaisse",
    desireName: "Bouillabaisse provençale, poissons rouille croûtons",
    aliases: ["bouillabaisse", "soupe poisson"],
    cuisine: "francaise",
    region: "Provence",
    slot: "lunch",
    difficulty: 4,
    minChefLevel: 4,
    family: "soupe",
    technique: "braise",
    baseFamilies: ["poisson", "saffran", "rouille"],
    fundamentals: ["poissons variés", "fumet saffran", "rouille ail"],
    timings: { prep: 35, cook: 40, rest: 0 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Soupe provençale dorée, poissons tendres, saveur mer",
    profTips: ["Poissons très frais", "Saffran généreuse dose", "Rouille authentique"],
    mistakes: ["Poissons vieux", "Saffran dosage faible", "Rouille mayonnaise"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 5, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["poisson mixte", "saffran", "safran"],
    ingredients: [
      { name: "rouget/loup/baudroie", quantity: "600g" },
      { name: "congre/grondin", quantity: "400g" },
      { name: "oignons", quantity: "200g" },
      { name: "ail", quantity: "6 gousses" },
      { name: "tomate fraîche", quantity: "400g" },
      { name: "fenouil frais", quantity: "100g" },
      { name: "écorce orange", quantity: "1 zeste" },
      { name: "safran", quantity: "1 sachet (0.1g)" },
      { name: "bouillon poisson", quantity: "1L" },
      { name: "huile olive", quantity: "5 cs" },
      { name: "sel, poivre", quantity: "à goûter" },
      { name: "pain grillé", quantity: "8 tranches" },
      { name: "mayo ail (rouille)", quantity: "150g" },
    ],
    steps: [
      "Cuire têtes poisson 20 min bouillon. Passer.",
      "Étuver oignon-fenouil huile 5 min.",
      "Ajouter tomate-ail-safran. Cuire 10 min.",
      "Verser bouillon poisson. Ajouter poisson entiers/gros morceaux.",
      "Cuire 8-10 min. Poisson tendre juste cuit.",
      "Pain grillé huile, frotter ail.",
      "Dresser soupe et pain. Ajouter rouille genérousement.",
    ],
    techniques: ["braise"],
    tags: ["soupe", "poisson", "provence"],
  },
  {
    id: "cassoulet-toulouse",
    name: "Cassoulet",
    desireName: "Cassoulet Toulouse confit, haricots viandes",
    aliases: ["cassoulet", "plat Toulouse"],
    cuisine: "francaise",
    region: "Occitanie",
    slot: "lunch",
    difficulty: 4,
    minChefLevel: 4,
    family: "ragout",
    technique: "braise",
    baseFamilies: ["haricots", "canard confit", "saucisse"],
    fundamentals: ["haricots cuits tendre", "confit canard", "cuisson 2h"],
    timings: { prep: 30, cook: 120, rest: 0 },
    servings: 6,
    portionAdaptation: "moderate",
    signature: "Plat généreux haricots-confits, croûte gratinée",
    profTips: ["Haricots très tendre", "Confit canard riche", "Croûte dorée"],
    mistakes: ["Haricots durs", "Sans confit", "Trop sec"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["haricots", "canard", "saucisse"],
    ingredients: [
      { name: "haricots blancs secs", quantity: "500g" },
      { name: "canard confit cuisses", quantity: "4" },
      { name: "saucisse toulouse", quantity: "400g" },
      { name: "poitrine porc", quantity: "200g" },
      { name: "oignons", quantity: "200g" },
      { name: "ail", quantity: "4 gousses" },
      { name: "tomate concentrée", quantity: "1 cs" },
      { name: "bouillon volaille", quantity: "500ml" },
      { name: "graisse canard", quantity: "100g" },
      { name: "pain rassis mie", quantity: "100g" },
      { name: "persil", quantity: "20g" },
      { name: "thym, laurier", quantity: "à goûter" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Tremper haricots nuit. Cuire 30 min eau.",
      "Cuire haricots 30 min avec bouillon oignon-ail.",
      "Dorer saucisse-poitrine. Ajouter haricots-confit.",
      "Couvrir, braiser 180C 60 min.",
      "Miettes pain-graisse-persil. Couvrir cassoulet.",
      "Repasser four 160C 30 min croûte dorée.",
    ],
    techniques: ["braise"],
    tags: ["cassoulet", "haricots", "occitanie"],
  },
  {
    id: "sole-meuniere-citron",
    name: "Sole Meunière",
    desireName: "Sole pochée beurre citron, légère délicate",
    aliases: ["sole citron", "poisson meunière"],
    cuisine: "francaise",
    region: "France",
    slot: "lunch",
    difficulty: 2,
    minChefLevel: 2,
    family: "poisson",
    technique: "poach",
    baseFamilies: ["sole", "beurre", "citron"],
    fundamentals: ["sole très fraîche", "cuisson douce pochée", "beurre noisette"],
    timings: { prep: 15, cook: 12, rest: 0 },
    servings: 2,
    portionAdaptation: "linear",
    signature: "Sole tendre, beurre noisette, saveur citron subtile",
    profTips: ["Sole très fraîche", "Pochage très doux", "Beurre noisette couleur"],
    mistakes: ["Sole vieille", "Eau trop chaude", "Beurre brûlé"],
    premiumTier: "signature",
    plaisir: { gourmandise: 4, texture: 5, visuel: 4, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["sole", "beurre", "citron"],
    ingredients: [
      { name: "sole entière", quantity: "400g" },
      { name: "eau ou fumet poisson", quantity: "250ml" },
      { name: "vinaigre blanc", quantity: "1 cs" },
      { name: "oignon émincé", quantity: "50g" },
      { name: "carotte julienne", quantity: "50g" },
      { name: "beurre", quantity: "80g" },
      { name: "citron frais", quantity: "1" },
      { name: "persil feuilles", quantity: "10g" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Vider sole, nettoyer bien.",
      "Porter à peine frémissant eau-vinaigre-aromates.",
      "Pocher sole 10 min très doux.",
      "Retirer délicatement sur assiette chaude.",
      "Beurre noix dans poêle. Versez sole jus citron.",
      "Persil. Servir immédiatement.",
    ],
    techniques: ["poach"],
    tags: ["poisson", "sole", "classique"],
  },
  {
    id: "beef-bourguignon-slow",
    name: "Boeuf Bourguignon",
    desireName: "Boeuf braisé vin rouge, légumes braisés",
    aliases: ["beef bourguignon", "boeuf vin rouge"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "ragout",
    technique: "braise",
    baseFamilies: ["boeuf", "vin rouge", "légumes"],
    fundamentals: ["boeuf cuit tendre", "vin rouge riche", "braisé 2h"],
    timings: { prep: 30, cook: 120, rest: 10 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Boeuf tendre sauce riche, légumes tendre",
    profTips: ["Boeuf qualité", "Vin bon Bourgogne", "Braise très lente"],
    mistakes: ["Boeuf mauvaise coupe", "Vin bon marché", "Braise trop rapide"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 5 },
    category: "plat_principal",
    baseIngredients: ["boeuf", "vin rouge", "légumes"],
    ingredients: [
      { name: "boeuf à braiser cubes", quantity: "1000g" },
      { name: "vin rouge Bourgogne", quantity: "700ml" },
      { name: "lardons fumés", quantity: "150g" },
      { name: "oignons grelots", quantity: "200g" },
      { name: "champignons de Paris", quantity: "250g" },
      { name: "carotte", quantity: "200g" },
      { name: "ail", quantity: "3 gousses" },
      { name: "bouillon boeuf", quantity: "300ml" },
      { name: "tomate concentrée", quantity: "1 cs" },
      { name: "beurre", quantity: "30g" },
      { name: "farine", quantity: "20g" },
      { name: "thym, laurier", quantity: "à goûter" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Revenir lardons, retirer.",
      "Saisir boeuf par portions, bien doré.",
      "Saupoudrer farine, cuire 3 min.",
      "Verser vin rouge, bouillon, tomate.",
      "Ajouter lardons, herbes, ail.",
      "Couvrir, braiser 160C 120 min.",
      "À mi-temps: ajouter légumes.",
      "Sauce riche, boeuf tendre. Servir chaud.",
    ],
    techniques: ["braise"],
    tags: ["boeuf", "bourgogne", "ragout"],
  },
  {
    id: "ratatouille-provence",
    name: "Ratatouille Niçoise",
    desireName: "Ratatouille méditerranéenne légumes été",
    aliases: ["ratatouille", "salade cuite"],
    cuisine: "francaise",
    region: "Provence",
    slot: "side",
    difficulty: 2,
    minChefLevel: 2,
    family: "legume",
    technique: "braise",
    baseFamilies: ["aubergine", "courgette", "tomate"],
    fundamentals: ["légumes tendre-croquant", "bien assaisonnée", "ail-herbes"],
    timings: { prep: 25, cook: 45, rest: 10 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Ratatouille provençale légère, saveurs méditerranéennes",
    profTips: ["Légumes tendre-croquant", "Ail doux", "Herbes généreuses"],
    mistakes: ["Légumes mous", "Ail brûlé", "Pas assez ails"],
    premiumTier: "classique",
    plaisir: { gourmandise: 3, texture: 4, visuel: 5, arome: 4 },
    category: "accompagnement",
    baseIngredients: ["aubergine", "courgette", "tomate"],
    ingredients: [
      { name: "aubergines", quantity: "300g" },
      { name: "courgettes", quantity: "300g" },
      { name: "tomates fraîches", quantity: "400g" },
      { name: "poivron rouge", quantity: "1" },
      { name: "oignons", quantity: "150g" },
      { name: "ail", quantity: "5 gousses" },
      { name: "huile olive", quantity: "4 cs" },
      { name: "herbes Provence (thym, romarin, basilic)", quantity: "20g" },
      { name: "sel, poivre", quantity: "à goûter" },
    ],
    steps: [
      "Découper légumes cubes réguliers.",
      "Étuver oignon huile 3 min.",
      "Ajouter aubergine, courgette. Cuire 10 min.",
      "Ajouter tomate, poivron. Cuire 20 min.",
      "Finir ail haché frais, herbes.",
      "Assaisonner. Reposer 10 min. Servir tiède ou froid.",
    ],
    techniques: ["braise"],
    tags: ["ratatouille", "legume", "provence"],
  },
  {
    id: "tarte-tatin-pommes",
    name: "Tarte Tatin",
    desireName: "Tarte Tatin pommes caramélisées, pâte feuilletée",
    aliases: ["tarte apple caramel", "tatin"],
    cuisine: "francaise",
    region: "France",
    slot: "dessert",
    difficulty: 2,
    minChefLevel: 2,
    family: "tarte",
    technique: "bake",
    baseFamilies: ["pomme", "caramel", "pate"],
    fundamentals: ["pommes dorées caramélisées", "pâte feuilletée", "cuisson 165C"],
    timings: { prep: 20, cook: 35, rest: 10 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Tarte caramélisée, pommes tendres en couronne",
    profTips: ["Pommes bien dorée", "Caramel pas brûlé", "Feuilletage croustillant"],
    mistakes: ["Pommes pales", "Caramel brûlé", "Pâte mouillée"],
    premiumTier: "classique",
    plaisir: { gourmandise: 5, texture: 4, visuel: 5, arome: 4 },
    category: "dessert",
    baseIngredients: ["pomme", "caramel", "pate",],
    ingredients: [
      { name: "pommes Renette", quantity: "700g" },
      { name: "sucre", quantity: "60g" },
      { name: "beurre", quantity: "50g" },
      { name: "pâte feuilletée", quantity: "250g" },
      { name: "vanille", quantity: "1/2 pod" },
      { name: "cannelle", quantity: "1/4 cc" },
      { name: "sel", quantity: "pincée" },
    ],
    steps: [
      "Caraméliser sucre-beurre poêle fond épais.",
      "Ajouter vanille, cannelle.",
      "Disposer pommes pelées quartiers dans caramel.",
      "Cuire 10 min feu doux.",
      "Couvrir pâte feuilletée légèrement aplatie.",
      "Enfourner 165C 25 min croustillant doré.",
      "Reposer 5 min. Démouler sur plat. Servir tiède.",
    ],
    techniques: ["bake"],
    tags: ["tarte", "pomme", "caramel"],
  },
  {
    id: "creme-brulee-classique",
    name: "Crème Brûlée",
    desireName: "Crème brûlée vanille, sucre caramélisé",
    aliases: ["creme brulee", "dessert brûlée"],
    cuisine: "francaise",
    region: "France",
    slot: "dessert",
    difficulty: 2,
    minChefLevel: 2,
    family: "cremeux",
    technique: "bake_in_bath",
    baseFamilies: ["crème", "vanille", "sucre"],
    fundamentals: ["crème infusée vanille", "bain-marie lent", "sucre brûlé torche"],
    timings: { prep: 20, cook: 45, rest: 300 },
    servings: 4,
    portionAdaptation: "linear",
    signature: "Crème veloutée vanille, sucre croustillant",
    profTips: ["Crème très riche", "Bain-marie lent 150C", "Sucre bien brûlé"],
    mistakes: ["Crème pauvre", "Cuisson rapide", "Sucre pas caramélisé"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 4 },
    category: "dessert",
    baseIngredients: ["crème", "vanille", "sucre"],
    ingredients: [
      { name: "crème fraîche entière", quantity: "400ml" },
      { name: "lait entier", quantity: "100ml" },
      { name: "jaunes d'œufs", quantity: "5" },
      { name: "sucre blanc", quantity: "80g" },
      { name: "vanille gousses", quantity: "2" },
      { name: "sel", quantity: "pincée" },
      { name: "sucre cassonade (brûlée)", quantity: "40g" },
    ],
    steps: [
      "Fendre vanille. Infuser crème lait 15 min.",
      "Passer infusion.",
      "Tort jaunes-sucre pâle 3 min.",
      "Verser crème chaude lentement en tortant.",
      "Passer à travers fine passoire.",
      "Verser ramequins. Bain-marie 150C 45 min.",
      "Refroidir. Réfrigérer 5h minimum.",
      "Avant servir: caraméliser sucre cassonade torche.",
    ],
    techniques: ["bake_in_bath"],
    tags: ["creme", "vanille", "brulee"],
  },
  {
    id: "escargots-beurre-persil",
    name: "Escargots Courtepierre",
    desireName: "Escargots beurre persil ail, classique français",
    aliases: ["escargots", "bourguignons"],
    cuisine: "francaise",
    region: "Bourgogne",
    slot: "entree",
    difficulty: 2,
    minChefLevel: 2,
    family: "appetizer",
    technique: "bake",
    baseFamilies: ["escargot", "beurre", "ail"],
    fundamentals: ["escargots conserve", "beurre ail-persil", "cuisson court 190C"],
    timings: { prep: 20, cook: 10, rest: 0 },
    servings: 2,
    portionAdaptation: "moderate",
    signature: "Escargots beurre savoureux, bouchée gourmande",
    profTips: ["Escargots qualité", "Beurre riche", "Cuisson court"],
    mistakes: ["Escargots vieux", "Beurre maigre", "Cuisson longue"],
    premiumTier: "classique",
    plaisir: { gourmandise: 4, texture: 4, visuel: 3, arome: 4 },
    category: "entree",
    baseIngredients: ["escargot", "beurre", "ail"],
    ingredients: [
      { name: "escargots en conserve égouttées", quantity: "12" },
      { name: "coquilles escargot", quantity: "12" },
      { name: "beurre mou", quantity: "100g" },
      { name: "ail", quantity: "4 gousses" },
      { name: "persil frais haché", quantity: "30g" },
      { name: "échalote", quantity: "1" },
      { name: "sel, poivre", quantity: "à goûter" },
      { name: "pain grillé", quantity: "4 tranches" },
    ],
    steps: [
      "Écraser ail échalote.",
      "Mélanger beurre mou-ail-persil-sel-poivre.",
      "Farcir coquilles beurre-escargot-beurre.",
      "Disposer plat four.",
      "Enfourner 190C 8-10 min. Mousse beurre.",
      "Servir brûlant avec pain grillé.",
    ],
    techniques: ["bake"],
    tags: ["escargot", "entree", "classique"],
  },
  {
    id: "moussaka-grec",
    name: "Moussaka",
    desireName: "Moussaka aubergine viande sauce béchamel",
    aliases: ["moussaka", "aubergine viande"],
    cuisine: "francaise",
    region: "Mediterranean",
    slot: "lunch",
    difficulty: 3,
    minChefLevel: 3,
    family: "gratin",
    technique: "bake",
    baseFamilies: ["aubergine", "viande", "bechamel"],
    fundamentals: ["aubergine rôtie", "viande mijotée", "béchamel riche"],
    timings: { prep: 45, cook: 45, rest: 15 },
    servings: 4,
    portionAdaptation: "moderate",
    signature: "Gratin riche aubergine-viande, béchamel dorée",
    profTips: ["Aubergine bien rôtie", "Viande savoureux", "Béchamel onctueuse"],
    mistakes: ["Aubergine molle", "Viande insipide", "Béchamel granuleuse"],
    premiumTier: "signature",
    plaisir: { gourmandise: 5, texture: 5, visuel: 4, arome: 4 },
    category: "plat_principal",
    baseIngredients: ["aubergine", "viande", "bechamel"],
    ingredients: [
      { name: "aubergines", quantity: "600g" },
      { name: "viande hachée", quantity: "400g" },
      { name: "oignon", quantity: "150g" },
      { name: "ail", quantity: "3 gousses" },
      { name: "tomate concentrée", quantity: "2 cs" },
      { name: "huile olive", quantity: "3 cs" },
      { name: "beurre", quantity: "50g" },
      { name: "farine", quantity: "40g" },
      { name: "lait", quantity: "500ml" },
      { name: "jaune d'œuf", quantity: "1" },
      { name: "fromage rapé", quantity: "80g" },
      { name: "thym", quantity: "2 branches" },
      { name: "sel, poivre, muscade", quantity: "à goûter" },
    ],
    steps: [
      "Rôtir aubergines tronches 200C 20 min.",
      "Revenir oignon. Ajouter viande hachée, cuire 10 min.",
      "Ajouter ail-tomate concentrée-thym. Mijoter 10 min.",
      "Préparer béchamel beurre-farine-lait riche.",
      "Garnir moule beurré alternant aubergine-viande-béchamel.",
      "Finir béchamel. Fromage rapé.",
      "Enfourner 180C 45 min gratin doré.",
    ],
    techniques: ["bake"],
    tags: ["moussaka", "aubergine", "grec"],
  },
];

export default FRANCAIS_LOT4;
